### ISSUE TITLE
E_NOTICE Undefined property: autoptimizeStyles::$already_minified

### ISSUE THREAD

**Issue by nekojira** [futtta/autoptimize#1]
Hey there, Autoptimize is one of the best minifcation/concatetation plugins I've found  - works a charm but I got this PHP Notice, perhaps you could check it out (the [XXXXXXX] is just the path to a server which I edited out)

    E_NOTICE  Undefined property: autoptimizeStyles::$already_minified -     
    [XXXXXXX]/app/plugins/autoptimize/classes/autoptimizeStyles.php:329 
    #7 [XXXXXXX]/app/plugins/autoptimize/autoptimize.php:265 - autoptimizeStyles->minify()
    #6 [internal call] - autoptimize_end_buffering('<!DOCTYPE html...', 5)
    #5 [XXXXXXX]/wp-includes/functions.php:3269 - ob_end_flush()
    #4 [internal call] - wp_ob_end_flush_all('')
    #3 [XXXXXXX]/pigafetta/wp-includes/plugin.php:496 - call_user_func_array('wp_ob_end_flus...',    Array[1])
    #2 [XXXXXXX]/wp-includes/load.php:613 - do_action('shutdown')
    #1 [internal call] - shutdown_action_hook()
    [XXXXXXX] Failed to load resource: net::ERR_CACHE_MISS

**Comment by futtta** [comment]
Thanks for reporting @nekojira. This indeed is a known bug in 1.9.2 that was however already solved on trunk on WordPress SVN and here on Github in https://github.com/futtta/autoptimize/commit/33ef6bee17ea3e3b0507102a78b3dafb0d3e60af. Can you check that fix out and confirm (or deny) that works for you?

frank

**Comment by nekojira** [comment]
thanks! seems ok not, the reference commit seems to fix that - sorry I was using the latest available version from WordPress and not the one from Github

**Comment by futtta** [comment]
OK, happy it works, this will be in 1.9.3 together with some other smaller fixes.
