### ISSUE TITLE
HTML Optimization Adds Extra Space To Type Attribute

### ISSUE THREAD

**Issue by treyrich** [futtta/autoptimize#101]
When we have HTML Optimization enabled on our site, any style elements who's tags are `<style type="text/css">...</style>` end up as `<style type=" text/css">...</style>` which is causing those styles to not be parsed by Chrome. This doesn't appear to be a problem if the `style` tag has other attributes, for example `<style class="some-class" type="text/css">...</style>` works just fine.

I haven't had a chance to dig too deeply into this issue, and I may not have time for a while, for now I've just disabled the HTML optimization.

**Comment by futtta** [comment]
tested on my dev environment and can't reproduce I'm afraid (or happy) to write @treyrich ;
`
<style type="text/css">a{b:c;}</style>`
stays 
`
<style type="text/css">a{b:c;}</style>`

frank

**Comment by treyrich** [comment]
@futtta I just tried on a fresh install with only the autoptimize plugin enabled, and the problem doesn't exist, so clearly something is conflicting with it elsewhere with the site I was experiencing this on. I'm not sure how much more time I can spend to drill down to where the conflict is though, so we can leave this open and I can look into it further when I get a chance, or close as it seems that the bug will be something else anyways?

**Comment by futtta** [comment]
will close as not generic, but do let me know if you ever find out what caused this @treyrich
