### ISSUE TITLE
CSS styles had problems during optimisation

### ISSUE THREAD

**Issue by Ontario7** [futtta/autoptimize#103]
Firstly thanks for the great plugin.
But seems that there are some problems during css opt.

web http://www.eurosegway.cz

screenshot 1, as should be https://i.gyazo.com/2ae39306f6a18f6ca1cd9b3d1acc40d5.jpg
screenshot 2, with problems https://i.gyazo.com/14458b3217a09473eb68e8b699f604a2.jpg

Screenshot 3 from google pagespeed page, you can see also the black header https://i.gyazo.com/ab5285640f4335a65cecbdf9ef1b081c.png

Turning on/off several times fond that the problem is in this plugin..

**Comment by futtta** [comment]
issues here are more about code-level problems with AO @Ontario7, but have a look at [the plugin's FAQ](https://wordpress.org/plugins/autoptimize/faq/) for info on troubleshooting and if you can't fix it [open a topic on the plugin's support forum](https://wordpress.org/support/plugin/autoptimize/#new-post), will be happy to assist you there :-)

**Comment by Ontario7** [comment]
Thanks, I did open the same tread on the support forum now
