### ISSUE TITLE
Slow requests to ao_speedup_cachebuster

### ISSUE THREAD

**Issue by mckernanin** [futtta/autoptimize#104]
Hello,
I have the plugin active on a staging site, and on every page load there's a 3-4 second request to /?ao_speedup_cachebuster. Sometimes it fires twice. Using a simple profiling plugin, here's a screenshot:

https://www.dropbox.com/s/stp43whmins1edf/Screenshot%202017-07-19%2012.05.17.png?dl=0

Site is running on ServerPilot, php7.1, WP 4.8. Let me know if you need any other info, happy to help track this down!

**Comment by futtta** [comment]
weird; that runs as part of autoptimizeCache::clearall in classes/autoptimizeCache.php and thus only gets executed when the cache has been cleared to preload it again immediately after that. so the question is; why (what) is triggering autoptimize::clearall?

**Comment by futtta** [comment]
did you have the time to investigate further @mckernanin ?

**Comment by mckernanin** [comment]
I have not, will try to soon.

**Comment by futtta** [comment]
@mckernanin no news yet, but that is good news maybe? :-)

**Comment by PatTheMav** [comment]
@futtta - FYI, faced the same issue on my blog, with the cache buster call being constantly triggered and hammering my whole FPM pool. Fully disabling and re-enabling Autoptimize seemed to have fixed it.

**Comment by futtta** [comment]
@PatTheMav this has been diagnosed as a problem with stale options ("alloptions") in external object caches (redis, memcached, ...) causing AO to continuously going through the "update"-procedure, including clearing the cache and preloading it (cfr. the cachebuster requests) and is fixed (well, worked around as [it's a core issue](https://core.trac.wordpress.org/ticket/31245)) in the upcoming 2.3.2, cfr. this commit.

quite the bug ... :-/

**Comment by PatTheMav** [comment]
@futtta - yeah I also had the redis-cache in mind, but I just disabled most adding wholesale and re-enabled them one by one. Then it worked and I couldn't debug it any further anymore.

**Comment by mckernanin** [comment]
Ahhhhh, that makes sense. I was using redis on the site in question.

**Comment by futtta** [comment]
this sure is a core bug that deserves an urgent fix after over 2 years of discussion, certainly when taking into account [they have a working fix](https://core.trac.wordpress.org/ticket/31245#comment:57) (well, workaround) for WP VIP for 2y already ...

**Comment by PatTheMav** [comment]
Sounds like a typical Wordpress thing.. That beast needs to be rewritten from scratch, but that will probably never happen. 😅
