### ISSUE TITLE
Request: Filters for deferred CSS loader

### ISSUE THREAD

**Issue by asadkn** [futtta/autoptimize#105]
It would be great if we could filter the loadCSS technique and the this.rel='stylesheet' technique used. We wanted to add a callback to both onload event of the preload link style tag and replace loadCSS with a modified solution for callbacks. 

Requesting filters for `classes/autoptimizeStyles.php`:

```
apply_filters( 'autoptimize_css_preload_onload', "this.rel=\'stylesheet\'" );
apply_filters( 'autoptimize_css_preload_polyfill', $preloadPolyfill );
```

**Comment by futtta** [comment]
Well, if you make this a git pull request I can merge if OK :-)

Can you use `autoptimize_filter_css_preload_onload` and `autoptimize_css_preload_polyfill` though?

**Comment by futtta** [comment]
PR merged, thanks for your contribution! :-)
