### ISSUE TITLE
Using static filename instead of hash for assets

### ISSUE THREAD

**Issue by amit777** [futtta/autoptimize#109]
I have a cluster of wordpress servers and it seems that when I update content on the main server, the other servers don't seem to have the newly generated auto-optimize filename.  I'm curious if there is a way to not use the hash.  And what factors influence the hash values?

**Comment by futtta** [comment]
there is no way not to use the hash @amit777, it is based on the contents of the aggregated but non-minified code (its an md5-checksum) and allows AO to check if the exact same code already exists in cache or not.

hope this clarifies,
frank
