### ISSUE TITLE
@supports media queries are erased upon minification

### ISSUE THREAD

**Issue by carasmo** [futtta/autoptimize#110]
I have this in my css for a blur and css before this for when it's not supported, works fine until packing.  Thanks!

```
@supports (-webkit-filter: blur(3px)) or (filter: blur(3px)) {

styles with the blur

}
```

**Comment by futtta** [comment]
probably same as [this support request](https://wordpress.org/support/topic/feature-queries-conditions-not-working/#post-9476519) on wordpress.org @carasmo, can you check if the problem indeed is with a space gone missing; `or(` instead of `or (`?

**Comment by carasmo** [comment]
Yes, that is why. ![screen shot 2017-09-08 at 6 10 51 pm](https://user-images.githubusercontent.com/1124594/30233046-1b2403ce-94c1-11e7-8157-9d685cfce344.png)

**Comment by futtta** [comment]
can you check [this commit](https://github.com/futtta/autoptimize/commit/50a694b09c96aad39f58bad5ab58ef5a5e7bf77b) out @carasmo

**Comment by carasmo** [comment]
Works great!

**Comment by carasmo** [comment]
![screen shot 2017-09-09 at 11 19 02 am](https://user-images.githubusercontent.com/1124594/30241404-b69973ae-9550-11e7-9c9e-51d5006c5bb0.png)

**Comment by carasmo** [comment]
Thank you!

**Comment by futtta** [comment]
closing this here, will go in next AO release (no eta yet though), thanks for your input & feedback!
