### ISSUE TITLE
Historic critical css 

### ISSUE THREAD

**Issue by rdowling90** [futtta/autoptimize#111]
I used a previous version of the Autoptimize plugin in 2016 using the 'Inline and Defer CSS' function. I since removed the plugin and want to remove this inlined CSS however it remains in my source code and can't see any way of removing it. Furthermore, the inlined CSS appears to be duplicated so I have two large inlined CSS files in the head of the page.

Is there a way I can remove all remnants of the Autoptimize plugin?

**Comment by futtta** [comment]
If you removed AO, then the inline CSS is probably (well, it cannot be but) someone else's @rdowling90. Can you share a URL so I can verify?

**Comment by rdowling90** [comment]
Hi, I have 2 lumps of inlined CSS. One I think is actually being produced by the theme with an id "theme-styles-inline-css", which is annoying but obviously not related to your plugin. The other with the id "critical-path-css" I'm sure is stuck there from a previous version of Autoptomize.

Here is an URL: https://www.cardinus.com/safety-dse/

**Comment by futtta** [comment]
no, AO's style ID is `aoatfcss`, cfr. https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeStyles.php#L536

maybe another plugin such as "above the fold" or "wp criticalcss"?

**Comment by rdowling90** [comment]
Ok well thank you for confirming for me. Very odd, I don't have any other plugins that would be doing it. I can only assume it's my theme Jupiter - which is a pain!

Thanks.

**Comment by futtta** [comment]
you're welcome, have a nice day! :)
