### ISSUE TITLE
Request - Combine Google Font Requests as an Option

### ISSUE THREAD

**Issue by idevwebs** [futtta/autoptimize#112]
Great plugin. Thank you for your works.

In addition to "Remove Google Fonts" I think it would be great if there was a "Combine Google Font Requests" option as well.

In pagespeed for a site I'm working on, ironically google complains about 6 separate font requests and suggests reducing number of requests. Between all the plugins and theme features, one can end up with many different font lines in the html. In my case, 6. 

All can be combined to a single request:

For example:

```
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Ubuntu:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
```
Down to:

`    <link href='//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700|Ubuntu:400,700,400italic,700italic' rel='stylesheet' type='text/css'>`

Hopefully this can be a quick addition to your plugin.

**Comment by futtta** [comment]
Thanks for the suggestion @idevwebs. although this is not my focus for now, I might add this at a later stage. And if you're into development, I do welcome Pull Requests, so ... :-)

**Comment by zytzagoo** [comment]
You may want to give https://github.com/zytzagoo/wp-google-fonts-optimizer a try :)

**Comment by futtta** [comment]
Update: [I'm working on "AO Extra"](https://blog.futtta.be/2017/11/29/another-autoptimize-experiment-extras/), which is a separate plugin for now but which will be integrated in Autoptimize and optimizing Google Fonts will actually be one of the new features (the last one to be added, working on it now).

**Comment by futtta** [comment]
I just committed the Google Font optimization (choice between "remove", "combine fonts & link" and "combine fonts and load asynchronous with webfont.js") feature to AO Extra (it will integrate with your Autoptimize installation), so if you want  download https://github.com/futtta/ao_extra/archive/master.zip and give it a spin maybe? :-)

**Comment by futtta** [comment]
closing here, feedback welcome at https://github.com/futtta/ao_extra/issues/ :-)

**Comment by futtta** [comment]
just added all of ao_extra to autoptimize dev version (here on github), feedback would be very welcome @idevwebs :-)

**Comment by winstondu** [comment]
@futtta , for some reason "combine fonts and load asynchronously with webfont.js" appears to not be asynchronous.

The webfont loader script is forced into head for my website (http://vanderbilthistoricalreview.com/), which is fine (and I expect intended), except for some reason my sites header code has wf.defer = 'true' even though you clearly wrote "async='true'" at https://github.com/futtta/ao_extra/blob/master/ao_extra.php#L225

This behavior occurs even with all of my other plugins turned off. I suspect somewhere in Auto-optimize, the plugin is aggressive adding "defer = 'true'".

I noticed in a user's question about a separate issue a couple of months, they also have "defer = 'true'" on their header despite having the option on. See:
https://wordpress.org/support/topic/combine-and-load-fonts-asy-webfont-js-not-working-properly/

**Comment by futtta** [comment]
@winstondu [2.3.4 indeed hat wf.defer='true'](https://github.com/futtta/autoptimize/blob/master/classlesses/autoptimizeExtra.php#L260), [2.4 (beta) has swiched back to wf.async='true'](https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeExtra.php#L280) so maybe take 2.4 out for a spin? :-)

**Comment by winstondu** [comment]
Ah. Didn't realize 2.3.4 still had defer = 'true'. Will definitely switch to 2.4.
Thanks so much for this excellent plugin.
