### ISSUE TITLE
WP_ROOT_DIR str_replace too greedy

### ISSUE THREAD

**Issue by jellycode** [futtta/autoptimize#114]
Great plugin but I'm having a bit of an issue with my setup.

My WP_CONTENT_DIR contains the AUTOPTIMIZE_WP_CONTENT_NAME in the path twice, so when it gets replaced on line 49 of the autoptimize.php file it destroys the path:

define('WP_ROOT_DIR',str_replace(AUTOPTIMIZE_WP_CONTENT_NAME,'',WP_CONTENT_DIR));

My path is
/srv/users/serverpilot/apps/website ... /web/app
and the AUTOPTIMIZE_WP_CONTENT_NAME is /app.

When the str_replace happens the path ends up like:

/srv/users/serverpilots/website ... /web

So instead of replacing it anywhere it appears, I changed it to only replace at the end:

define('WP_ROOT_DIR',substr(WP_CONTENT_DIR, 0, strlen(WP_CONTENT_DIR)-strlen(AUTOPTIMIZE_WP_CONTENT_NAME)));

Thoughts?

**Comment by jellycode** [comment]
Ok!

**Comment by futtta** [comment]
merged, thanks @jellycode
