### ISSUE TITLE
Gravity forms: JS errors

### ISSUE THREAD

**Issue by redpik** [futtta/autoptimize#118]
Hi,

Autoptimize not compatible with Gravity forms?

`SyntaxError: invalid regular expression flag r`
`ReferenceError: gformInitSpinner is not defined`

Anybody here has the same bug?
Thanx for your help.

**Comment by futtta** [comment]
Better open a topic [on the wordpress.org Autoptimize support forum](https://wordpress.org/support/plugin/autoptimize/#new-post) @redpik, issues here are with Autoptimize as such, not for compatibility problems. Ideally add a URL where we (I) can see this happening.
