### ISSUE TITLE
Add an option to combine dynamic css link with @import

### ISSUE THREAD

**Issue by kevinptt0323** [futtta/autoptimize#121]
This plugin will only combine css which is ending with `.css`.

Could you add an option to combine dynamic css with `@import`?

For example: Google Fonts.

[Ref](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeStyles.php#L146)

**Comment by futtta** [comment]
That would be opening Pandora's box, dynamically generated (and/ or remote) CSS (and JS) can change based on context. Making dynamic CSS (or JS) static does away with any business logic implemented, thereby potentially breaking things. Google Fonts is a good example actually; when requesting the CSS Google sends different responses to different browsers, which would not work when having AO import the CSS, effectively breaking your site (or at least the font-rendering) in some browsers.

So no, I'm afraid I don't want go there. On the bright side; [I'm working on "AO Extra"](https://blog.futtta.be/2017/11/29/another-autoptimize-experiment-extras/), which is a separate plugin for now but which will be integrated in Autoptimize and optimizing Google Fonts will actually be one of the new features.

**Comment by futtta** [comment]
I just committed the Google Font optimization (choice between "remove", "combine fonts & link" and "combine fonts and load asynchronous with webfont.js") feature to AO Extra (it will integrate with your Autoptimize installation), so if you want  download https://github.com/futtta/ao_extra/archive/master.zip and give it a spin maybe? :-)

**Comment by futtta** [comment]
now added all of ao_extra to autoptimize itself, testing would be appreciated @kevinptt0323 :-)
