### ISSUE TITLE
Exclude javascript from aggregates but also minify it. 

### ISSUE THREAD

**Issue by tdtgit** [futtta/autoptimize#124]
Thanks for awesome plugin. Using it for 2 years and still love it.

May I ask, if I want to exclude some script(s) from aggregates (not combine) but also minify it. Example: I have exclude OneSignal and it's not combined, great, but it's not minified too. Is AO have an option for minify but not aggregates?

![screen shot 2017-12-12 at 10 49 54](https://user-images.githubusercontent.com/4527866/33866642-74c08c6e-df2a-11e7-8acf-b991d42ee7f4.png)

**Comment by futtta** [comment]
No, AO can't minify excluded inline JS currently @tdtgit .

**Comment by tdtgit** [comment]
Will we have that feature in future?

**Comment by futtta** [comment]
Possibly :-)

**Comment by futtta** [comment]
AO 2.4 will by default minify excluded files (but not inline JS as that is pretty certain to "bust" the cache given the rapidly changing nature of inline JS)
