### ISSUE TITLE
Include remove DNS prefetch from Disable Emojis function

### ISSUE THREAD

**Issue by laserjobs** [futtta/autoptimize#127]
```
add_filter( 'wp_resource_hints', 'disable_emojis_remove_dns_prefetch', 10, 2 );

/**
 * Remove emoji CDN hostname from DNS prefetching hints.
 *
 * @param array $urls URLs to print for resource hints.
 * @param string $relation_type The relation type the URLs are printed for.
 * @return array Difference betwen the two arrays.
 */
function disable_emojis_remove_dns_prefetch( $urls, $relation_type ) {
 if ( 'dns-prefetch' == $relation_type ) {
 /** This filter is documented in wp-includes/formatting.php */
 $emoji_svg_url = apply_filters( 'emoji_svg_url', 'https://s.w.org/images/core/emoji/2/svg/' );

$urls = array_diff( $urls, array( $emoji_svg_url ) );
 }
```

Wordpress held this for moderation so I thought I should post it here too. 
Code from:
https://kinsta.com/knowledgebase/disable-emojis-wordpress/

**Comment by futtta** [comment]
can you check with the code in [this commit](https://github.com/futtta/autoptimize/commit/4b0354d02d29f5a347d4d025f747cccea9985173) @laserjobs ?

**Comment by tdtgit** [comment]
And [fonts.googleapis.com](fonts.googleapis.com) if **Remove Google fonts** option is enabled too. My code with multiple exclude:
```
function remove_unused_preconnect($urls){
	$unused = array('fonts.googleapis.com', 'https://s.w.org/images/core/emoji/2.3/svg/');
	foreach($unused as $script){
		if(in_array($script, $urls)){
			unset($urls[array_search($script, $urls)]);
		}
	}
	return $urls;
}
add_filter('wp_resource_hints', 'remove_unused_preconnect');
```

**Comment by futtta** [comment]
@tdtgit yes, but that should go elsewhere and only if gfonts are not left as is. I've added a TODO for me in the code as a reminder.

**Comment by tdtgit** [comment]
Ok I saw your todo commit

**Comment by futtta** [comment]
new commit https://github.com/futtta/autoptimize/commit/57846fa3eff4ad8b24bb55bf57a542159b139a2a should fix this, can you guys test this @tdtgit and @laserjobs ?

**Comment by tdtgit** [comment]
+1 worked for me with no error. Both emoji and Google fonts

**Comment by futtta** [comment]
closing, but @laserjobs can obviously reopen if it doesn't work :-)
