### ISSUE TITLE
Where to put cache alert increase code?

### ISSUE THREAD

**Issue by mrwizard64** [futtta/autoptimize#128]
Hey Frank,

Thank you so much for making this plugin... it's really great.  

Currently, Autoptimize is 'alarming' me that my cache is 1100mb, so I wanted to insert the following code:

add_filter('autoptimize_filter_cachecheck_maxsize','adjust_cachesize');
function adjust_cachesize() {
  return 4*512*1024;
}
where 4 * 512 * 1024 = 2GB

but where would I paste this?  

Hopefully it's not a big deal having 1100mb in the cache?  My dedicated server is pretty big and pretty fast... I'm assuming that it can handle it.

Thanks for your help man!

**Comment by tdtgit** [comment]
Your theme's functions.php file.

**Comment by mrwizard64** [comment]
Thank you for that man.  That 'worked'... except it seems like it lowered the previous value down to 100mb.  Definitely not the direction I wanted to go!

**Comment by futtta** [comment]
[have a look at this blogpost](http://blog.futtta.be/2016/09/15/autoptimize-cache-size-the-canary-in-the-coal-mine/) to see why cache size is but one (visible) part of the problem @mrwizard64
