### ISSUE TITLE
Use whitelist instead of blacklist for CSS/JS optimization

### ISSUE THREAD

**Issue by methnen** [futtta/autoptimize#13]
It would be great if there were an alternate method for deciding what gets optimized that used a whitelist instead of a blacklist.  This would come in especially handy with complex sites where coming up with a list of JS/CSS that _can_ be safely optimized is much easier than a list of all the stuff that can't.

**Comment by futtta** [comment]
That is not a bad idea ... Your suggestion happens to coincide with a request by a web agency to be able to "freeze" the configuration when a site is handed over to the customer. A whitelist would indeed allow just that, not aggregating CSS/ JS of whatever plugin a non-developer happens to install.

So yeah, this will probably get in AO at some point in time.

**Comment by methnen** [comment]
Glad to hear it, it'd be a big deal for us at least.

**Comment by futtta** [comment]
cfr. https://github.com/futtta/autoptimize/commit/414d6edbad4771b8e0c4eb9a709dfe9d7980a2ba

**Comment by futtta** [comment]
and for CSS; https://github.com/futtta/autoptimize/commit/aa5525bda5251e317ef9f6150e1f03fcc2fb162c

**Comment by futtta** [comment]
closing as per methnen's confirmation per mail that he's succesfully implemented this on his staging environment :-)
