### ISSUE TITLE
Include footer scripts?

### ISSUE THREAD

**Issue by yangkennyk** [futtta/autoptimize#130]
Is it possible to force include scripts that are enqueued in the footer? 

Some plugins enqueue their scripts in the footer and AO doesn't seem to pick them up resulting in the AO.js under the footer scripts.

Right now I'm dequeuing and enqueuing the scripts in the header to force to be included in the main AO file

**Comment by futtta** [comment]
hey @yangkennyk ; AO _normally_ includes all (local) scripts, so no force include needed really. the only known reason this is not happening is when using NextGen Gallery, which by default does some funky thing causing AO not so "see" JS in the footer. [The FAQ](https://wordpress.org/plugins/autoptimize/advanced/) has info on how to fix that though.
