### ISSUE TITLE
Filters to stop minifying aren't working

### ISSUE THREAD

**Issue by slz** [futtta/autoptimize#131]
I want to combine js/css files without minification.

I placed the following filters in my theme's functions.php file:
add_filter('autoptimize_js_do_minify', '__return_false',10,1);
add_filter('autoptimize_css_do_minify', '__return_false',10,1);

However, autoptimize still minifies the files exactly as before, so it appears these filters aren't stopping the minification.

**Comment by slz** [comment]
The problem appears to be due to the functions in classlesses/autoptimizeSpeedupper.php not using these filters before minimizing each file.

**Comment by futtta** [comment]
good catch @slz, fancy creating a pull request to fix that? :-)

**Comment by futtta** [comment]
Committed a fix, could you test @slz ?

**Comment by slz** [comment]
@futtta That fixed it. It's combining without minifying now. Thanks.
