### ISSUE TITLE
Problem with server time response

### ISSUE THREAD

**Issue by AdrianKuriata** [futtta/autoptimize#132]
Hi, i tested page with autoptimize plugin and after turn on (don't need turn on minify for anything). On PageSpeed test i getting 0,20sec server time response, without plugin i don't have this problem. So when i getting this issue i can't get 100/100 points. Do you have an idea how can i hang on it? Server is really good configured, i using HTTP/2.

**Comment by futtta** [comment]
sorry @AdrianKuriata, but this (github issues) is not the place for these kind of support questions, feel free to [open a topic on the wordpress.org support forum](https://wordpress.org/support/plugin/autoptimize#new-post) and I'll be happy to look into your question though.
