### ISSUE TITLE
Cannot get the settings page

### ISSUE THREAD

**Issue by Flyzy2005** [futtta/autoptimize#135]
Hi, futtta,
Thank you for your wonderful plugin!

There seems to be something wrong when I changed my host via copying the whole webroot to another VPS. It works well now, generating compressed css and js (I can also stop autoptimize and restart it again). But when I want to open the settings to add the uncompressed js list, I cannot get it.  It throws me a HTTP ERROR 564. All of other plugins's setting page is accessible.

How can I locate the problem? Or how can I add the uncompressed list without getting the setting page.

Thanks
![zwi qd hj e glaf21txi](https://user-images.githubusercontent.com/16304483/35261534-85cc438a-004b-11e8-9676-1ae4d85702f0.png)

**Comment by futtta** [comment]
I have never seen or heard of HTTP ERROR 564 I'm afraid @Flyzy2005 Moreover as it worked on your previous host, this looks like a problem at that level, no? Maybe ask them and/ or have a look at your phperror log?

As a workaround you can always go to `wp-admin/options.php` in your browser and search for `autoptimize_js_exclude` there, change the list and submit the form (bottom below).

I'm closing here now (these issues are for bugs at the code-level), but if you need you can [open a support ticket on the wordpress.org support forum](https://wordpress.org/support/plugin/autoptimize/#new-post).

**Comment by Flyzy2005** [comment]
Hello, futtta,
I have found out the error.

When I try to open the setting page of autoptimize, it will take so long time, up to 30s. But if I open the setting page of any other plugins, it will just take only 0.2s. 

Here are the screenshots:
![screenshot of auto](https://user-images.githubusercontent.com/16304483/35671341-107a3132-0776-11e8-857f-3ed17f6c9b26.png)
![screenshot of cache](https://user-images.githubusercontent.com/16304483/35671342-129d73fc-0776-11e8-8a50-25536a80f5ba.png)

**Comment by futtta** [comment]
you *really* need to ask on the wordpress support forum unless if you have questions/ remarks on code level  :-)

On code level you can probably fix the problem by having a good look at https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeConfig.php#L372 :-p

**Comment by Flyzy2005** [comment]
Okay, anyway, thank you for your reply :)
