### ISSUE TITLE
Adding support for storing generated files (cache) on Google Cloud Storage (GCS)

### ISSUE THREAD

**Issue by laszlocsontos** [futtta/autoptimize#136]
Hey @futtta,

I'm using WordPress on Google App Engine's (GAE) PHP runtime. One of the consequences of that is that writing files isn't directly possible, becuase the application's local file system is read only.

Google developed a plugin which moves files of the media library to GCS.

As AO requires a local directory (cache) to be writable, it doesn't currently work on GAE.

I'm thinking about implementing this ability, but I need your guidence how to do that. My primary language has been Java for a very long time and haven't really seen PHP in the last 15 years. :)

I did some preliminary analyses on AO's codebase and learned that you use the `file_put_contents` and `file_get_contents` calls in `autoptimizeCache.php`.

Fortunately both `file_put_contents` and `file_get_contents` are fully supported by GAE, as well as a bunch of other [PHP filesystem functions](https://cloud.google.com/appengine/docs/standard/php/googlestorage/advanced#php_filesystem_functions_support_on_google_cloud_storage).

Example:
```
file_put_contents("gs://bucket_name/object_name", $newFileContent);
```

What probably needs to be changed is that `AUTOPTIMIZE_CACHE_DIR` should be configurable and in case of GCS, this would point to a GCS bucket.

The other consequence of using GCS is that the public link to generated (cached) files would also change and `AUTOPTIMIZE_CACHE_URL` should point to the public URL of the GCP bucket directly. For example: `https://storage.googleapis.com/bucket_name.appspot.com/object_name`.

Having all that said, you could please give me some starting points how to get started with contributing GAE support?

Many thanks!

Cheers,
László
**********
References:
[Reading and Writing Files / GAE PHP runtime](https://cloud.google.com/appengine/docs/standard/php/googlestorage/)
[PHP filesystem functions](https://cloud.google.com/appengine/docs/standard/php/googlestorage/advanced#php_filesystem_functions_support_on_google_cloud_storage)

**Comment by futtta** [comment]
For AUTOPTIMIZE_CACHE_URL you can use the `autoptimize_filter_base_cdnurl` (which changes the CDN base URL, before it's used to construct the Autoptimized URL's) or  `autoptimize_filter_base_replace_cdn` (which changes the Autoptimized URL after CDN replacement) filters.

For AUTOPTIMIZE_CACHE_DIR I could add a filter [in autoptimizeCache.php](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeCache.php#L11) to allow you to change the cachedir?

**Comment by laszlocsontos** [comment]
> For AUTOPTIMIZE_CACHE_DIR I could add a filter in autoptimizeCache.php to allow you to change the cachedir?

> For AUTOPTIMIZE_CACHE_DIR I could add a filter in autoptimizeCache.php to allow you to change the cachedir?

I think that could work. I'd really appreciate if you could add a filter for that.

**Comment by futtta** [comment]
[Done](https://github.com/futtta/autoptimize/commit/5ff884c78d1ba9e059d95bde86e540223e0e5f7c). I also replaced the constant which was still scattered throughout the file with the filtered variable, but you'll have to check to make sure all FS functions (e.g. also scandir) work with `gs://` file handles.

**Comment by laszlocsontos** [comment]
That was fast! :) Thanks!

**Comment by zytzagoo** [comment]
There's a reference to that constant in autoptimizeConfig.php too (meaning, when filtered, the settings page will not show the actual [filtered] value, but rather, the one defined early on in autoptimize.php?)

Also, conceptually, we now allow something defined as a constant to be changed (and, at that, **after** the _constant_ has been defined) -- kind of defeats the purpose of using a constant in the first place?

May I propose we just use apply_filters() before setting/defining the constant in the first place, and leave that other bunch of existing code as it was?

**Comment by futtta** [comment]
that indeed makes sense @zytzagoo !

**Comment by futtta** [comment]
@zytzagoo instead of using a filter (which might apply too late as AUTOPTIMIZE_CACHE_DIR is set very early, immediately when autoptimize.php is loaded and not linked to a wp core action/ hook) I'm thinking of only defining it if it has not been defined yet (in wp-config.php) as is already the case for the other constants. What do you think?

**Comment by zytzagoo** [comment]
Is the case of autoptimize.php being loaded but apply_filters() not being callable even possible? (I dont think so?)

I was thinking of using apply_filters() there, early, in autoptimize.php... but, sure, defining if it's not already defined is also an option, yes.

**Comment by futtta** [comment]
@zytzagoo I actually added apply_filters in autoptimize.php on my local dev maching and doing add_filter using the code_snippets plugin, but the result wasn't consistent; sometimes the filter got called, sometimes not (guess code_snippets hooks in too late), hence my fallback on constants.

**Comment by zytzagoo** [comment]
yeah, forgot about that plugin/use-case completely... 

only constants can really work as far as i understand the flow (unless we also init all our constants on some hook too, later than other plugins we rely on)

code_snippets plugin fires active snippets on plugins_loaded, which should be **after** autoptimize.php is loaded/executed, meaning, any filters to change the constant in question added inside a code snippet are added too late, and hence not being called any more (tho not sure how you had it working on/off.. it shouldnt work at all, but perhaps something else was also different between runs)

**Comment by futtta** [comment]
Looks good @zytzagoo I'll commit to this version as well.

so @laszlocsontos AUTOPTIMIZE_CACHE_DIR will not be a filter, but a constant you can set in wp-config.php
