### ISSUE TITLE
minify_excluded breaks stuff

### ISSUE THREAD

**Issue by futtta** [futtta/autoptimize#140]
cfr. https://wordpress.org/support/topic/css-url-are-not-rewriting-when-http-2-minify-without-combine-filter-is-used/#post-9992836 when minifying excluded CSS (guess this has no impact on JS) the paths are wrong.

**Comment by zytzagoo** [comment]
Yeah, we should probably call rewrite_assets() (or was it fixurls? or both?) somewhere in minify_single() when handling css specifically, and before handing the chunk of code over to autoptimizeCSSmin().

Or do it in autoptimizeCSSmin() "automagically", but that would require moving some code around and/or changing method scopes (at least) + who knows what existing stuff that might break.

**Comment by futtta** [comment]
should be fixed on `master` (which doesn't have rewrite_assets()) by calling fixurls() in minify_single(), would assume the same applies to `beta`? or do you prefer to do it differently?

**Comment by futtta** [comment]
[confirmed fixed on wordpress.org](https://wordpress.org/support/topic/css-url-are-not-rewriting-when-http-2-minify-without-combine-filter-is-used/#post-9993540)
