### ISSUE TITLE
Suggestion so the minify is more cache aware

### ISSUE THREAD

**Issue by kaziqta** [futtta/autoptimize#141]
The thing is I am using HTTP/2 Server push.

For every single page the cache files are different, is there a way a whole package, that is common can be created, so once the user gets the autoptimize minify files once, he doesn't require me to serve him new files, you understand the files be cached in the browser.

I used some code in the functions.php (works great):

```
add_filter('autoptimize_filter_cache_getname','pushAOFiles');
function pushAOFiles($in) {
  $uri = substr($in, 30);
  $pushType = substr($in,strrpos($in,".")+1) === "js" ? "script" : "style";
  header('link: <'.$uri.'>; rel=preload; type='.$pushType,false);
  return $in;
}

```

**Comment by futtta** [comment]
AO actually creates the cached files based on the (hash of) the contents of the aggregated CSS, so;

* page A: css-file1 + css-file2 + inline-css1
* page B: css-file1 + css-file2 + inline-css2
* page C: css-file1 + inline-css2
* page D: css-file1 + inline-css1

would all have different AO'ed CSS.

Possible solutions to lessen the impact:
* untick "also aggregate inline CSS"
* exclude any CSS that isn't used on most pages
* use the API to switch to a whitelist-approach, where AO only aggregates CSS that is whitetlisted

hope this clarifies,
frank
