### ISSUE TITLE
Update to work with PHP 7.2

### ISSUE THREAD

**Issue by fredroo** [futtta/autoptimize#142]
Hello, actually version not work with PHP 7.2

please update, a very important plugin for optimizing Wordpress

**Comment by futtta** [comment]
it actually works very well on PHP 7.2, the only thing is [there are warnings of deprecated functions](https://github.com/futtta/autoptimize/issues/134) which will be tackled in the 2.4 version. if you want you can already test that version by downloading [the zip-version from GitHub](https://github.com/futtta/autoptimize/tree/beta).

hope this clarifies :-)

**Comment by fredroo** [comment]
thanks @futtta
