### ISSUE TITLE
CloudFlare and WPengine integration (Just a question)

### ISSUE THREAD

**Issue by celsobessa** [futtta/autoptimize#144]
Hi, @futtta . Just checking if my understanding is right about CloudFlare and WPengine integration.

If I am hosted at WPEngine, using Cloudlflare Official plugina and AO, is my understanding that AO calls WPEngine cache purging and Cloudflare plugin listens to `autoptimize_action_cachepurged` hook. Therefore, if purge AO cache, WPE and CF caches purging should be triggered as well. 

Am I right?

**Comment by futtta** [comment]
-> yes, AO calls `WpeCommon::purge_varnish_cache();` so upon clearing AO's cache WPE Varnish cache should also be purged
-> if Cloudflare indeed hooks into `autoptimize_action_cachepurged`, then indeed they can purge their cache if that action fires

so yes, you should be right @celsobessa :-)
