### ISSUE TITLE
Can't install beta

### ISSUE THREAD

**Issue by oskarrough** [futtta/autoptimize#146]
Hi, I wanted to try out the 2.4.0 beta. I removed the older autoptimize plugin from my site and activated the new one.

`Fatal error: Cannot redeclare autoptimizeMain::maybe_run_partners_tab() in /srv/bindings/bd36f0d51850445da0ddf545cdd4b735/code/wp-content/plugins/autoptimize-2.4.0-beta-update1/classes/autoptimizeMain.php on line 190`

Wordpress 4.9.5

**Comment by oskarrough** [comment]
Sorry, it failed with the .zip download from here https://github.com/futtta/autoptimize/releases/tag/2.4.0-beta-update1

Downloading the repo as zip worked.

**Comment by futtta** [comment]
tried removing the tag earlier, did not succeed. any idea how @zytzagoo ?

**Comment by zytzagoo** [comment]
git tag deletions need to be pushed to all remotes in cases like these -- which has been done now, I dont see it listed anymore: https://github.com/futtta/autoptimize/tags
