### ISSUE TITLE
CDN URL's for Custom Fonts

### ISSUE THREAD

**Issue by vestaxpdx** [futtta/autoptimize#148]
Hi

Is there a way to filter the URLs used in CSS for fonts so I can serve them from my CDN (cloudfront) url and not locally.

I know there will be a headache of Cross Domain fonts but I just want to filter the URLS first and deal with that later.

I have tried the following but nothing seems to update. I even returned false in this function but it still outputs the CSS so perhaps I am in the wrong place.

```
function ac_set_cdn_urls_css($css)
{
    $cdn_domain = 'MY_CDN_URL';
    $site_domain = 'MY_SITE_DOMAIN';    

    //replace
    $css = str_replace("url('//". $site_domain, "url('//". $cdn_domain, $css);
    
    return $css;
}
add_filter('autoptimize_css_after_minify', 'ac_set_cdn_urls_css', 10, 1);
```

It would be great if it was possible or you could point me in the right direction.

Please note I am using custom self hosted fonts not just google hosted fonts etc.

Many thanks,

**Comment by futtta** [comment]
hey @vestaxpdx 

returning `false` would not work, as the code only applies the result from the filter if the resulting string is not empty :-)

have you tried returning `true` to the `autoptimize_filter_css_fonts_cdn` filter, in which case AO will use your CDN settings and apply them to fonts as well?

**Comment by futtta** [comment]
Hey @vestaxpdx; make sure to (also) test against the beta branch which might not have that caveat (it should not, smells like a bug really) and which will become AO 2.4 later this year. Or is this based on 2.4 already?

**Comment by vestaxpdx** [comment]
@futtta OK cool will do, this was on AO v2.3.4

**Comment by futtta** [comment]
any news on this @vestaxpdx or can I close?
