### ISSUE TITLE
Merge these changes for comparability with php 7.2

### ISSUE THREAD

**Issue by juslintek** [futtta/autoptimize#149]
Remade create_function to anonymous function
https://github.com/juslintek/autoptimize

**Comment by futtta** [comment]
have a look at [the beta branch](https://github.com/futtta/autoptimize/tree/beta) @juslintek all of that and much more is in there already :-)

(create_function still works with 7.2 by the way, it just warns it will not work in a future version, so AO is perfectly compatible with php 7.2. but I understand your point)
