### ISSUE TITLE
Critical css is not working correctly

### ISSUE THREAD

**Issue by whitlockwoodendesigns** [futtta/autoptimize#151]
Hi, Inline and deffer is on and I have tried code from both the top generators, but something is broken in my code I think. I'm no computer whizz so don't know where to look.
Cloudflare is on but no minification or railgun.
I am using Keycdn as well.
I did have an AMP plugin but didn't like it so got rid.  if there is `<html amp` in the response (as AMP-pages are optimized already) Is this my problem?
My cache is with siteground Memcache.
I'm lost and desperate help, please. https://www.whitlockwoodendesigns.com/product/red-european-twist-ballpoint-pen/

**Comment by tdtgit** [comment]
Try to disable Rocket Loader on Cloudflare.

**Comment by whitlockwoodendesigns** [comment]
Thanks for fast reply. I don't see an option for that in the settings, this is now done within cpanel on siteground. I have put it in development mode for a limited time so that should bypass all that?

**Comment by whitlockwoodendesigns** [comment]
Morning, any further suggestions or help would be appreciated.

**Comment by futtta** [comment]
Can you create a topic on[ the WordPress AO support forum](https://wordpress.org/support/plugin/autoptimize) @whitlockwoodendesigns ? Github issues are only for fundamental code-related bugs with AO, not for usage support. Thanks for understanding!
