### ISSUE TITLE
W3C validation fails.

### ISSUE THREAD

**Issue by 1n3JgKl9pQ6cUMrW** [futtta/autoptimize#152]
When using Autoptimize I do not get a 100% W3C validation at https://validator.w3.org/nu/

The reason is that Autoptimize ads ```type="text/javascript"``` to the optimized Javascript-tag, which triggers a warning / error during validation.

Is it possible to remove ```https://validator.w3.org/nu/``` from ```autoptimizeScripts.php``` at **line #318**

**Comment by futtta** [comment]
w3.org warnings are not very high on my priorities list to be honest @1n3JgKl9pQ6cUMrW  :-)

If this is really important for you, you can simply fix these "errors" with a call to AO's API like this;

```php
add_filter('autoptimize_html_after_minify','remove_js_type');
function remove_js_type($htmlIn) {
    return str_replace('type="text/javascript" ','',$htmlIn);
}
```
Have a nice day! :-)
frank
