### ISSUE TITLE
Autoptimize overrides default link colour

### ISSUE THREAD

**Issue by IndigoHomme** [futtta/autoptimize#157]
In the Divi Theme options/typography settings for link colour the value is #91d736.
On the rendered page the colour is overridden with this CSS:

.et_color_scheme_green a {
    color: #7cc68d;
}

from this link address:
https://joemihevc.ca/wp-content/cache/autoptimize/css/autoptimize_e0dcea0d0f2f3baf114ea9073352d20f.css

**Comment by futtta** [comment]
either remove `wp-content/cache` from the CSS optimization exclusion list (but keep an eye on your cache size) or add `wp-content/themes/Divi/style.css` to the same (comma separated) CSS exclusion list.

closing here (as config not code), but feel free to follow up on this in [the wordpress.org user support forum](https://wordpress.org/support/plugin/autoptimize) :-)
