### ISSUE TITLE
Async JavaScript instead of defer

### ISSUE THREAD

**Issue by chinchang** [futtta/autoptimize#158]
By default Autoptimizer is puts the `defer` attribute on the aggregated JS file. Is there a way to put `async` instead of `defer`?

**Comment by futtta** [comment]
yes, using the AO API, cfr. [example code here](https://github.com/futtta/autoptimize/blob/master/autoptimize_helper.php_example#L31-L36)

Alternatively you can [use the "async javascript" plugin](https://wordpress.org/plugins/async-javascript).

**Comment by chinchang** [comment]
Great! Thanks for the quick reply 😀
