### ISSUE TITLE
AMP Plugin validation

### ISSUE THREAD

**Issue by andremacola** [futtta/autoptimize#159]
I'm having a problem validating autoptimize with **custom templates** using amp-plugin even if I try to remove que style and script applied by autoptimize.

So what I am doing wrong?

```php
add_action('wp_enqueue_scripts', function() {
	if (is_amp_endpoint()) {
		wp_dequeue_style( 'autoptimize-toolbar' );
		wp_deregister_style('autoptimize-toolbar');
		wp_dequeue_script( 'autoptimize-toolbar' );
		wp_deregister_script('autoptimize-toolbar');
	}
}, PHP_INT_MAX, 0);
```

![captura de tela 2018-05-19 as 04 36 17](https://user-images.githubusercontent.com/3408809/40266269-51b4e326-5b1e-11e8-8ec5-9a6f8edd3b97.png)

**Comment by futtta** [comment]
well, is `is_amp_endpoint` triggered? maybe add error-logging in an `else` clause to make sure?

an alternative could be to disable the toolbar using;
`
add_filter('autoptimize_filter_toolbar_show','__return_false');`

that being said; those files [are only enqueued if the user is logged in](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeToolbar.php#L18) and `current_user_can( 'manage_options' )`, so these AMP errors will likely only be there for you (the site admin)?

**Comment by andremacola** [comment]
Yes, `is_amp_endpoint` is triggered `wp_dequeue_style` and `wp_deregister_style` is working. But `wp_dequeue_script` and `wp_deregister_script` is not.

I fixed this issue with another approach

```
add_filter( 'amp_pre_get_permalink', function( $pre, $post_id ) {
	return add_query_arg( amp_get_slug(), '', get_permalink( $post_id ) );
}, 10, 2 );

add_filter('init', function() {
	if (isset($_GET['amp'])) {
		add_filter('show_admin_bar', '__return_false');
	}
});
```

**Comment by futtta** [comment]
Taking into account that [AO only enqueues the CSS & JS for the toolbar if `is_admin_bar_showing` is true](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeToolbar.php#L23), this is a pretty weird situation you've got going on there really André :-)

But anyway, you worked around it so no worries. 

Have a nice day!
