### ISSUE TITLE
Remove comments from minified css and js for better Page Speed Insights score

### ISSUE THREAD

**Issue by AlexDubstone** [futtta/autoptimize#16]
Hello futta and all :)

I'm optimizing the pagespeed for a website and autoptimize was a huge time saver here. However Page Speed Insights is still telling me:

~~~
Minify CSS for the following resources to reduce their size by 727B (1% reduction).
~~~

Those 1% are simply the comments left in the minifed css file, mainly the license comments. Is there an option to remove these comments or are they left in the minifed version on purpose? I could not find  any information regarding that yet.

Regards
Alex

**Comment by futtta** [comment]
both minifiers (js & css) indeed leave "important" comments in place, cfr. https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/blob/master/cssmin.php#L224-L234 and https://github.com/mrclay/minify/blob/master/min/lib/JSMin.php#L402-L408

this is specifically done to leave the license information (which most open source licenses require) to be left in.

**Comment by noahjohn9259** [comment]
Do you have sample code to remove those important comments? I test my site on pagespeed and it complains about the important comment blocks ..

**Comment by futtta** [comment]
No I don't, sorry.To be completely honest; pagespeed might be saying it can compress 1% more, but from a real-world performance (which can be tested with http://webpagetest.org) point of view this is
