### ISSUE TITLE
2.4 beta: HTML output broken?

### ISSUE THREAD

**Issue by futtta** [futtta/autoptimize#161]
* to be confirmed/ looked into
* if confirmed, likely related to https://github.com/futtta/autoptimize/commit/e59190b49aaf693fd9b53daa1f475e544ea34704

**Comment by futtta** [comment]
follow-up: site on which problem was encountered had UTF-7 as charset (`blog_charset` option). question is under what circumstances a site would be on UTF-7 iso UTF-8 ..

**Comment by zytzagoo** [comment]
re utf-7: https://wordpress.stackexchange.com/questions/77108/if-a-hacker-changed-the-blog-charset-to-utf-7-does-that-make-wordpress-vulnerabl

**Comment by futtta** [comment]
yeah .. question is; can UTF-7 be used in a non-malicious scenario?

**Comment by futtta** [comment]
great, we can close this one :-)
