### ISSUE TITLE
Image Optimization - Specify Cache Validator

### ISSUE THREAD

**Issue by rainwilds** [futtta/autoptimize#162]
Hi,

I'm testing the new 2.4 beta. Love the integrated image optimization potential! Thank you! There's just one thing. Running GTMetrix.com's PageSpeed test shows that the compressed JPGs are returning without a Last-Modified or ETag header. So it's drastically causing a negative effect on PageSpeed score. 
Here's a screenshot.

![optimization](https://user-images.githubusercontent.com/39784786/40757508-34561810-64cc-11e8-9c07-441f022f83b3.png)

Any way to fix this?

Thanks,
David

**Comment by futtta** [comment]
I'll check with Shortpixel David!

**Comment by rainwilds** [comment]
Thanks Frank!

**Comment by rainwilds** [comment]
Hi Frank. Any news from Shortpixel? Thank you!

**Comment by futtta** [comment]
they confirmed they'll look into it :)

**Comment by futtta** [comment]
Just got confirmation they added Last-Modified, can you test @rainwilds ?

**Comment by rainwilds** [comment]
I just checked. For the most part, it works great now. In comparison to the last screenshot, only two images appear to be lacking Last-Modified, see image below.

![annotation](https://user-images.githubusercontent.com/39784786/40970146-15e4ce00-68fd-11e8-9d74-bb813eba4371.png)

**Comment by futtta** [comment]
Well, the last-modified header is there, so that would seem like a GTmetrix miss?

![image](https://user-images.githubusercontent.com/181297/40970532-3798e0d2-68bb-11e8-90c4-8b1dd76e38bf.png)

**Comment by rainwilds** [comment]
Hmm, it must be. No idea why. Perhaps a GTmetrix caching issue. In any case, thank you for following up on this!

**Comment by futtta** [comment]
Thanks you for testing @rainwilds ! I'll close this one, but don't hesitate to follow up here or in a new issue if you have any questions or remarks!

**Comment by futtta** [comment]
@rainwilds shortpixel switched to ETAG, feel free to re-test if GTmetrix understands that better :)

**Comment by rainwilds** [comment]
@futtta just re-tested; I got the same results as with Last-Modified. Still those images as above showing up as not having a cache validator. Must be something with GTmetrix. Thanks for keeping me posted! 👍
