### ISSUE TITLE
Version 2.4.0-beta-3 ShortPixel image dimension delivery issue

### ISSUE THREAD

**Issue by MollyWeb** [futtta/autoptimize#163]
Hey, 

Great news that shortpixel is included in Autoptimize. Enjoying it so far but noticing an issue with image dimensions being changed by shortpixel. The post thumbnail size is 820x445 but the shortpixel URL is bringing it in at 127x27. See the URL (I've covered up my domain name and file image for privacy) has the w_127, h_27 from shortpixel: https://api-ai.shortpixel.com/client/q_glossy,ret_img,w_127,h_27/https://mydomainhere.com/wp-content/uploads/2018/05/my_image_900_600_B-820x445.png

This happened on two of my sites I'm trying this beta version on with a lot of the images and one site was rectified by regenerating thumbnails across the site but this one above I can't seem to rectify. 

Any help would be appreciated! 

Thanks

** UPDATE ** So in my current case, it is inside of a flexslider and it appears to be using the width and height before the flexslider has finished loading. To rectify it, i've set the width and height on the images inside so it pulls the correct information. Thanks

**Comment by futtta** [comment]
AO Extra Image Optimization indeed uses the size set in the HTML (width and height of img src and width of srcsets) to tell shortpixel what size the images should be in @MollyWeb. Good you found the solution! :-)

**Comment by futtta** [comment]
Will close this one as it "works as designed" @MollyWeb , feel free to let me know if you have any other issue or question! And thanks for testing! :+1:
