### ISSUE TITLE
 Excluded CSS still served on their minified uri's on Autoptimize 2.4 Beta 

### ISSUE THREAD

**Issue by RealUn2ken** [futtta/autoptimize#164]
I understand that one of the new features of the Beta is excluded CSS or JS now gets minified.
that is a great thing but is there an option to opt out for specific files? 

I noticed on the beta version, that excluded css from autoptimize is still served and pushed through the their minified urls on the mark up. only dashicons and admin-bar.css can be fully excluded 
here is a sample
![screenshot_310](https://user-images.githubusercontent.com/11664809/41102182-d7b98542-6a98-11e8-9925-818cdbbfe8bd.png)
tried purging the cache and tested it with other css files being loaded by plugins and themes to be excluded and seems to be the case. I haven't tested it with javascript files though

Is it possible that there is a way that an excluded CSS left be untouched by autoptimize  and still be served with their original uri/ls? cause that is how autoptimize worked before this will be great for plugin flexibility.

**Comment by futtta** [comment]
Excluded CSS/ JS will indeed be minified by default, except if it is already minified (based on having .min or -min in the filename). 

You can force AO not to do so using the API @RealUn2ken, example code snippet;

```php
add_filter( 'autoptimize_filter_css_minify_excluded', 'css_unminify', 10, 2 );
function css_unminify ( $yesno, $url ) {
    if ( strpos( $url, 'dontminify.css' ) !== false ) {
        return false;
    } else {
        return $yesno;
    }
}
```

**Comment by RealUn2ken** [comment]
wow thank you for providing the solution. i did not know that autoptimize_filter_css_minify_excluded existed. you can close this issue now and thanks again.
