### ISSUE TITLE
Use WP Content URL instead of Site URL

### ISSUE THREAD

**Issue by redconfetti** [futtta/autoptimize#17]
After installing this plugin we found that the CDN URL feature wasn't working. After further investigation it seems pretty clear that you're performing a search and replace using the site_url, instead of the content_url.

https://github.com/futtta/autoptimize/blob/52c73d85/classes/autoptimizeBase.php#L184

See [Wordpress Codex - Editing WP-Config](http://codex.wordpress.org/Editing_wp-config.php#Moving_wp-content_folder).

I can see that themes themselves even use functions like [get_template_directory_uri](https://codex.wordpress.org/Function_Reference/get_template_directory_uri) or [get_stylesheet_uri](https://codex.wordpress.org/Function_Reference/get_stylesheet_uri).

It appears that these functions make use of [get_theme_root_uri](https://github.com/WordPress/WordPress/blob/master/wp-includes/theme.php#L578), which itself depends on the WP_CONTENT_DIR constant as a primary before trying WP_PLUGIN_DIR.

**Comment by futtta** [comment]
Considering http://your.site.com/wp-content/cache/autoptimize/js/autoptimize_123.js and a base cdn url of http://cdn.site.com, we need to replace your.site.com with cdn.site.com.

get_template_directory_uri would give http://your.site.com/wp-content/themes/yourtheme/
get_stylesheet_uri would give http://your.site.com/wp-content/themes/yourtheme/style.css
get_theme_root_uri would give http://your.site.com/wp-content/themes/
wp_content_url would give http://your.site.com/wp-content/
[site_url](https://codex.wordpress.org/Function_Reference/site_url) would give http://your.site.com/

so it seems to me site_url is exactly what I should be using?

frank

**Comment by redconfetti** [comment]
It looks to me that the site_url is not always the base URL as you expect, but might be a subdirectory. Just the same, Wordpress allows for the content directory to be redefined, as well as many other [directory types](https://codex.wordpress.org/Function_Reference/site_url#Related)

The project that I'm currently working on is using the [roots/bedrock](https://github.com/roots/bedrock/) configuration for Wordpress sites, which [redefines WP_CONTENT_URL](https://github.com/roots/bedrock/blob/df4e013a/config/application.php#L37) as under 'app' instead of 'wp-content', and the [WP_SITEURL is defined](https://github.com/roots/bedrock/blob/df4e013a/.env.example#L8) as in a 'wp' subfolder (installed by Composer).

With this alternative configuration, your plugin looks for `http://your.site.com/wp/` and doesn't find a match because our theme is linking to assets under `http://your.site.com/app/`.

In the Wordpress Codex article on [Changing The Site URL](https://codex.wordpress.org/Changing_The_Site_URL) it states:

> The "Site Address (URL)" setting is the address you want people to type in their browser to reach your WordPress blog.
> The "WordPress Address (URL)" setting is the address where your WordPress core files reside.

In the context of the Wordpress Settings -> General page, the field labelled "Site Address (URL)" corresponds to the 'home' in wp_options, while the "WordPress Address (URL)" corresponds to the 'siteurl' value.

Here is the output I get from WP-CLI when running these functions:
```
wp> content_url();
string(37) "http://example.com/app"
wp> home_url();
string(34) "https://example.com"
wp> site_url();
string(36) "http://example.com/wp"
```

To make your plugin compatible with all these different alternative URLs, especially since they can exist separately for themes, plugins, and uploads, perhaps the best solution is to abstract the base URL from the the site_url() or content_url() string (this seems more preferable).

So lets say that the JS, CSS, or HTML links to `http://example.com/app/uploads/09/22/image1.jpg`, the content_url() would return `http://example.com/app/`, and you could simply extract `http://example.com` and use that for the search and replace. No matter what sub-directory path is used in the URL, it will remain after the replace.

A CDN network that provides generic mirroring of assets should still find the assets if you're only replacing the domain name, and leaving whatever custom sub-directory path in URL, whether that be `/wp-content/uploads/09/22/image1.jpg` or something special like `/app/uploads/09/22/image1.jpg` or `/files/uploads/09/22/image1.jpg`.

**Comment by futtta** [comment]
I consider this somewhat of an edge case, but you are right, with setup where your renamed wp-content is not inside the directory where the WP core files reside (app vs wp) autoptimize's CDN functionality does not work currently.

I'll see if I can get this fixed with the (parse_url'ed) content_url() :-)

**Comment by futtta** [comment]
OK, commited a possible fix (limiting the changes to the url_replace_cdn function, as the constant is also used elsewhere), cfr. https://github.com/futtta/autoptimize/commit/2c1e94abfc5673973d3bd660398f9b00f64d9b7d

Would be great if you could test & confirm (or deny) this fixes your problem.

**Comment by redconfetti** [comment]
Thank you @futtta. I very much appreciate the energy you put into that commit. I was really just wanting to contribute some information about the issue I had identified for the benefit of everyone that uses it.

Unfortunately I'm trying to implement a method for using a mirroring CDN with the project I'm on by a deadline (this Saturday), and right now the Autoptimize plugin is intermittently not working at all with our application. I believe it has something to do with the use of ob_start(), which might be used by other plugins at the same time to modify the buffer output, though I'm not entirely sure.

I'm instead testing out a solution in my own plugin currently that registers an origin host and cd host string in two WP options. It then uses a str_replace on the URLs that I'm wanting to target.

```
  public function replace_host($url, $path='') {
    if ( is_admin() ) return $url;
    return str_replace($this->origin_host, $this->mirror_host, $url);
  }
```

I'm then applying this function as a filter for the script and stylesheet loaders, as well as the content_url() response.
```
add_filter('script_loader_src', array($this, 'replace_host'));
add_filter('style_loader_src', array($this, 'replace_host'));
add_filter('content_url', array($this,'replace_host'), 10, 2);
```

Unfortunately the content_url filter doesn't apply to asset links embedded in the post content, unless I define WP_CONTENT_URL in a file like wp-config.php.

I'm thinking that perhaps I'll instead have to do a find and replace on the expected origin paths for uploads (i.e. /uploads/) using a filter on [the_content](https://codex.wordpress.org/Plugin_API/Filter_Reference/the_content).

**Comment by futtta** [comment]
Good luck with your deadline @redconfetti, hope you'll have time to test the commit out later! :-)

**Comment by futtta** [comment]
Have you been able to check that change out @redconfetti ?

**Comment by futtta** [comment]
own testing revealed no issues, considered fixed unless told otherwise ;-)
