### ISSUE TITLE
Beta issues

### ISSUE THREAD

**Issue by FrankMeijer** [futtta/autoptimize#172]
Thanks for adding image optimization to an already great plugin!
I noticed two issues:
- My site is HTTPS but the requests to the ShortPixel API contain the image URL with HTTP, resulting in two requests from ShortPixel to my server (first HTTP, which is redirected to HTTPS).
- Images that are not intended to be displayed, e.g. those in the <head>, e.g. <meta property="og:image"...> and the like, are also processed by ShortPixel. They should not.

**Comment by futtta** [comment]
I tried reproducing the `og:image` issue, but did not succeed @FrankMeije. Based on the source-code this _should_ not happen either. Can you share a URL where I could see this happening?

**Comment by FrankMeijer** [comment]
Regarding og:image, I was wrong. It is another entry, generated by the WPSSO plugin _in the body_.
The code that is generated is in a non-displayed div, and I don't know what purpose it serves, but I don't think Autoptimize is able to exclude it:
```
<div class="wpsso-schema-image-for-pinterest" style="display:none;">
<img src="https://api-ai.shortpixel.com/client/q_glossy,ret_img/https://bla.com/blabla.jpg" width="0" height="0" style="width:0;height:0;" data-pin-description="Cr&eacute;er une carte de Saint-Valentin soi-m&ecirc;me est amusant avec ces tampons fabriqu&eacute;s &agrave; partir d&#039;un rouleau de carton et d&#039;une pomme de terre." alt="" />
</div>
```

**Comment by FrankMeijer** [comment]
Regarding SSL, I use CloudFlare flexible SSL, and that setup forces me to set WordPress Address to http, and Site Address to https.  See [here ](https://jonnyjordan.com/blog/how-to-setup-cloudflare-flexible-ssl-for-wordpress/).
site_url() returns the WordPress Address.  home_url() returns the Site Address, so if you used that, it should work (at least for me).

**Comment by futtta** [comment]
OK, just [pushed a commit](https://github.com/futtta/autoptimize/commit/ea688cf9c93e8a30fef368085a4a2150e2aa7c3d) that uses home_url() (hope no regressions happen) + a filter to allow whatever "normalized URL" to be changed. Would be great if you could test :)

**Comment by FrankMeijer** [comment]
Yes, that works! Hartelijk bedankt voor je snelle reaktie.

**Comment by futtta** [comment]
graag gedaan! in case of regression I might switch back, but then you could
use the filter to enforce HTTPS as with 2 lines of code (which I can
provide if need be).

**Comment by FrankMeijer** [comment]
Yes, of course.
I like it when a plugin has a lot of filters. I am using one of your filters to set the image quality. I think that is important enough to make it a setting in admin.

**Comment by futtta** [comment]
maybe it indeed is :-)

**Comment by FrankMeijer** [comment]
Oops, I was mistaken on the HTTPS issue (the first one in this thread).
[site_url()](https://codex.wordpress.org/Function_Reference/site_url) returns the proper scheme, it calls is_ssl() to determine what to use.
The actual reason for seeing http was that I call [wp_upload_dir()](https://developer.wordpress.org/reference/functions/wp_upload_dir/) in various places in my code to compute the image URLs, and that function does not take ssl into account.  I un-did your change and added a 'upload_dir' filter where I change http to https, and now it works fine.
I am really sorry for the churn.

**Comment by futtta** [comment]
no problem @FrankMeijer so https://github.com/futtta/autoptimize/commit/ea688cf9c93e8a30fef368085a4a2150e2aa7c3d is not needed?

**Comment by FrankMeijer** [comment]
That is correct. It is not needed.

**Comment by futtta** [comment]
> I am using one of your filters to set the image quality. I think that is important enough to make it a setting in admin.

well I ended up adding it; https://github.com/futtta/autoptimize/commit/303e55b7d1ecb74b6e1953e021b2e6a6838d7887

feedback welcome :-)

**Comment by FrankMeijer** [comment]
Very nice. Thank you.

Just one thing: In `get_img_quality_array()` you added filter `autoptimize_filter_extra_imgopt_quality` with the same name but different semantics as another filter (that I was using). I had to remove my filter function to get it to work, but you probably want to give these filters different names :-)

Also, I noticed the following in the WP debug.log:
```
[14-Jul-2018 14:06:28 UTC] PHP Notice:  Undefined variable: imgopt_w in /.../wp-content/plugins/autoptimize-beta/classes/autoptimizeExtra.php on line 343
[14-Jul-2018 14:06:28 UTC] PHP Notice:  Undefined variable: imgopt_h in /.../wp-content/plugins/autoptimize-beta/classes/autoptimizeExtra.php on line 343
[14-Jul-2018 14:06:28 UTC] PHP Notice:  Undefined variable: imgopt_w in /.../wp-content/plugins/autoptimize-beta/classes/autoptimizeExtra.php on line 343
[14-Jul-2018 14:06:28 UTC] PHP Notice:  Undefined variable: imgopt_h in /.../wp-content/plugins/autoptimize-beta/classes/autoptimizeExtra.php on line 343
```
This happened only the first time I started the new version (I think), and I don't know if it is related to the other issue.

**Comment by futtta** [comment]
Hmm, autoptimize_filter_extra_imgopt_quality was moved in the code, but as
far as I know (understand) it would still expect the same thing; a string
with the quality value (e.g. q_lossless). Does that not work?

regarding error in the debug-log; line 343 is return $in; and is in the
filter_preconnect_google_fonts() function, so I _think_ this predates the
installation of the new version?

**Comment by FrankMeijer** [comment]
In the version I retrieved on July 13, I see `autoptimize_filter_extra_imgopt_quality` twice: 
once on line 438 where it expects a string:
`           $quality         = apply_filters( 'autoptimize_filter_extra_imgopt_quality', 'q_' . $this->get_img_quality_string() );`
and once on line 548, where it expects an array of strings:
`$img_quality_array = apply_filters( 'autoptimize_filter_extra_imgopt_quality', $img_quality_array );`

Regarding the second point, the error in debug.log, you are probably right. I haven't seen that error since I upgraded.

**Comment by futtta** [comment]
good catch! the 548 one indeed needs to be renamed, will be
autoptimize_filter_extra_imgopt_quality_array :-)
