### ISSUE TITLE
autoptimizeBase.php str_is_valid_regex throwing fatal error

### ISSUE THREAD

**Issue by futtta** [futtta/autoptimize#173]
reported by beta-user;
* only happens when browsing on internal URL and when HTTP auth is active
* the `ImagickException` makes this weird
* happens since beta-3 and is also the case with most recent archive
* asked to rollback to beta-2 to see if this is a regression

```
Fatal error: Uncaught ImagickException: preg_match(): No ending matching delimiter '&gt;' found in /nas/content/staging/zerocatersite2/wp-content/plugins/autoptimize/classes/autoptimizeBase.php:558 

Stack trace: 
#0 /nas/content/staging/zerocatersite2/wp-content/plugins/autoptimize/classes/autoptimizeBase.php(558): preg_match('<!--[if', '') 
#1 /nas/content/staging/zerocatersite2/wp-content/plugins/autoptimize/classes/autoptimizeBase.php(583): autoptimizeBase->str_is_valid_regex('<!--[if') 
#2 /nas/content/staging/zerocatersite2/wp-content/plugins/autoptimize/classes/autoptimizeBase.php(232): autoptimizeBase->replace_contents_with_marker_if_exists('IEHACK', '<!--[if', '#<!--\\[if.*?\\[e...', '<!doctype html>...') 
#3 /nas/content/staging/zerocatersite2/wp-content/plugins/autoptimize/classes/autoptimizeScripts.php(132): autoptimizeBase->hide_iehacks('<!doctype html>...') 
#4 /nas/content/staging/zerocatersite2/wp-content/plugins/autoptimize/classes/autoptimizeMain.php(431): autoptimizeScripts->read(Array) 
#5 [internal function]: in /nas/content/staging/zerocatersite2/wp-content/plugins/autoptimize/classes/autoptimizeBase.php on line 558```

**Comment by zytzagoo** [comment]
interesing! any chance of getting our hands on the (ideally exact/complete) minimal markup that triggers this?

(since i’m assuming it’s not just due to iehacks being present somewhere in any kind of markup, or this would blow up a lot sooner i the wild?)

**Comment by zytzagoo** [comment]
What are the odds of cbb80e7 having an effect on this?

I mean, that commit is now a departure from "the way things were" conceptually, if compared to current master (2.3.4) -- first iehacks were restored, then comments, and it was the same in both the beta and master branches

I guess it will depend on the exact markup etc., but I guess the same issue/fix should be present in 2.3.4/master then too? If not, why not?

Or we need to dig a lot deeper.

**Comment by futtta** [comment]
re https://github.com/futtta/autoptimize/commit/cbb80e7782cda0fa5552fb1bbaaaa93255aa7994; theoretically this fix should also go in 2.3.4, but I consider the master branch frozen as I will not push out another 2.3.x version.

but i do consider the order of restoring in autoptimizeStyles wrong in all but current 2.4, because the order for hiding is:

1. hide noptimize
2. hide (no)scirpt
3. hide iehacks
4. hide comments

unhiding (restoring) should logically be done in the exact opposite way:
1. unhide comments
2. unhide iehacks
3. unhide (no)script
4. unhidenoptimize

which was not done so before. let's await the OP's feedback; he promised he would revert to 2.4-beta2 to see if the problem goes away. if it does we'll have to dig deeper, but I do feel the order of restoring in aoStyles was wrong before and is right now.

**Comment by futtta** [comment]
Just got confirmation from OP that the issue also occurs on AO 2.4-beta2 (so before https://github.com/futtta/autoptimize/commit/cbb80e7782cda0fa5552fb1bbaaaa93255aa7994).

**Comment by zytzagoo** [comment]
And the same error/exception happens with the most recent beta tree download/zip/checkout?

Is there a chance of running/installing the AO test suite in that environment to see if the simple tests for str_is_valid_regex() also blow up? (or perhaps they end up running fine, which could also help eliminate some things...)

I kind of feel like the environment has some extra error handling manipulations in there, which is why we're seeing weird/unrelated things in the initial trace, but without a lot more details about the env, it's impossible to say anything concrete...

**Comment by yasirahmedsiddiqui** [comment]
This error keep coming with beta-1 but disappear with AO 2.3.4

**Comment by futtta** [comment]
Thanks @yasirahmedsiddiqui , could you have a look at [Zytzagoo's questions](https://github.com/futtta/autoptimize/issues/173#issuecomment-406978503) as well? :-)

**Comment by yasirahmedsiddiqui** [comment]
if you guys required, i can give you a new install to investigate. the latest beta downloaded 15 days back and have same issue.

**Comment by futtta** [comment]
@yasirahmedsiddiqui if I remember correctly, this only occurs if;
* the site has basic auth on
* it is accessed on the internal IP-range of your hoster

is that correct? if so, can we even test (esp. considering the ip-range limitation)?

**Comment by futtta** [comment]
closing due to lack of feedback/ info and no other reports.
