### ISSUE TITLE
Exclude js filters does not exclude files in 2.4.0

### ISSUE THREAD

**Issue by Ridder90** [futtta/autoptimize#181]
Hi there. I have the v 2.3.4 (stable) and v 2.4.0-beta-4 installed. 

I am running the 2.4.0 because of the following warning:
```
 PHP Deprecated:  Function create_function() is deprecated in /var/www/html/wp-content/plugins/autoptimize/classes/autoptimizeBase.php on line 213
```
At the exclude scripts option i have the following string:
 `seal.js, js/jquery/jquery.js,tinymce,mytheme/dist` 
This is excluding all the js files in the `dist` folder of `mytheme`. This works in 2.3.4 but **not in 2.4.0**. 

Unfortunately all the files in dist folder get concatenated to. 

I am running WP  4.9.8 on PHP 7.2. Let me know if i can help.

**Comment by futtta** [comment]
wow, that's an ugly regression and -to my surprise- I can reproduce; I'll look into this and update here later tonight/ tomorrow.

groeten uit België!
frank

**Comment by futtta** [comment]
any news on this @Ridder90 ?

**Comment by Ridder90** [comment]
Hi Futta, sorry for the late response. I checked and you are right! The extra files where indeed the ones i wanted to excluded. I do however also want to exclude them from being minified by autoptimize because i already concat and minify my theme files with gulp. Doing it on run time with autoptimize seems to be a waste of resources. Please correct me if i am wrong.

**Comment by futtta** [comment]
> Doing it on run time with autoptimize seems to be a waste of resources. Please correct me if i am wrong.

correct, but AO does not re-minify if the file is minified according to the filename; xyz.min.js or 123-min.js will not get re-minified, 123.js and abc.js will. so tweaking your gulp setup to make sure the file is recognized as being minified should do the trick :-)

**Comment by Ridder90** [comment]
Great! Thanks for the tip. I still would like to have function for my development environment to leave the excluded scripts as they are. Because my development environment uses scripts unminified and with source maps. however I would still like to have autoptimize to concat en minifiy the Wordpress assets on dev.

Maybe xyz.dev.js and 123-dev.js can also be excluded...any thoughts?

**Comment by futtta** [comment]
you could use fhe autoptimize_filter_js_consider_minified filter (expects
an array) to declare dev.js as indicating a minified file, after which AO
will leave it as is :)

**Comment by Ridder90** [comment]
Perfect!
