### ISSUE TITLE
Error 500 upon opening settings

### ISSUE THREAD

**Issue by lorrandavid** [futtta/autoptimize#185]
I just have just installed the plugin and when I go to the settings page I get an error 500: **"The page cannot be displayed because an internal server error has occurred"**.

But here's what is really bothering me, I can visit all settings page of the plugin except for the first one. If I go to _?page=autoptimize_extra_ it works just fine.

Can someone help me?

**Comment by lorrandavid** [comment]
Wordpress is running v.4.8 and the plugin is the latest one. I don't have access to the folders in the server except for the wordpress one, is there another way to check for the error?

**Comment by hyperpress** [comment]
There are a lot of factors that can result in 500 errors. Can you ask your host support to look at their server logs to see if they provide more details?

**Comment by futtta** [comment]
@lorrandavid:

* latest version of the plugin = the version from wordpress.org (2.3.4) or the beta-version from github (2.4.0-beta4)?
* you'll indeed have to check with your hosting support if you don't have access to the PHP errorlog yourself.

**Comment by lorrandavid** [comment]
@futtta the version from wordpress.org but I also tested the beta one. I forgot to mention one thing, my server is an IIS, do you think this is the issue?

**Comment by futtta** [comment]
> my server is an IIS, do you think this is the issue?

should not matter really.

afraid we won't be able to troubleshoot this unless you(r hoster) can provide the PHP errorlog @lorrandavid, can you make that happen?

**Comment by futtta** [comment]
were you able to fix this @lorrandavid ? can I close the issue or do you want to follow up on this?

**Comment by lorrandavid** [comment]
Sorry for being late @futtta, I could not solve this issue but you can close it. I guess it has something to do with the server but my client doesn't want to get in touch with the hosting or things like that.

Thanks for the support.

**Comment by futtta** [comment]
thanks for the feedback anyhow @lorrandavid, have a nice day :-)
