### ISSUE TITLE
Autooptimize and App Engine / Cloud Storage

### ISSUE THREAD

**Issue by mshick** [futtta/autoptimize#187]
Building on #136 here: I've been working out an App Engine deployment of Wordpress. Autoptimize has a couple of remaining issues that I've seen:

- `LOCK_EX` is not supported with the Cloud Storage library, and will throw errors. 

- `AUTOPTIMIZE_CACHE_DIR` as utilized generates inconsistent, unwritable paths, due to a lack of normalization of the trailing slash. There are several places where filepaths are appended that presume a trailing slash, and others that presume a lack of a slash. The GCS library will not accept a poorly formed path like `gs://my-bucket/cache//index.html`.

I've monkey patched my plugin to deal with these details and it seems to write and read correctly. However, the excessive about of "snippet" checking I'm seeing leads to AO creating hugely inefficient renders. Turning the plugin on jacks a page render up from 2-3s to about 10s, and seems to confound batcache...

**Comment by futtta** [comment]
Afternoon Michael;
the beta-branch (which is set to become the official 2.4-release around end
sept.) does not have LOCK_EX any more and chances are the trailing slash
issue is also gone in that branch (there are a lot of improvements in
there), maybe check that out? :-)

regarding inefficient renders;
* how did you trace that down to the snippet-logic?
* is the problem related to slow(er) reads or writes to gs:// filesystem?
* how/ why would that confound batcache?

frank

**Comment by mshick** [comment]
@futtta thanks for getting back. Great to hear about the new release. I will test it out.

* The snippet logic slowness — yes, I do think it's from the slowness of the gs:// filesystem. I've disabled minification and am seeing more sane renders now.

* The batcache was a mistake / misread on my end.

* One thing you might want to consider — when using the gs:// filesystem, I found I needed to manually gzip the files and set the metadata appropriately to `contentEncoding: gzip`. This allows Cloud Storage to serve the files more efficiently. Not sure how specific to Cloud Storage you want to get though.

**Comment by futtta** [comment]
re. gezipping manually; have a look at the
autoptimize_filter_cache_create_static_gzip filter :-)

**Comment by futtta** [comment]
so just add a ".gz" suffix to each autoptimized URL? I would probably use
autoptimize_html_after_minify and do a regex to parse out the
autoptimize-links and add the suffix?

**Comment by futtta** [comment]
closing due to lack of actionable feedback, feel free to re-open if you can provide more info @mshick
