### ISSUE TITLE
Compatibility Issue with RegistrationMagic Plugin

### ISSUE THREAD

**Issue by Kishores10** [futtta/autoptimize#188]
Hi no wonder Autoptimize is great plugin but is has compatibilty issues with RegistrationMagic plugin, when Autoptimize is activated the RegistrationMagic Forms does not show up Recaptcha, when we deactivate Autoptimize the Recaptcha Shows Up in RegistrationMagic Forms. 
Secondly It also has some issues with 'Youzer' Plugin, I have reported this issues to both the Authors of Youzer and RegistrationMagic, But you also needs to check and make Autoptimize compatible with thses both plugins, as RegistrationMagic and Youzer both are much needed plugins and cant be compromized for Autoptimize.  

Hope you will resolve the issue asap, I am using Autoptimize version (Latest) made available through GitHub
Thanks
Kishore

**Comment by futtta** [comment]
Hi Kishore;
Github is only for code-related questions, user support if provided over at https://wordpress.org/support/plugin/autoptimize

But I can already give you some good news; you can fix this yourself by reconfiguring Autoptimize, see [the AO FAQ](https://wordpress.org/plugins/autoptimize/faq/) for info on how to troubleshoot.

Kind regards,
frank
