### ISSUE TITLE
Unable to update Autoptimize version 2.4.0-beta-4 to version 2.4.0-beta-5

### ISSUE THREAD

**Issue by blessedOn** [futtta/autoptimize#189]
Hi there,

I am unable to update Autoptimize version 2.4.0-beta-4 to version 2.4.0-beta-5. I am getting the following error anytime I tried to update:

**Mise à jour de l’extension Autoptimize (1/1)
Téléchargement de la mise à jour depuis https://api.github.com/repos/futtta/autoptimize/zipball/beta…
Décompression de la mise à jour…
Une erreur est survenue lors de la mise à jour de Autoptimize : L’archive n’a pas pu être installée. PCLZIP_ERR_BAD_FORMAT (-10) : Invalid archive structure**

Please, someone help.

**Comment by futtta** [comment]
easiest solution would be to download
https://github.com/futtta/autoptimize/archive/beta.zip manually and unzip
over the existing directory.

**Comment by blessedOn** [comment]
I have downloaded file and install it. Thanks for your help!

Le mar. 18 sept. 2018 à 06:33, frank goossens <notifications@github.com> a
écrit :

**Comment by blessedOn** [comment]
Hi there

I am unable to update Autoptimize version version 2.4.0-beta-5 to version
2.4.1-beta-1.

**Comment by futtta** [comment]
Probably an issue with permissions on the filesystem, you might have/ want
to update manually again.

**Comment by futtta** [comment]
filesystem permissions; as you installed beta-4 (or beta-3) manually it is
likely that had different filesystem permissions (or rather file
ownership), which cause updates to fail because the user under which
wordpress is running does not have the required right to overwrite the
files.

**Comment by blessedOn** [comment]
Hi FraNk

Can you send me the link to download and update the version 2.4.0-beta-5
which i am currently to version 2.4.1-beta-1.

Le dim. 30 sept. 2018 à 06:49, frank goossens <notifications@github.com> a
écrit :

**Comment by futtta** [comment]
that would be https://github.com/futtta/autoptimize/archive/beta.zip
@blessedon :)

**Comment by blessedOn** [comment]
Please, send me the link for autoptimize version 2.5.0-beta-1 so that i can
download and install it manually. I can’t install it directly through
wordpress.

Le dim. 30 sept. 2018 à 11:06, frank goossens <notifications@github.com> a
écrit :

**Comment by futtta** [comment]
same link as previously :)
