### ISSUE TITLE
WP_PLUGIN_DIR usage

### ISSUE THREAD

**Issue by szepeviktor** [futtta/autoptimize#19]
Please consider avoiding `WP_PLUGIN_DIR`
https://github.com/futtta/autoptimize/search?utf8=%E2%9C%93&q=WP_PLUGIN_DIR
and introduce a define for `WP_PLUGIN_DIR . '/autoptimize'`.

**Comment by szepeviktor** [comment]
That way the plugin can be renamed easyly.

**Comment by szepeviktor** [comment]
Meanwhile I am looking for where to insert the TOC.

**Comment by futtta** [comment]
OK, couple of commits done just now, should be OK.
