### ISSUE TITLE
10s

### ISSUE THREAD

**Issue by Dmole** [futtta/autoptimize#191]
Yesterdays upgrade made sites up to 10s slower for logged in users.
tested by enabaling and disabaling the plugin.
forced to enable caching for users or not use autoptimize.

**Comment by Dmole** [comment]
>  can you try disabling CSS or JS or HTML optimization to try to pinpoint the issue somewhat?

HTML adds no time, but CSS and JS apear to have about equal impact.

>  are there any errors in your PHP errorlog?

not at the times of the slow pages

>  did you change any settings?

no

>  ...front-end only...?

yes (wp-admin is fine)

>  what's the metric; time to first byte...?

yes TTFB

> ...multiple sites...?

yes all every site on every server has the same issue.
The indroduced delay seems to relate to HTML/JS size vs post count etc.

**Comment by futtta** [comment]
> The indroduced delay seems to relate to page complexity;

not sure I understand that one, can you explain?

**Comment by Dmole** [comment]
Sites with more js/css seem to be slower... 3 to 13 seconds is the observed range.

**Comment by futtta** [comment]
OK, first thing to do for me would be to somehow be able reproduce what
you're seeing (which I am not now). Can you provide me some info on your
hosting environment (PHP version), theme(s) used, plugins used, ...?

**Comment by Dmole** [comment]
I can give you a cloud server to test later, what TTFB are you observing?

**Comment by futtta** [comment]
same as always, between .2 and .8s. actually the CSS optimization was
updated and in all tests is _a lot_ faster, so ...

**Comment by futtta** [comment]
ah and I would obviously be interested in testing on a cloud server of your specs/ config @Dmole

**Comment by Dmole** [comment]
Fixed;
https://github.com/futtta/autoptimize/commit/51c52183e2a0b9b30e7cb013ebfef7fd878ef06a
