### ISSUE TITLE
imgopt: does not pick up img src without host

### ISSUE THREAD

**Issue by futtta** [futtta/autoptimize#194]
see https://wordpress.org/support/topic/image-cdn-loading-issues/#post-10741958

**Comment by zytzagoo** [comment]
This is already taken care of in https://github.com/zytzagoo/autoptimize/tree/imgopt-review via https://github.com/zytzagoo/autoptimize/commit/b189dc607aaee6ff698ce0ecf04bd895362a2f75

Just need time to finalize, rebase against latest beta (and perhaps squash some commits...)

**Comment by futtta** [comment]
:+1:

**Comment by zytzagoo** [comment]
The test for that specific case was added in https://github.com/zytzagoo/autoptimize/commit/95d91d507180f6b1ade8c3a7e5fab140014a4a4f and then it failed for subfolder installs, so then https://github.com/zytzagoo/autoptimize/commit/b189dc607aaee6ff698ce0ecf04bd895362a2f75 was added.
