### ISSUE TITLE
High CPU usage: on Apache with fpm version 2.4.0

### ISSUE THREAD

**Issue by bara666** [futtta/autoptimize#198]
There are any problem with last version 2.4.0 that exhaust my server, my configuration is Apache2 with PHP 7.2 over fpm. When update plugin, my server create fpm threads but never close it, all the thread use 100% CPU and Apache not respond.

**Comment by futtta** [comment]
Can you try 2.4.1-beta @bara666 ? you can download that from
https://github.com/futtta/autoptimize/archive/beta.zip

**Comment by futtta** [comment]
2.4.1 was released and (a.o.) had fixes for high loads due to dog-slow iconv_* functions. assuming this is OK now, feel free to comment if not @bara666
