### ISSUE TITLE
External libs

### ISSUE THREAD

**Issue by szepeviktor** [futtta/autoptimize#2]
Please consider a build script that clones and builds https://github.com/mrclay/minify for plugin releases.

**Comment by szepeviktor** [comment]
The same for js
https://github.com/carhartl/jquery-cookie

**Comment by szepeviktor** [comment]
That way you can leave out external libs from your repo.

**Comment by futtta** [comment]
hmmm ... Currently this github repo is more or less a mirror of the svn trunk at wordpress.org.  If/ when I decide to use Github as master, this would indeed make a lot of sense, so I'll keep this one open for future reference.

thanks Viktor!
frank

**Comment by futtta** [comment]
closing, this does not match my workflow.

**Comment by szepeviktor** [comment]
OK I see.

[off] Look! I am experimenting with WP performance by a family of plugins called Tiny cache.
They are really tiny plugins: https://github.com/szepeviktor/wordpress-plugin-construction/tree/master/tiny-cache
I would appreciate if you install them and give your opinion.

**Comment by futtta** [comment]
@szepeviktor looks _very_ interesting, why not package & distribute those as "autoptimize power-ups"? :-)

**Comment by szepeviktor** [comment]
Thank you for your idea.

One of them must be installed as an MU plugin and all of them need persistent object cache which seems rare in the shared hosting industry.
Plus the configuration must be done by constants and filters. 

I am really curious what your experience is.





-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by futtta** [comment]
> I am really curious what your experience is.

that might be difficult now; https://github.com/szepeviktor/wordpress-plugin-construction/commit/8d7cf50d009e07483006f85b0ee2c125e5e6eb10 ;-)

but don't have a persistent object cache myself i'm afraid, so not the ideal test subject :)

**Comment by szepeviktor** [comment]
> but don't have a persistent object cache myself i'm afraid, so not the ideal test subject :)

I am sorry. A persistent object cache makes WordPress - and anything else - at least 2-3× faster.

> that might be difficult now; szepeviktor/wordpress-plugin-construction@8d7cf50 ;-)

Excuse me. Moved to its own place: https://github.com/szepeviktor/tiny-cache

**Comment by szepeviktor** [comment]
Some fine hosting provers give you that.
e.g. [Hawk Host](https://github.com/szepeviktor/debian-server-tools/blob/master/Hosting.md#shared-hosting)

**Comment by futtta** [comment]
probably going to go for a VPS at Hetzner;
https://www.hetzner.com/virtual/matrix-virtual :-)
