### ISSUE TITLE
WP Filesystem API vs. file_put_contents()

### ISSUE THREAD

**Issue by szepeviktor** [futtta/autoptimize#20]
Please consider moving to Filesystem API.
Some users may not have direct file write permission or using Google App Engine.

**Comment by futtta** [comment]
Absolutely correct, but will require substantial refactoring, esp. to make sure the links to autoptimized CSS/ JS result in the cached CSS/ JS being fetched from FS/ GAE cloud storage bucket.

Giving this complexity and given the fact this isn't a feature anyone has ever requested (except you, here, now), I'll consider this of low priority.

frank

**Comment by futtta** [comment]
I did quick web-search on "wp_filesystem google app engine" I find no (immediate) confirmation that wp_filesystem automagically solves any filesystem issues. From what I read on https://cloud.google.com/appengine/docs/php/googlestorage/ the way to write files is by using the:

> Google Cloud Storage stream wrapper is built in to the run time, and is used when you supply a file name starting with gs://.

While WP's filesystem API tries to write using local filesystem, ftp or ssh.

So although I understand GAE has it's challenges (and AO won't work on there for now), I don't think wp_filesystem is the solution?

frank

**Comment by szepeviktor** [comment]
I think this plugin provides the WP FileSystem API implementation:
https://wordpress.org/plugins/google-app-engine/

**Comment by szepeviktor** [comment]
And WP's filesystem API would support any custom filesytem.

**Comment by futtta** [comment]
> I think this plugin provides the WP FileSystem API implementation:
> https://wordpress.org/plugins/google-app-engine/

I checked the code, and no, it does not extend wp_filesystem, it "only" has code to do [mail](https://github.com/GoogleCloudPlatform/appengine-wordpress-plugin/blob/master/modules/mail.php), [http-requests](https://github.com/GoogleCloudPlatform/appengine-wordpress-plugin/blob/master/modules/urlfetch.php) and [file-uploads](https://github.com/GoogleCloudPlatform/appengine-wordpress-plugin/blob/master/modules/uploads.php) using GAE.

> And WP's filesystem API would support any custom filesytem.

Had a look at the code (again) and It does not; it "only" supports [direct file access](https://github.com/WordPress/WordPress/blob/a4facedfeee65b6f30e107e1bf23e86890c0f71b/wp-admin/includes/class-wp-filesystem-direct.php), [ftp](https://github.com/WordPress/WordPress/blob/a4facedfeee65b6f30e107e1bf23e86890c0f71b/wp-admin/includes/class-wp-filesystem-ftpext.php) (+ [variation for ftp](https://github.com/WordPress/WordPress/blob/a4facedfeee65b6f30e107e1bf23e86890c0f71b/wp-admin/includes/class-wp-filesystem-ftpsockets.php)) or [ssh](https://github.com/WordPress/WordPress/blob/a4facedfeee65b6f30e107e1bf23e86890c0f71b/wp-admin/includes/class-wp-filesystem-ssh2.php), all of which won't work on GAE. This is the very reason why on GAE you actually have to update wp core, theme & plugins on your local machine and then deploy to GAE (as described on [this page](http://www.codeproject.com/Articles/792412/Migrate-WordPress-to-Google-App-Engine), under "8.Prepare local site for upload"; 

> Run all available updates, you will not be able to do this when the site is uploaded. To install plugins and updates you have to do it locally and then reupload. Therefor it’s a good idea to keep your local environment to be able to take care about this later on. 

So no, wp_filesystem does not help us to make AO work on GAE.

**Comment by szepeviktor** [comment]
Thank you.

> but a role of thumb is that caching and minifying plugins won’t work.

:smile:

**Comment by futtta** [comment]
> but a role of thumb is that caching and minifying plugins won’t work.

yeah ... I think I could make it work (writing the optimized files using Google Cloud Storage stream wrapper and injecting links to optimized code of the type wp-content/plugins/autoptimize/gae.php?id=xyz.css with gae.php using the stream wrapper to read the file), but it would introduce some complexity that -given the low amount of WP on GAE- I feel is not really worth it.

anyway, thanks for challenging me, I learned from it :-)

frank

**Comment by szepeviktor** [comment]
I think when a project uses GAE resources are optimized during the build process.

**Comment by futtta** [comment]
Doesn't look like it when checking the HTML source on https://gae-php-tips.appspot.com/...

There used to be mod_pagespeed integration in GAE, but [that was turned off late 2015](https://groups.google.com/forum/#!topic/page-speed-service-discuss/h4jyUpv6Bc8).
