### ISSUE TITLE
New Cache file created action hook.. will you accept a PR?

### ISSUE THREAD

**Issue by devbhosale** [futtta/autoptimize#200]
@futtta  Thank you so much for developing an excellent plugin.

for those using S3 uploads, it will be helpful to provide an action hook every time a new cache file is created and/or updated so that we can do CDN push.

Looks like all changes for this will have to be inside "autoptimizeCache.php" file. Is that correct?

Would you consider a Pull Request for this?

**Comment by futtta** [comment]
I will consider a PR, but you could use the existing
autoptimize_filter_cache_getname (should have been an action, but well ...)
which will provide you with the URL of all AO'ed CSS/ JS-files and if the
file referenced in that URL is not on the CDN then push it?

**Comment by futtta** [comment]
Any news on this @devbhosale or can I close this?

**Comment by devbhosale** [comment]
@futtta Please close.

I noticed that autoptimize can regenerate all the files in "cache" folder when the files are manually deleted...  my use case was wordpress cluster and serving "cache" files from CDN...
however, due to this feature of auto regeneration of files on delete, every node in the cluster can serve from its own local cache rather than a central CDN location...
