### ISSUE TITLE
2.4.0 breaks on iOS and Android

### ISSUE THREAD

**Issue by yumyo** [futtta/autoptimize#201]
Since version 2.4.0 when testing against real mobile devices, either iOS or Android, Autoptimize fail to run. Scripts are not aggregated and no autopmize.xxxx.js files is generated and enqueued.

The only solution for us has been downgrading to 2.3.4

**Comment by futtta** [comment]
Have not seen this happening yet @yumyo , can you provide some more info, like;

* what URL did you see this on?
* is there anything in the error log?
* can you [try downloading](https://downloads.wordpress.org/plugin/autoptimize.zip) & installing what will be the 2.4.1 version soon?

**Comment by yumyo** [comment]
Sorry for the delay @frutta, I will try to set up a test URL within today and also try to download & install 2.4.1

**Comment by futtta** [comment]
any news on this @yumyo, or can I close this?

**Comment by futtta** [comment]
closing due to lack of feedback, feel free to re-open when you can provide more info @yumyo
