### ISSUE TITLE
How to get cache file name to inline script?

### ISSUE THREAD

**Issue by tdtgit** [futtta/autoptimize#205]
I already know about `autoptimize_filter_cache_getname` filter but, I want to inline the name of the script to my Javascript. How can I archive this?

```
add_filter('autoptimize_filter_cache_getname', 'pushAOFiles');
function pushAOFiles($in) {
    $pushType = substr($in,strrpos($in,".")+1) === "js" ? "script" : "style";
    if($pushType == "script"){
        wp_add_inline_script('jquery', 'var minifiedJS = ' . $in . ';');
    }
}
```

Expected result:
```
<script>var minifiedJS = ao_c84c3140e7dc6fce0e01d282ea78d08f.js</script>
```

I tried `add_action` and `do_action` to `wp_enqueue_scripts` hook but I think I'm not good at it. Thanks for your help.

Oh... another question, not load this script with your handler, I mean not echo `<script src="ao_c84c3140e7dc6fce0e01d282ea78d08f"></script>`. Whole of this question, I want call minified script by my own function, Google Tag Manager, etc and I need AO filename :)

**Comment by futtta** [comment]
wp_enqueue_scripts and wp_add_inline_script are already executed long before AO kicks in, you could try parsing the optimized HTML (using the `autoptimize_html_after_minify` filter), extracting the filename there (optionally remove it too)  and then add it back in to the HTML in a JS-block?

**Comment by celsobessa** [comment]
Ages ago I tried to something similar using different techniques, the technique pointed by @futtta seems to be the best option.

**Comment by tdtgit** [comment]
Thanks. Thought parse HTML is the last option but seems there's no other choices. Will try and share after successful.

**Comment by tdtgit** [comment]
Here is the implement code in case anyone need. I use aggrate javscript function so I only have 1 file. Feel free to contribute if you have better performance code.

```
add_filter('autoptimize_html_after_minify', function($content) {
    $doc = new DOMDocument();
	$doc->loadHTML($content);

	foreach($doc->getElementsByTagName('script') as $script) {
		if($script->hasAttribute('src') && $script->hasAttribute('defer')) {
			$minJS = $doc->createElement('script', 'var minJS="' . $script->getAttribute('src') . '";');
			$doc->getElementsByTagName('body')[0]->appendChild($minJS);
			$script->parentNode->removeChild($script);
		}
	}

    return $doc->saveHTML();
}, 10, 1);
```

**Comment by futtta** [comment]
nice, thanks for the code snippet Anh Tuấn!

frank
