### ISSUE TITLE
Google Adsense

### ISSUE THREAD

**Issue by willstocks-tech** [futtta/autoptimize#206]
Hey Frank,

Me again!! ;)

Thought I'd open an issue on here, rather than clogging up the wp.org support forum!
So, for a couple of months, I'd been having issues with adsense ads not displaying on my blog. I've gone through weeks, if not months of diagnosis to no avail. There were no errors being thrown, no warnings - nothing! It was plain weird.
I finally managed to get in touch with the guys at Google Adsense who managed to work out that Autoptimize was actually minifying something to do with the ad units, in such a way that it would cause sporadic and not necessarily repeatable behaviour!
I've since wrapped all of my ad units in a `<!--noptimize--><!--/noptimize-->` tag, which seems to have done the trick! 

I don't know whether it's worth tackling this in one of a fewways:
1. Automatically wrapping adsense ads in a `noptimize` tag (janky... very janky, but in theory doable because the format is fairly "standard")?
2. Adding an FAQ to the list for Adsense users, warning that they should add `noptimize` tags around their adsense ads?
3. Adding an "Advanced"/"Extra" option to try and automatically cater for Google adsens ads (per note 1, but not "automatically appled to all"?

**Comment by futtta** [comment]
Could you specify this part Will?

> Autoptimize was actually minifying something to do with the ad units

**Comment by willstocks-tech** [comment]
I’ll go back to them and will ask for some more detail, as all they told me was:
>I have been in contact with one of our tech guys regarding your issue. It looks like the plugin you're using called autoptimize is minifying our ad code. Please kindly resolve the issue related to this plugin

**Comment by futtta** [comment]
OK, so if we get that detail and/ or if we can compare the output with and
without the noptimize tag, then we can see if/ how we can prevent this from
happening again within AO.

**Comment by willstocks-tech** [comment]
I’ve sent them an email asking for some clarification. 
Leave it with me though, I’ll also remove the noptimize tags from one of my units and we can try to compare the two?
I won’t be able to this evening, but I’ll give it a whirl first thing tomorrow morning (in around 12 hours!)

**Comment by willstocks-tech** [comment]
Right - I've removed the `<!--noptimize--><!--/noptimize-->` tags from the ad unit in the sidebar on my site (https://willstocks.co.uk). Below is my current Autoptimize config:

- [x] Optimize HTML Code
- [ ] Keep HTML comments

- [x] Optimize Javascript Code
- [x] Aggregate JS files
- [ ] Aggregate inline JS
- [ ] Force JS in head
- [x] Exclude scripts: `admin-bar.min.js, seal.js, js/jquery/jquery.js, adsbygoogle.js, pinit_main.js, webfont.js, /js/jquery.masonry.min.js, /js/jquery/jquery-migrate.min.js, /js/jquery/jquery-migrate.js, /js/imagesloaded.min.js, /wp-content/plugins/jetpack/modules/widgets/twitter-timeline-admin.js, /wp-content/plugins/contact-form-7/includes/js/scripts.js`
- [ ] Add try-catch wrapping

- [x] Optimize CSS
- [x] Aggregate CSS
- [ ] Aggregate inline CSS
- [ ] Generate data URIs for images
- [x] Inline and Defer
- [ ] Inline all CSS
- [x] Exclude CSS: admin-bar.min.css, dashicons.min.css, adminbar-780.min.css, jetpack.css, /wp-content/plugins/contact-form-7/includes/css/styles.css

- [x] Save aggregated script/CSS as static files?
- [ ] Optimize for logged in users

**Comment by futtta** [comment]
OK, now how does the adsense JS differ with and without the noptimize tags?

**Comment by willstocks-tech** [comment]
Right.
This ad unit is displaying correctly:
```
<div class="ads before_footer">
<div class="container"> 
<!--noptimize-->
<div class="row adsense-footer-ws">	
	<div id="adsense" style="max-width:100%;width:100%;">
		<!-- Will Stocks - Footer -->
		<ins class="adsbygoogle" style="display: block; height: 90px;" data-ad-client="ca-pub-5933273263680205" data-ad-slot="2285974578" data-ad-format="auto" data-full-width-responsive="true" data-adsbygoogle-status="done">
		<ins id="aswift_1_expand" style="display:inline-table;border:none;height:90px;margin:0;padding:0;position:relative;visibility:visible;width:960px;background-color:transparent;">
		<ins id="aswift_1_anchor" style="display:block;border:none;height:90px;margin:0;padding:0;position:relative;visibility:visible;width:960px;background-color:transparent;">
		<iframe width="960" height="90" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_1" name="aswift_1" style="left:0;position:absolute;top:0;width:960px;height:90px;"></iframe>
		</ins>
		</ins>
		</ins>
<script> (adsbygoogle = window.adsbygoogle || []).push({});</script>
	</div>
</div>
<!--/noptimize-->
</div>
</div>
```

Whilst this one is not showing anything at all:
```
<div id="adsense-sidebar" style="width:100%;">
 <ins class="adsbygoogle" style="display: block; max-width: 100%; margin-left: auto; margin-right: auto; text-align: center; height: 600px;" data-ad-client="ca-pub-5933273263680205" data-ad-slot="2753588877" data-ad-format="auto" data-full-width-responsive="true" data-adsbygoogle-status="done">
<ins id="aswift_0_expand" style="display:inline-table;border:none;height:600px;margin:0;padding:0;position:relative;visibility:visible;width:190px;background-color:transparent;">
<ins id="aswift_0_anchor" style="display:block;border:none;height:600px;margin:0;padding:0;position:relative;visibility:visible;width:190px;background-color:transparent;">
<iframe width="190" height="600" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_0" name="aswift_0" style="left:0;position:absolute;top:0;width:190px;height:600px;">
</iframe>
</ins>
</ins>
</ins>
  </div>
```

First thing I notice, the `<script> (adsbygoogle = window.adsbygoogle || []).push({});</script>` is missing from the ad unit that isn't showing. Other than that... I'm really not sure what's going on here?

**Comment by willstocks-tech** [comment]
It seems to do a bit of a "switcheroo" in terms of which ad unit does and doesn't show. I've just hard refreshed (as well as clear cache and hard refresh) the page in Chrome, and now I'm seeing the sidebar ad unit, but not the footer ad unit!

**Comment by futtta** [comment]
and if you disable HTML optimization?

**Comment by willstocks-tech** [comment]
Strangely, the `<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>` is still getting stripped out... which I assume is the issue?
Let me wrap that specifically in a `noptimize`, to see what happens

**Comment by willstocks-tech** [comment]
Nope - that didn't make a difference... 
I've _triple_ checked the widget, and the inline script is definitely there, but on the front end it seems to be going missing? Does that make any sense?!

**Comment by futtta** [comment]
that is very weird, I don't see how/ why AO would do that ... can you try
disabling just JS opt. and then just CSS opt. and see if either of those
make a difference?

**Comment by willstocks-tech** [comment]
Yes, not a problem - I'll give that a whirl shortly! :)

**Comment by willstocks-tech** [comment]
OK, fiddled with all settings and it's _definitely_ the JS optimization option
- [x] Optimise JavaScript Code
Disabled all forms of optmization - ads show
Enabled HTML - ads still show
Enabled CSS - ads still show
Enabled JS - ads faulty
Disabled HTML (left CSS and JS enabled) - ads faulty
Disabled CSS (only JS left enabled) - ads faulty
Disabled JS and enabled HTML and CSS - Ads work
Enabled JS, Disabled HTML and CSS and wrapped ads in a `noptimize` tag - ads still faulty!!

Just to confirm, in the JS section I only have the following enabled:
- [x] Optimise JavaScript Code
- [x] Aggregate JS files?
- [x] Exclude scripts from Autoptimize: admin-bar.min.js, seal.js, js/jquery/jquery.js, adsbygoogle.js, pinit_main.js, webfont.js, /js/jquery.masonry.min.js, /js/jquery/jquery-migrate.min.js, /js/jquery/jquery-migrate.js, /js/imagesloaded.min.js, /wp-content/plugins/jetpack/modules/widgets/twitter-timeline-admin.js, /wp-content/plugins/contact-form-7/includes/js/scripts.js

**Comment by willstocks-tech** [comment]
For some reason, this specific line: `<script> (adsbygoogle = window.adsbygoogle || []).push({});</script>` is being stripped out of the widgets. Not necessarily always the same widget either. Can sometime be footer, sometimes sidebar (most of the time it's the sidebar!)

**Comment by futtta** [comment]
OK, can you try adding just adsbygoogle in the comma-separated JS exclusion
list and test again?

**Comment by willstocks-tech** [comment]
Doesn't seem to have done the trick :( No difference

**Comment by willstocks-tech** [comment]
Would it make a difference if I change `<script>` to `<script id="adsbygoogle_script">` and add `adsbygoogle_script` to the exclusion list?

**Comment by futtta** [comment]
OK, so to find the simplest test-case possible, can you confirm (test) that
when you have

* a stock up to date wordpress
* with AO 2.4.1 with only JS optimiization on and aggregate inline JS off
* with 2 or more widgets that have just this block of code;

<script> (adsbygoogle = window.adsbygoogle || []).push({});</script>

then often (but not always) one or more of those script blocks disappear?

(I'm on holiday so can't dig in myself yet, but trying to collect all
relevant info)

**Comment by willstocks-tech** [comment]
I'll get a proper "test" environment spun up, with a twenty-something theme, AO 2.4.1 and a couple of these widgets ("Custom HTML" in this case).

I was surprised it was the JS option to be completely honest, simply because the aggregate **inline** option is disabled on my site!

Leave it with me, I'll see what I can do over the next couple of days!

**Comment by futtta** [comment]
thanks Will, much appreciated!

**Comment by willstocks-tech** [comment]
Sorry @futtta - I haven't had a chance to attack this head-on yet! I'm hoping that over the next couple of days, I'll be able to get a test site spun up, configured and with some data populated! :)

**Comment by willstocks-tech** [comment]
Hey Frank
I'm really sorry, I've been absolutely swamped with work over the past couple of weeks, I haven't yet had a chance to get a test environment setup as promised! I don't suppose you've managed to make any headway on this one?

**Comment by futtta** [comment]
I'll do a quick test of the minimal test case (https://github.com/futtta/autoptimize/issues/206#issuecomment-432256381) on my side, but I would be surprised I'll be able to reproduce to be honest :-/

**Comment by willstocks-tech** [comment]
It's really really weird - I'll try to get something setup my end as well this week, hopefully work clears down a little bit haha!

**Comment by futtta** [comment]
I coincidentally got a support request from a user who also has Google Ads and I checked the HTML source of his site (filectory.com) and it had 8 occurrences of `<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>` which seems confirm at least that AO does not _always_ strip out that code?

**Comment by willstocks-tech** [comment]
Hi Frank,
I can confirm that I'm seeing strange behaviour too... however for me I _only_ seem to have the issue with Widgets (I think!)
So: https://willstocks.co.uk/ - I see the issue in the two widget areas
But: https://willstocks.co.uk/review-soundpeats-a1-pro-wireless-on-ear-headphones/ - Multiple in-post content ads show perfectly fine?!

**Comment by willstocks-tech** [comment]
Hmmm, OK interesting! 
I also don't really understand why the `<!--noptimize--><!--\noptimize--> `tags were "ignored" as well... because the issue persisted. Only when I disable the JS entirely (per https://github.com/futtta/autoptimize/issues/206#issuecomment-432210255 ) does the issue "go away"

I still need to get that test site spun up!!!

**Comment by willstocks-tech** [comment]
Don't suppose you've had any further thoughts around this one Frank? 

I was thinking maybe I could try using one of the filters (such as `apply_filters( 'autoptimize_filter_js_minify_excluded', true, $url )` or similar?)? But it's not a "URL resouce"... it's an inline script?

**Comment by futtta** [comment]
Well, minify_excluded has no impact on inline JS, so can be ignored in this context. My problem is I can't reproduce Will, so I I'm kind of stuck here. Once you have a test-site spun up where you can reproduce I'll be happy to dig in there though :)

**Comment by willstocks-tech** [comment]
OK - done! https://test.willstocks.co.uk/ I'll find a way to send you over some creds!

**Comment by willstocks-tech** [comment]
You should get an email shortly :) Shout if you don't and I'll manually send over an email!

**Comment by futtta** [comment]
Had a quick look at the HTML and I see two occurences of

<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>

both with AO enabled and disabled (?ao_noptimize=1) ?

**Comment by willstocks-tech** [comment]
Just importing my site now so it's like-for-like. I have also checked:
https://willstocks.co.uk/ vs https://willstocks.co.uk/?ao_noptimize=1 and on the noptimize I see the ads perfectly fine, but not on the optimized version :(

**Comment by futtta** [comment]
ah, but then the assumption of that inline script getting zapped -which I
was looking for- might have been wrong, because when comparing the HTML
source of your site with and without AO i also see the 2 occurences so
there is no inline JS getting removed?

**Comment by willstocks-tech** [comment]
It tends to be sporadic for me in all honesty - sometimes it's there and sometimes it's not there :(
It's such a pain in the arse to replicate!! Haha

**Comment by futtta** [comment]
OK, ping me when the test-site is up to snuff and I'll see if I can get the
inline JS to disappear somehow by refreshing ... a lot :)

**Comment by willstocks-tech** [comment]
OK - you should be good to go now! I had to set you up as a user again, sorry :D Feel free to have at it entirely!!!!

**Comment by futtta** [comment]
so how sure are you that some of the inline JS getting lost sometimes? because I've done quite a bit of searches (?s=whateverstringicanthink of) and I have not been able to reproduce .. :-/

![image](https://user-images.githubusercontent.com/181297/49108102-9474f600-f287-11e8-8834-8389029d15ef.png)

**Comment by willstocks-tech** [comment]
Very interesting! I’m sure I saw the behaviour earlier!

I’m currently away from my laptop, so I will look again for you first thing
tomorrow to see if I can replicate.

Whether it’s any concern - I’m primarily running the latest stable Chrome
on a Windows 10 machine or macOS machine. I generally don’t use other
browsers, but sometimes do.

**Comment by futtta** [comment]
browser or OS should not make any difference as this concerns the HTML as
sent from the server (I'm on FF on Ubuntu Linux).

**Comment by willstocks-tech** [comment]
So I'm currently seeing:
![image](https://user-images.githubusercontent.com/43744514/49146506-2f0e1d00-f2fa-11e8-8352-964fce493c93.png)
and then further down the page:
![image](https://user-images.githubusercontent.com/43744514/49146545-48af6480-f2fa-11e8-8d4a-e580c1111750.png)

**Comment by futtta** [comment]
and that was on test or production? because I did some more refreshes and still can't reproduce?

what I can do is on test add debugging code that counts the number of occurrences of `(adsbygoogle = window.adsbygoogle || []).push({});` and log that to a debug log file before and after JS optimization? then if you can reproduce you can look at that logfile to see if AO indeed logged 1 occurrence iso 2 to confirm that something is off sometimes?

**Comment by willstocks-tech** [comment]
That sounds good to me!

I’ve just realised that that was prod after I migrated hosts earlier today!
I was flicking back and forth between my old and new host and my test
environment and must’ve gotten confused (also moved from Hummingbird to
W3TC)

I will try to replicate in test once the aforementioned debug code is
there! 😊

**Comment by futtta** [comment]
OK, 2 debug logging statements are in autoptimizeScripts.php, one before
and one after JS optimization, you can see the resulting logfile at
https://test.willstocks.co.uk/wp-content/cache/autoptimize/ao_debug.txt :-)

**Comment by willstocks-tech** [comment]
So I've been playing and it's showing 2 before, 2 after every time (except a few posts, where I see 4 - 7). Now I don't know if this helps, but:

Chrome "view-source":
```
<div id="adsense-sidebar" style="width:100%;">
    <ins class="adsbygoogle" style="display:block;max-width:100%;margin-left:auto;margin-right:auto;text-align:center;" data-ad-client="ca-pub-5933273263680205" data-ad-slot="2753588877" data-ad-format="auto" data-full-width-responsive="true">
</ins>
    <script>
        (adsbygoogle = window.adsbygoogle\ | \ | []).push({});
    </script>
</div>
```
Chrome devtools:
```
<div id="adsense-sidebar" style="width:100%;">
	<ins class="adsbygoogle" style="display: block; max-width: 100%; margin-left: auto; margin-right: auto; text-align: center; height: 600px;" data-ad-client="ca-pub-5933273263680205" data-ad-slot="2753588877" data-ad-format="auto" data-full-width-responsive="true" data-adsbygoogle-status="done">
		<ins id="aswift_0_expand" style="display:inline-table;border:none;height:600px;margin:0;padding:0;position:relative;visibility:visible;width:190px;background-color:transparent;">
			<ins id="aswift_0_anchor" style="display:block;border:none;height:600px;margin:0;padding:0;position:relative;visibility:visible;width:190px;background-color:transparent;">
				<iframe width="190" height="600" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_0" name="aswift_0" style="left:0;position:absolute;top:0;border:0px;width:190px;height:600px;"></iframe>
			</ins>
		</ins>
	</ins>
</div>
```

**Comment by willstocks-tech** [comment]
Devtools is _kind of_ what I would expect to see, as it means the script has started to work (as opposed to the view-source, which is the html provided by Google - no ad content). If you look further down the page you'll see (footer) a "correct" output:
```
<div class="ads before_footer">
	<div class="container">
		<div class="row adsense-footer-ws">
			<div id="adsense" style="max-width:100%;width:100%;">
				<ins class="adsbygoogle" style="display: block; height: 90px;" data-ad-client="ca-pub-5933273263680205" data-ad-slot="2285974578" data-ad-format="auto" data-full-width-responsive="true" data-adsbygoogle-status="done">
					<ins id="aswift_1_expand" style="display:inline-table;border:none;height:90px;margin:0;padding:0;position:relative;visibility:visible;width:960px;background-color:transparent;">
						<ins id="aswift_1_anchor" style="display:block;border:none;height:90px;margin:0;padding:0;position:relative;visibility:visible;width:960px;background-color:transparent;">
							<iframe width="960" height="90" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_1" name="aswift_1" style="left:0;position:absolute;top:0;border:0px;width:960px;height:90px;"></iframe>
						</ins>
					</ins>
				</ins>
				<script> (adsbygoogle = window.adsbygoogle || []).push({});</script>
			</div>
		</div>
	</div>
</div>
```

**Comment by willstocks-tech** [comment]
I've replaced both of these ad codes multiple times now as well. One thing that interests me here is in the _most_ problematic area (right sidebar 95% of the time!), view-source is showing: `(adsbygoogle = window.adsbygoogle\ | \ | []).push({});` vs `(adsbygoogle = window.adsbygoogle || []).push({});` (note the two \'s!)

**Comment by willstocks-tech** [comment]
Done a little more refreshing - still seeing 2 before 2 after (on the most part) :( no differing values!

**Comment by futtta** [comment]
Well, this does confirm that it is not AO causing inline JS to be removed
now and again Will.

**Comment by willstocks-tech** [comment]
It does indeed! :( I'm still so confused as to why the JS Optimization is breaking the ads though?

**Comment by futtta** [comment]
Well, as you have seen the inline JS disappear on occasion and as we now
know that it isn't AO removing it, the question becomes what is removing
that JS? because that still is the most credible explanation of why the ads
sometimes don't show? maybe the combination of AO with one of your other
plugins?

**Comment by willstocks-tech** [comment]
I'm going to deactivate all other plugins (except the one that is essential for my theme) and see what happens! :)

**Comment by willstocks-tech** [comment]
OK done - AO is now one of 7 active plugins. I'm still seeing the behaviour :(

**Comment by futtta** [comment]
Errr ... the inline JS being removed you mean?

**Comment by willstocks-tech** [comment]
The script tag still seems to show in view-source, but not in Chrome devtools. But I've disabled all except for core theme/media plugins and AO, and I'm still not seeing an ad in the sidebar, but I am in the footer/posts. I've even wrapped the sidebar in a nooptimize just to try it!

**Comment by willstocks-tech** [comment]
Sidebar:

view-source:https://test.willstocks.co.uk/:
```
<!--noptimize-->
<div id="adsense-sidebar" style="width:100%;">
	<!-- Will Stocks - Sidebar -->
	<ins class="adsbygoogle"
			 style="display:block;max-width:100%;margin-left:auto;margin-right:auto;text-align:center;"
			 data-ad-client="ca-pub-5933273263680205"
			 data-ad-slot="2753588877"
			 data-ad-format="auto"
			 data-full-width-responsive="true"></ins>
	<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
</div>
<!--/noptimize-->
```

Chrome dev tools:
```
<!--noptimize-->
<div id="adsense-sidebar" style="width:100%;">
	<!-- Will Stocks - Sidebar -->
	<ins class="adsbygoogle" style="display: block; max-width: 100%; margin-left: auto; margin-right: auto; text-align: center; height: 600px;" data-ad-client="ca-pub-5933273263680205" data-ad-slot="2753588877" data-ad-format="auto" data-full-width-responsive="true" data-adsbygoogle-status="done">
		<ins id="aswift_0_expand" style="display:inline-table;border:none;height:600px;margin:0;padding:0;position:relative;visibility:visible;width:190px;background-color:transparent;">
			<ins id="aswift_0_anchor" style="display:block;border:none;height:600px;margin:0;padding:0;position:relative;visibility:visible;width:190px;background-color:transparent;">
				<iframe width="190" height="600" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_0" name="aswift_0" style="left:0;position:absolute;top:0;border:0px;width:190px;height:600px;"></iframe>
			</ins>
		</ins>
	</ins>
</div>
<!--/noptimize-->
```

**Comment by willstocks-tech** [comment]
Footer:
view-source:https://test.willstocks.co.uk/:
```
<!--noptimize-->
<div class="row adsense-footer-ws">
	<div id="adsense" style="max-width:100%;width:100%;" >
		<!-- Will Stocks - Footer -->
		<ins class="adsbygoogle"
					 style="display:block"
					 data-ad-client="ca-pub-5933273263680205"
					 data-ad-slot="2285974578"
					 data-ad-format="auto"
					 data-full-width-responsive="true"></ins>
		<script> (adsbygoogle = window.adsbygoogle || []).push({});</script>
	</div>
</div>
<!--/noptimize-->
```

Chrome dev tools:
```
<!--noptimize-->
<div class="row adsense-footer-ws">
	<div id="adsense" style="max-width:100%;width:100%;">
		<!-- Will Stocks - Footer -->
		<ins class="adsbygoogle" style="display: block; height: 89px; width: 960px;" data-ad-client="ca-pub-5933273263680205" data-ad-slot="2285974578" data-ad-format="auto" data-full-width-responsive="true" data-adsbygoogle-status="done">
			<ins id="aswift_1_expand" style="display: inline-table; border: none; height: 89px; margin: 0px; padding: 0px; position: relative; visibility: visible; width: 960px; background-color: transparent;">
				<ins id="aswift_1_anchor" style="display: block; border: none; height: 89px; margin: 0px; padding: 0px; position: relative; visibility: visible; width: 960px; background-color: transparent; overflow: hidden;">
					<iframe width="960" height="89" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_1" name="aswift_1" style="left: 0px; position: absolute; top: 0px; border: 0px; width: 960px; height: 89px;"></iframe>
				</ins>
			</ins>
		</ins>
		<script> (adsbygoogle = window.adsbygoogle || []).push({});</script>
	</div>
</div>
<!--/noptimize-->
```

**Comment by futtta** [comment]
well, HTML source is what the browser starts out with, but then JS takes
over and changes the DOM which is reflected in the dev tools. so it looks
like there is some JS changing the DOM in ... an unexpected way.

**Comment by willstocks-tech** [comment]
Ads still show. If I enable aggregate again, ad disappears. Disable aggregate, ad still shows.

Strange, because Google ads are 3rd party so it's not like there's anything to aggregate??!

**Comment by willstocks-tech** [comment]
OK, another interesting thing... I enabled aggregate and then enabled force in head... ads show fine (jQuery error because by default I defer jQuery as it's not 100% necessary for ATF content for me). But the ads are now showing fine... I'm officially confused, so hopefully you can make some headway?

**Comment by futtta** [comment]
not really ... try excluding your theme from JS optimization and then
individual plugins to see which one is causing that problem?

**Comment by willstocks-tech** [comment]
We're on to something here... disabled my theme JS and I _appear_ to be getting ads now although I'm seeing a load of jQuery errors in the console now
I'm not sure how or why the theme JS would cause this issue... I'm going to see if I can get the theme devs to help out here! :)

**Comment by futtta** [comment]
maybe try excluding specific JS-files from your theme now?

**Comment by willstocks-tech** [comment]
It's one chunky file: https://test.willstocks.co.uk/wp-content/themes/linx/js/linx.min.js
If you're logged in to wp-admin, you'll see in the js folder there's a list of other js files. All of these are "pre-concatenated" into `linx.min.js`

**Comment by futtta** [comment]
Maybe there's an option to disable concatenation by the theme?

**Comment by willstocks-tech** [comment]
The guys are looking into it on the test site now - it _looks_ like 90% of the time it only affects the sidebar (per my message to them below). 
> It looks like the issue lies PRIMARILY in the sidebar. I've just moved a widget from the sidebar to the footer position - both ads-before-footer and footer show, but the ad left in the sidebar still doesn't show. If I then move the ad from the footer to the sidebar (so two ad units in the sidebar), both don't show!
> 
> VERY strange behaviour!!!

There's no "disable concat" option within the theme, but all of the relevant JS files are there so can be enqueued as necessary (which is the next step of their testing) :)

**Comment by willstocks-tech** [comment]
So it was something to do with jQuery and cloning the side navbar into off-canvas (all a bit beyond my skill set!!) that was causing the issue, not autoptimize (but _because_ my theme js was being autoptimized!)
>I just found that the reason was cloning the sidebar and appending to the off-canvas section.

**Comment by willstocks-tech** [comment]
Thank you for all of your assistance with this Frank! Thank you very much!

**Comment by futtta** [comment]
You're welcome Will, always interesting to learn about edge-cased like
that, even if it turns out to be a false positive! :)
