### ISSUE TITLE
Feature request: Google Fonts session storage

### ISSUE THREAD

**Issue by willstocks-tech** [futtta/autoptimize#207]
Hey Frank,
Cheeky FR/proposal for the future while I'm playing around:
If loading Google Fonts via webfont.js, it'd be great to improve performance/prevent FOUT/FOIT by utilizing:
```
WebFontConfig = { 
	google: { 
		families: [ 'fontfamily' ] 
	}, 
	active: function() { 
		sessionStorage.fonts = true; 
	} 
};
```
Then, utilizing this little script (could be passed through to `wp_head`):
```
<script> 
	(function() { 
		if (sessionStorage.fonts) { 
			console.log("fonts installed!"); 
			document.documentElement.className += " wf-active"; 
		}
	})(); 
</script>
```

That way, fonts are effectively "cached" in local storage and when a user returns to the site the font can be called from there as opposed to having to call out for it again - therefore allowing the font to be applied from the get go?

Might not be worth the effort - but I've found it to be quite interesting/useful!

**Comment by futtta** [comment]
interesting Will. if you think this is/ can get this in production-ready
state then I might be interested in a PR for this (maybe functionality
behind a default off filter to begin with).

**Comment by willstocks-tech** [comment]
I'll see what I can pull together!! :)

**Comment by willstocks-tech** [comment]
Just want to note - rather than utilising "sessionStorage" it's actually likely more worthwhile utilising "localStorage", so that the "cached fonts" are then available across sessions, rather than only during that session!
Useful info:
- https://stackoverflow.com/questions/5523140/html5-local-storage-vs-session-storage
- https://stackoverflow.com/questions/19867599/what-is-the-difference-between-localstorage-sessionstorage-session-and-cookies
- https://wpreset.com/localstorage-sessionstorage-cookies-detailed-comparison/
- https://jsperf.com/localstorage-vs-sessionstorage

**Comment by futtta** [comment]
browser-side caching mechanisms are a can of worms, but as local &
sessionstorage are actually meant for string-storage and Ilya Grigorik
advises against using localstorage or indexedDB (
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization#proper_caching_is_a_must),
but couldn't cachestorage (part of serviceworkers) be an alternative here?

**Comment by willstocks-tech** [comment]
I definitely got way ahead of myself and way too excited about localStorage on another little project! I did a tonne of research last night and realised that it's not a good thing to do (also read through the same article you've linked to, amongst probably 15+ others!).

If I'm honest - based on all the documentation and advice I can find from legitimate sources (there's a LOT of dodgy stuff out there - such as base64'ing webfonts and storing that in localStorage - madness!!!) it does sound like using the (Google advised) sessionStorage and leaving future/return sessions up to the standard browser cache to handle is the better option, to cater for changes Google's end! 

Therefore, as originally requested, I'll pull together a PR - I'm thinking of keeping it really simple: 
- Checkbox under "use webfont.js" for "use sessionStorage" that's only enabled when the webfont option is selected
- Checkbox.Checked = two ways of doing it:
1) Can have its own function to override the original webfont.js function
2) if statement within the webfont.js function: (incorrect syntax here, but just to explain what I'm thinking at a super high level!!!) 
```
function usethewebfontoption() {
WebFontConfig = { 
	google: { 
		families: [ 'fontfamily' ] 
	} 
       if (sessionStorageCheckbox.Checked = true) {
		, 
		active: function() { 
			sessionStorage.fonts = true; 
		} 
	}
}
}
```

**Comment by vijayaraghavanramanan** [comment]
Should add, sessionstorage should be used by first detecting if it exists. 

Safari in private mode doesn't allow sessionstorage. 

Feature detection test here, see `function storageAvailable(type)`:

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

**Comment by willstocks-tech** [comment]
Good call @vijayaraghavanramanan - fairly easy to do I believe:
```
function usethewebfontoption() {
WebFontConfig = { 
	google: { 
		families: [ 'fontfamily' ] 
	} 
       if (sessionStorageCheckbox.Checked = true && typeof(sessionStorage) !='undefined') {
		, 
		active: function() { 
			sessionStorage.fonts = true; 
		} 
	}
}
}    


```

**Comment by vijayaraghavanramanan** [comment]
Hi @willstocks-tech 

I think what happens in Safari private mode and maybe some others who don't allow this in incognito mode, is that `typeof(sessionStorage)` will indeed be defined but trying to use sessionStorage will still give errors. So I think the only way is like in the Mozilla link: setting a test storage, read it and removing it and use try-catch to figure if the operation has gone smoothly.

**Comment by willstocks-tech** [comment]
Good ol' Apple eh ;)
Yes, I was researching this after posting last and came across: https://stackoverflow.com/a/11214467/10597671 as well as the Mozilla link you sent over (very similar)

**Comment by futtta** [comment]
still on this @willstocks-tech ? :)

**Comment by willstocks-tech** [comment]
I was literally just typing up a response! 😱 Great minds, eh Frank!

**Comment by willstocks-tech** [comment]
I've been looking into this more... If I'm honest, I'm not really sure I see the benefit in implementing this, as 99.99999% of the time, after the initial load the font will be in the browser cache. Sticking it in `sessionStorage` as well isn't really going to provide much benefit?

I do like the idea of the service-worker caching mentioned [here](https://github.com/futtta/autoptimize/issues/207#issuecomment-435223847) and my first instinct would be to look into something along the lines of: https://github.com/Zertz/font-workers (worth a read: https://medium.com/@pierluc/supercharge-google-fonts-with-cloudflare-and-service-workers-25c37462fb6a)

**Comment by futtta** [comment]
>  I'm not really sure I see the benefit in implementing this, as 99.99999% of the time, after the initial load the font will be in the browser cache. Sticking it in sessionStorage as well isn't really going to provide much benefit?

-> agreed :sunglasses:

**Comment by willstocks-tech** [comment]
If I'm honest as well, caching the font via service-worker is just opening up to potential problems... for the sake of simplicity, it's probably best to just let the browser do what it does best! Implementing a network-first service worker just for the sake of caching a font (which the browser is already going to do) seems a bit overkill for most users?

**Comment by futtta** [comment]
let's close this issue then? there's bigger fish to fry after all ;-)

**Comment by willstocks-tech** [comment]
I reckon this one can be closed off as a "wontfix" for now? Maybe if you get more demand for it in the future/some new caching method comes into play for fonts?

The only think I can think _might_ be beneficial from the SW front is that you could fetch the gfont with `font-display: swap;` to alleviate FOUT... but again, opening up to complexity/issues there for those that don't fully understand it?

Gonna close this 😁
