### ISSUE TITLE
Query string `ver` is removed even when "Remove query strings" is not checked

### ISSUE THREAD

**Issue by diegoversiani** [futtta/autoptimize#208]
Hi,

Autoptimize is removing the `ver` query string from CSS file excluded from optimization even when "Remove query strings from static resources" is not checked. The option does not seem to take effect as it removes the query string whether it's checked or not.

It works as expected for JS files

Here is how I have the options set:

- Optimize CSS: **checked**
- Exclude CSS from Autoptimize: **theme.min.css**
- Remove query strings from static resources: **checked/unchecked**

Result:

- Query string `ver` is always removed when **Optimize CSS** is checked.
- If I disable Optimize CSS it works as expected: removing the query string only when option checked.
- If I deactivate Autoptimize the query string is there.

I can provide more information if needed and test any patches.

Thank you in advance,
Diego

**Comment by futtta** [comment]
you're right! :-)

this seems to happen in https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeStyles.php#L215-L218, can you try commenitng out those lines and do the same tests with and without the "remove query string" option?

@zytzagoo is this new our 2.4.x branch or has that been in for longer? shouldn't this be handled by the "remove query strings" logic anyhow?

**Comment by zytzagoo** [comment]
I think you introduced it here: https://github.com/futtta/autoptimize/commit/0163289002223629c63a6b3e479fb1a28ddd8af3#diff-96087a310ce2ff9d4c8f862e55a9bd62
And then modified slightly but still doing the same in https://github.com/futtta/autoptimize/commit/6ca290bf9df9218a1529268c3179185ed0e3ffd6

The inconsistency in css/js handling (if true, havent had time to check) is weird indeed.

**Comment by futtta** [comment]
indeed weird that JS would not have this, as [the code to remove the querystring is there as well](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeScripts.php#L182-L185) ... 

so @diegoversiani could you indeed test if:
* commenting out those lines in autoptimizeStyles.php fixes this?
* doublecheck if this doesn't also happen for JS?

**Comment by diegoversiani** [comment]
@futtta that's it, commented out these lines and worked as expected.
Will check for js now.

**Comment by diegoversiani** [comment]
Just looking at the code it seems the variable `$explUrl` is not defined on the js class `autoptimizeScripts` so the if statement will always be false.

I can't find `$exploded_url` on the js class as well.

**Comment by futtta** [comment]
Indeed it could not have worked for JS @diegoversiani :-)

So I removed the code in both, would be great if you could test the current master branch  to see if all indeed is fine that way?

**Comment by diegoversiani** [comment]
@futtta tested on master branch, all working as expected :)

**Comment by futtta** [comment]
Thanks for the help Diego, this will be in AO 2.4.2 later this month!
