### ISSUE TITLE
ESI tags is not correctly rendered

### ISSUE THREAD

**Issue by tdtgit** [futtta/autoptimize#211]
It's me again.

I don't remember Autoptimize not working with ESI tags because I'm using AO and implemented ESI long time ago and it's working fine. But today I notice AO trim my ESI tags to:

Original and expected result:
```
<esi:remove>Content goes here...</esi:remove>
<!--esi <esi:include src="/path/source.php">-->
```

It's become:
```
<remove>Content goes here...</remove>
<include src="/path/source.php"></include>
```

Too lazy to revert old version on my production, can you find something?

And here is quick fix in case anyone need:
```
add_filter('autoptimize_html_after_minify', function($content) {
	$content = str_replace('<remove>', '<esi:remove>', $content);
	$content = str_replace('</remove>', '</esi:remove>', $content);
	$content = str_replace('<include', '<!--esi <esi:include', $content);
	$content = str_replace('</include>', '-->', $content);
	return $content;
}, 10, 1);
```

**Comment by futtta** [comment]
just tested by adding your ESI-code in a HTML widget and -provided "keep comments" is on in HTML optimization- this renders as;
`
<esi:remove>Content goes here...</esi:remove> `

so I don't think this is an AO issue (as AO doesn't "know" ESI)?

**Comment by futtta** [comment]
Any news @tdtgit or can I close this?

**Comment by tdtgit** [comment]
Okay close this case until I retested it :)
