### ISSUE TITLE
Google Lighthouse: Defer unused CSS

### ISSUE THREAD

**Issue by willstocks-tech** [futtta/autoptimize#219]
Hi Frank!
Me again! So I ran a https://web.dev Lighthouse report (https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://willstocks.co.uk#unused-css-rules) and it's asking me to "defer unused CSS".
I'm using the "Inline and Defer" option in Autoptimize, with CriticalCSS add on, so I'm not sure why this "error" is showing?
Any thoughts?

**Comment by futtta** [comment]
I've gotten it regularly the last couple of weeks so I have this answer ready for copy/ pasting. This is my take on this: 

> When you’re using “inline & defer” (potentially with the automated critical CSS plugin) the critical CSS is inlined and the full CSS is technically not deferred but “preloaded” meaning it is loaded without it being render-blocking (which is a separate GPSI recommendation). AO uses Filamentgroup’s loadCSS for this purpose.
> 
> The advantage of using “preload” is that the page below the fold is styled as soon as possible without the CSS being render blocking. If it would be deferred (as AO used to do a couple of versions ago) the chance was bigger that the user scrolled down to a part of the page that was not styled yet. Given the fact that preloading the full CSS does not block rendering, there is little advantage to be found in deferring it instead and the disadvantage might be significant.

**Comment by willstocks-tech** [comment]
Ahhhhhhhh, OK that makes sense!
So it's "kind of like" rather than "lazyloading" the CSS as a user scrolls, you're preloading it so the whole page is styled, but the whole page CSS is loaded _late_?

**Comment by futtta** [comment]
almost;
* the critical CSS is loaded immediately inline and allows the visible part
of the page (without scrolling) to be styled
* the full CSS is preloaded (which is not render-blocking) and as soon as
it is preloaded it is applied to the entire page

**Comment by willstocks-tech** [comment]
Nice, OK that now all makes sense to me! Cheers Frank! :) In my mind, all I can see now is font swapping (inline = "system font", full = "webfont", preload and apply = something like fontfaceobserver) to prevent FOIT!

I'm having an interesting time playing with Lighthouse and HTTP/2 Push (using this: https://github.com/futtta/autoptimize/issues/49#issuecomment-305156931 snippet) and Lighthouse complains about some strange things while HTTP/2 Push doesn't seem to be playing ball (not seeing anything being "Pushed" to the browser). I think, however, I might _patiently_ await an "official" HTTP/2 Push option in Autoptimize ;)

**Comment by futtta** [comment]
the big Q. off course is if your webserver supports HTTP/2? :)

**Comment by willstocks-tech** [comment]
It does indeed :)
I'm running a DigitalOcean droplet via Cloudways, with HTTP/2 enabled!

**Comment by willstocks-tech** [comment]
![image](https://user-images.githubusercontent.com/43744514/49229118-c18aeb00-f3e4-11e8-8f36-468d03d9e012.png)

**Comment by futtta** [comment]
what webserver; nginx or apache and what version? because HTTP/2 support
does not automatically mean HTTP/2 push support?

**Comment by willstocks-tech** [comment]
Fixed it!!! Not sure what was interfering, but something clearly was!!!

**Comment by futtta** [comment]
Great job Will :-)

I'll close this issue as I like keeping a clean house, but don't hesitate to follow up here if needed.

**Comment by willstocks-tech** [comment]
Thanks Frank! 
Clear house = clear mind! Onwards with ignoring Google! ;)
