### ISSUE TITLE
Network settings

### ISSUE THREAD

**Issue by jgadbois** [futtta/autoptimize#22]
I would like to activate for a MU network and apply the settings to all network sites - is this something you could add?

**Comment by futtta** [comment]
Pretty easy to do in code actually. This was discussed [in this thread on the wordpress.org forum](https://wordpress.org/support/topic/any-way-to-active-and-configure-across-large-network?replies=7) and [this linked gist](https://gist.github.com/roytanck/e5e38d2955140b36da7e) might be helpful as well.

frank

**Comment by jgadbois** [comment]
Thanks that almost works, however optimize HTML, while checked, is not changing the source.  Is there an additional function I could call to generate the optimized HTML?

**Comment by jgadbois** [comment]
That works great, thanks
