### ISSUE TITLE
Disable Autoptimize completely on certain url/parameters?

### ISSUE THREAD

**Issue by justanotherco** [futtta/autoptimize#220]
Great plugin.

Is it possible to disable Autoptimize completely on certain urls/parameters?

For example:

http://mysite.com/?my_special_param=1

I need autoptimize to not load at all if my_special_param is active.

Thanks.

**Comment by futtta** [comment]
yes, use a code snippet like this one;

```php
add_filter('autoptimize_filter_noptimize','param_noptimize',10,0);
function param_noptimize() {
	if (strpos($_SERVER['REQUEST_URI'],'my_special_param')!==false) {
		return true;
	} else {
		return false;
	}
}
```

happy noptimizing ;-)
frank
