### ISSUE TITLE
Improve AMP support

### ISSUE THREAD

**Issue by westonruter** [futtta/autoptimize#222]
On a [support topic](https://wordpress.org/support/topic/amp-tag-issue/#post-11030835) for the AMP plugin, I found that the Autoptimize plugin is breaking the AMP validity of pages by moving the following required `style` element into an external stylesheet:

```html
<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style>
```

Can Autoptimize be updated to skip handling `style` elements that contain `amp-boilerplate`, `amp-custom`, or `amp-keyframes` attributes?

Also, the AMP plugin already does CSS inlining, minification, and even tree-shaking so perhaps all of the CSS handling could be disabled when `function_exists( 'is_amp_endpoint' ) && is_amp_endpoint()`?

**Comment by futtta** [comment]
Bizar, as [AO bails on a page if `<html amp` or `<html ⚡`](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeMain.php#L379-L384) is found, which is the indication the page is in fact AMP?

So .. 
* does the html have that attribute?
* are you sure this is AO's doing?

**Comment by westonruter** [comment]
Yes, the page in question does have the `amp` attribute: view-source: https://miguelrivasespana.es/hacerse-mediador-seguros/?amp

And I can see one of the AO stylesheets is including the amp-boilerplate styles: https://miguelrivasespana.es/wp-content/cache/autoptimize/css/autoptimize_5e2b569eacd096b6f7cad0fa561a0128.css

I think the issue is that the AMP plugin now has theme support, meaning you can take existing themes and serve them as AMP. Naturally they do not have the `amp` attribute to begin with, so the AMP plugin adds this attribute during its output buffering:

https://github.com/ampproject/amp-wp/blob/511a8b1d8f81f79ec6968a48637d22091e8ce700/includes/class-amp-theme-support.php#L1721-L1724

So the issue is likely that the AO output buffers are being handled _before_ AMP handles the output buffer, meaning that when AO is running it doesn't yet have access to whether it will be an AMP response by just looking at the `html` element.

**Comment by futtta** [comment]
ob_craziness could indeed explain, thanks for troubleshooting and for the PR @westonruter

**Comment by futtta** [comment]
question @westonruter ; is the AMP plugin now always using the output buffer, or only if that new feature (amp with theme) is used? and is that new feature default on or off?

**Comment by westonruter** [comment]
The classic mode doesn't use the output buffering. It is the new paired/native modes that use it, which is where the theme support comes in.

**Comment by futtta** [comment]
OK, and is that paired/native mode on or off by default?

**Comment by westonruter** [comment]
For now it is off by default, but eventually we plan to make the new paired mode the default instead of the classic mode.
