### ISSUE TITLE
Conflict with GTranslate plugin

### ISSUE THREAD

**Issue by ITpedia-NL** [futtta/autoptimize#228]
The optimize HTML option change ('nl|en') in (nl|en') [one single quote missing.]
 This results in a jump back to the homepage and not in de translation of the current page. Un-checking the HTML box solved the problem.

![knipsel5](https://user-images.githubusercontent.com/44037669/51798839-3d54b880-2219-11e9-80be-ad7dcd585bcd.JPG)
![knipsel4](https://user-images.githubusercontent.com/44037669/51798846-68d7a300-2219-11e9-92df-f7dcb1ab1f77.JPG)

**Comment by futtta** [comment]
that's [a (new) bug in W3TC](https://wordpress.org/support/topic/last-update-destroyed-html-minify-settings/) that is [impacting AO](https://wordpress.org/support/topic/issue-with-custom-share-buttons-with-floating-sidebar-csbwfs-plugin/#post-11133660). AO without W3TC (and it's buggy HTML minifier) will work just fine.
