### ISSUE TITLE
CSS/JS filters test report

### ISSUE THREAD

**Issue by denydias** [futtta/autoptimize#23]
@futtta,

CSS filters works great in any case I tested.

```php
add_filter('autoptimize_filter_css_removables','fgo_css_remove',10,0);
function fgo_css_remove() {
  return "font-awesome.css, ut-superfish, ssbp, wp-content/themes/brooklyn-child/css/custom.min.css";
}
```

In the other hand, no JS exclusions have worked as expected.

```php
add_filter('autoptimize_filter_js_removables','fgo_js_remove',10,0);
function fgo_js_remove() {
  return "jquery.js, jquery-migrate.js, emoji, superfish.min.js, ssbp_page";
}
```

The theme I use heavily depends on jQuery. I know the exclusion do not work because jQuery code is in the optimized JS created by AO after the filter is in place and because the site still works.

**Comment by futtta** [comment]
Just to make sure; the version of autoptimizeScripts.php you're using does include this last commit; https://github.com/futtta/autoptimize/commit/1f30447e80e833ff3116d70ec22a36226d07181f?

**Comment by futtta** [comment]
well, found bug anyway (impacting inline JS to be removed), [fixed here](https://github.com/futtta/autoptimize/commit/d3e2e24d8340569bd210717d8ac910205cd31877)

**Comment by denydias** [comment]
Oh! I was one commit behind. Sorry for the noise.

JS filtering works like a charm now. Tested with commit d3e2e24.

**Comment by futtta** [comment]
Muito obrigado Deny!

**Comment by denydias** [comment]
It works even with fuzzy matching, e.g. `blockUI` blocks `jquery.blockUI.js`. Nice!

This feature may receive some kind of warning as it may break things if the developer use a loose term.

Graag gedaan. ;)

**Comment by futtta** [comment]
> This feature may receive some kind of warning as it may break things if the developer use a loose term.

It can break things badly, indeed. Don't think I'll add it to the settings-page any time soon ;-)
