### ISSUE TITLE
Q: How to 'master reset' plugin options back to default?

### ISSUE THREAD

**Issue by samkatakouzinos** [futtta/autoptimize#232]
Is there a way within the plugin?
Or another method for developers for now?

**Comment by futtta** [comment]
Guess you could try triggering [the on_uninstall() function](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeMain.php#L460), this removes all options and should see them recreated with default values?

**Comment by samkatakouzinos** [comment]
I don't know how to do the trigger. 
Any pointer/advice so that I may learn?

**Comment by futtta** [comment]
from a code snippet try calling 
`autoptimizeMain::on_uninstall()`

or else simply deactivate/ uninstall and reactivate/ reinstall? :-)

**Comment by samkatakouzinos** [comment]
Used the 'Code Snippet' plugin. 
It worked, thanks!
