### ISSUE TITLE
update autoptimizeCache.php

### ISSUE THREAD

**Issue by vespino** [futtta/autoptimize#233]
"Propose file change" doesn't seem to work for me, so,,,

Please add file_exists() checks around file_put_contents() on line 99, 100 and 103, e.g. :

```
if ( file_exists( $this->cachedir . $this->filename ) ) {

}
```
Maybe on some more places, but I'll leave that up to you.

**Comment by futtta** [comment]
errr ... that won't work as an existing file is not supposed to be rewritten to start with. What is it you're trying to fix here and why do you think this would solve that problem?

**Comment by vespino** [comment]
I'm getting this error on a regular basis:

[20-Feb-2019 06:30:37 UTC] PHP Warning:  file_put_contents(/***/wp-content/cache/autoptimize/js/autoptimize_snippet_7121994eec5320fbe6586463bf9651c2.js): failed to open stream: No such file or directory in /***/wp-content/plugins/autoptimize/classes/autoptimizeCache.php on line 103

This for css and js files.

**Comment by futtta** [comment]
AO 2.5 (beta) [which you can download here](https://github.com/futtta/autoptimize/archive/beta.zip) has a fix for that, but you'll need to activate it with this code snippet;

`add_filter('autoptimize_filter_cache_checkdirs_on_write','__return_true');`

**Comment by vespino** [comment]
When will this version be released? I'm not a big fan of using beta software on live websites :)

**Comment by futtta** [comment]
When it's ready ;-)

But I'm targeting end March/ early April.
