### ISSUE TITLE
Minify HTML with Google ADSENSE code

### ISSUE THREAD

**Issue by fredroo** [futtta/autoptimize#234]
when minify HTML option is enabled shows code like:

<ins class=adsbygooglestyle=display:blockdata-ad-client=ca-pub-0000000000000000data-ad-slot=0000000000data-ad-format=link></ins>

only shows my Google Adsense when disabling minify HTML

**Comment by futtta** [comment]
I can't know for sure, but I'm pretty confident you're (also) using W3 Total Cache, which as of the recent releases has some [pretty serious issues with a.o. HTML minify which unfortunately bleed into AO](https://blog.futtta.be/2019/01/27/warning-bug-in-w3-total-cache-impacts-autoptimize/).

If you're not using W3TC I'll happily investigate off course, but at least I'd need the URL of your site to start with?

**Comment by fredroo** [comment]
@futtta thanks, you are right I am using W3 Total Cache, when disabled this plugin works fine or when disabled minify HTML in Autoptimize, I am going to waiting for new version of W3 Total Cache, thanks again
