### ISSUE TITLE
[Feature Request] Static brotli compression

### ISSUE THREAD

**Issue by willstocks-tech** [futtta/autoptimize#235]
Hey Frank,
Hope you're well?
I don't know how easy this one is to implement, and I appreciate it's probably an "edge case" right now - and I'm not sure how much work is involved - but in a similar manner to the `autoptimize_filter_cache_create_static_gzip`, would it be possible to get a `autoptimize_filter_cache_create_static_brotli` for those with Brotli enabled on their server? This could be hidden behind a feature detecting tickbox (in a similar manner to what W3TC implemented recently) and would be great to avoid having to do Brotli compression on-the-fly! 😄

**Comment by willstocks-tech** [comment]
It's highly possible I've missed something - but basically, I just replicated the existing gzip filter, catering for brotli instead! I've opened a PR: #237 😁

**Comment by willstocks-tech** [comment]
Note here for reference as well - Per PR conversation, rather than creating a new filter to maintain, this has instead been "merged" into the existing `autoptimize_filter_cache_create_static_gzip` filter. We run a super simple check to find out whether the PHP Brotli Extension exists, and if it does then create a level 11 brotli version of the file!

**Comment by futtta** [comment]
merged, thanks @willstocks-tech ! :-)
