### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by fredroo** [futtta/autoptimize#238]
How I can load custom CSS right way to fix this:

Eliminate render-blocking resource

https://developers.google.com/speed/pagespeed/insights/?hl=us&url=https%3A%2F%2Fcriativoaz.com%2F

https://criativoaz.com/?custom-css

**Comment by futtta** [comment]
hey @fredroo ; github issues are for technical problems (bugs, improvements) with the plugin, end user support is provided at https://wordpress.org/support/plugin/autoptimize/

but as we're here now anyway; add your custom CSS in Appearance -> Customizer -> Additioinal CSS instead and all will be fine.
