### ISSUE TITLE
[Question] Why keep px in minified CSS

### ISSUE THREAD

**Issue by willstocks-tech** [futtta/autoptimize#239]
Hey Frank,
This is a sheer curiosity question - why does AO keep the px characters in the minified CSS files? It is my understanding that if a browser finds a numeric value in CSS with no unit, it interprets it as standard as px. 
I know it’s not huge savings, it’s 2B per px - just wondered if there’s a reason to/not to remove?

**Comment by willstocks-tech** [comment]
Just read up more on this - seems it _could_ be excluded for some use cases, but not all!

**Comment by futtta** [comment]
AO uses https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port for CSS minification, guess Tubal would have a good idea about that, but I don't really ... :joy:

**Comment by willstocks-tech** [comment]
Thanks Frank - I’ll close this off. I spent (far too much of!!) last night researching and I think it’s just a coding standards thing. It’s widely accepted that browsers use roc as fallback if no units are declared, but even when minified there’s some degree of readability required? That, or minification can result in potentially throwing off values? 
No idea - lol, way outside my current understanding! 😂
