### ISSUE TITLE
Combined CSS autoptimize_......css Duplicated

### ISSUE THREAD

**Issue by idevwebs** [futtta/autoptimize#243]
I've installed and configured the plugin, and when loading the page I find that the same

/wp-content/cache/autoptimize/css/autoptimize_xxxxxxxxxxxxxxxxxxxxxxxxxxx.css

Is loading in head and right before end of body. Same hash, file size. Why is this happening?

**Comment by futtta** [comment]
can't say without a link to your site @idevwebs :)

**Comment by idevwebs** [comment]
Unfortunately, site is behind a firewall which does not allow http/s from outside ip range. Any ideas though? This duplicate is there. Shows up in network of firefox tools as well as in page source.

**Comment by futtta** [comment]
No idea I'm afraid, never seen that happen before.

**Comment by futtta** [comment]
closing due to lack of a URL to see what's going on ..
