### ISSUE TITLE
AO WP Mobile app logo (iOS)

### ISSUE THREAD

**Issue by willstocks** [futtta/autoptimize#248]
The most significant feature/issue of all time Frank 😉😂

For some reason, AO’s logo doesn’t show on the WordPress mobile app.

![20FBAF3B-9FF2-4C98-8006-050136E55EFD](https://user-images.githubusercontent.com/43744514/56563594-f5d59280-65a3-11e9-8c1d-71add95ab2ba.jpeg)

Obviously this is by no means major, or impacts anything at all! But I thought I’d mention it as it’s one of three (including AOCCSS) plugins in my list that doesn’t have a logo

**Comment by futtta** [comment]
ah, must be an issue with image sizes or something I guess. I'll look into
it after the 2.5 stress ;-)

**Comment by futtta** [comment]
Hey Will, to pre-empt the 2.6 stress; [I just added an (ugly) HDI version of the icon](https://plugins.trac.wordpress.org/browser/autoptimize/assets/icon-256X256.png?rev=2211608), can you check if it now shows for you? :-)
