### ISSUE TITLE
API get CSS and JS Hash reference

### ISSUE THREAD

**Issue by yumyo** [futtta/autoptimize#249]
Hi, thank you for your great work with Autoptimize. 
I am wondering, how to get the JS and CSS hash reference with the API? 
Also, is there any plan to support WP-Json API?

**Comment by futtta** [comment]
you can use the `autoptimize_filter_cache_getname` filter (which not only returns the hash but the full URL where a specific optimized JS/ CSS-file can be found, so you would have to parse that a bit), see https://github.com/futtta/autoptimize/issues/49#issuecomment-305156931 for an example :)

no plans for wp-json no.

**Comment by yumyo** [comment]
That would work perfectly. Thank you!
