### ISSUE TITLE
Exclude images from lazyload not working for essentials grid.

### ISSUE THREAD

**Issue by Chris2011** [futtta/autoptimize#252]
When I want to exclude images, that are parts of the essentials grid, which is implemented in my page, it will not work. I added a lot of classes from wrapper elements from the essentials grid to exclude but nothing works. Unfortunately, the images inside of the wrapper, don't have classes to exlucde. I guess that only classes on img tags are working, right?

I need to add classes from wrapper elements like .esg-wrapper-smth to exlude those elements. To get the image names is not possible, because they are normal images, uploaded from the mediathek and don't have special name pattern.

My environment: WordPress 5.1.1 and Autoptimize 2.5.0

**Comment by futtta** [comment]
can you share the URL where you have essential grid active Chris?

**Comment by Chris2011** [comment]
Atm not really, I will make a test environment for that and will come back to you.

**Comment by Chris2011** [comment]
@futtta here it is: https://grid.54p.de/sample-page/ the grey block are 10 images in a grid. As you can see, it will not loadede, because lazy loading (in general) is not working with essentials grid. I tested a lot of other plugins but this is not the problem.

I added those classes for example: .tp-esg-item, .esg-entry-media but it doesn't work.

**Comment by futtta** [comment]
OK so excluding based on the class/ id of a div higher up in the DOM indeed is not possible (I would require AO to have deeper understanding the DOM, which I prefer not to because of perf.) so the normal exclusions won't work

I have however made a change in the lazyload logic and specifically in the should_lazyload filter that allows you to disable lazyload (for an entire page) based on the context (the HTML of that page) with a code snippet like this one;

```php
add_filter('autoptimize_filter_imgopt_should_lazyload','should_lazyload_context',10,2);
function should_lazyload_context($flag, $context) {
  if ( strpos( $context ,'esg-grid') !== false ) {
	return false;
  } else {
	return $flag;
  }
}```

Maybe not as easy as the normal lazyload exclusions, but at least now you can use AO lazyload without breaking your essential grid ;-)

**Comment by Chris2011** [comment]
Ahh ok cool, so I can use it on that page, but exclude the HTML that I don't want to lazyload but the rest, which is not an esg-grid, is working, right?

**Comment by futtta** [comment]
Afraid not; the code snippet stops all image on the page being lazy-loaded
if "esg-grid" is found anywhere in the HTML.

**Comment by Chris2011** [comment]
Hm ok, that's a workaround but pity, because I want to use this on the same page except for that grid.

Is it really a perf problem to say: "hey, you want to exclude this class ".esg-grid" so all images inside of this DOM element, will excluded"?

**Comment by futtta** [comment]
Yes, AO currently does not do full DOM parsing and adding that (with PHP's
domdocument & acting on that instead of on single tags in an HTML string)
would certainly slow things down.

**Comment by Chris2011** [comment]
Ok thx.
