### ISSUE TITLE
font-display

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [futtta/autoptimize#253]
Hi Frank/other contributors,

Google Fonts has already implemented font-display: https://github.com/google/fonts/issues/358 and is live. 

Would be relevant for AO.

**Comment by futtta** [comment]
well, if anyone wants to have a stab at this; go! :-)

**Comment by futtta** [comment]
No font-display option (yet), but surely [a filter is a first step](https://github.com/futtta/autoptimize/commit/0e2a5eed9a9d7451cac16c646f8617014dd74259) ? ;-)

**Comment by vijayaraghavanramanan** [comment]
Yeah that's good for a start. 

I am thinking maybe you can have the option to use webfont-loader as a polyfill and not expose it to new browsers, so that users who don't know these things don't choose webfontloader as the main option. font-display support is high 82.29% according to caniuse

And preload the css. So the html output might look like: 

```html
<script>
	var linkSupportsPreload = (function() {
		try {
			return document.createElement("link").relList.supports("preload");
		} catch (e) {
			return false;
		}
	})();

	var fontDisplaySupported = window.FontFace && window.FontFace.prototype.hasOwnProperty("display");

	function preloadFinished( el ) {
		var res = document.createElement("link");
		res.rel = "stylesheet";
		res.href = el.href;
		res.crossOrigin = el.crossOrigin;
		el.parentNode.insertBefore(res, el.nextSibling);
	}
</script>

<link rel="preload" href="https://fonts.googleapis.com/css?family=Open+Sans&font-display=swap" as="style" onload="fontDisplaySupported&&preloadFinished(this)" crossorigin>

<script>
	if (!fontDisplaySupported || !linkSupportsPreload) {
		document.write('<link href="https://fonts.googleapis.com/css?family=Open+Sans&font-display=swap" rel="stylesheet" crossorgin="anonymous">');
	}
</script>
```

Simplified a bit with document.write but could use webfontloader as the fallback. 

Congrats on 1m+ active installs!

**Comment by futtta** [comment]
added `display=swap` to AO's CSS-based (aggregate & link + aggregate & preload) Google Font optimizations in 2.6.0-beta-1 @vijayaraghavanramanan 

have time, no need to worry about not being able to test immediately ;-)
