### ISSUE TITLE
Clearing W3TC page cache results in AO's cache being emptied

### ISSUE THREAD

**Issue by willstocks-tech** [futtta/autoptimize#255]
Hey Frank,

I didn't notice this happening prior to 2.4.1 (I'm 99% sure anyways), but as of this morning, if I clear W3TC's page cache - AO's cache also gets cleared!

I wouldn't expect this behaviour normally. I'd expect AO's cache to build up regardless of W3TC's page cache state.

**Comment by futtta** [comment]
Hey Will; 
It indeed does, got introduced in 2.4.0 actually, you can disable that with this code snippet;
```php
add_filter('autoptimize_filter_main_hookpagecachepurge','__return_false');
```

Reason is simple; cache size issues are (were) the biggest issue when doing support, clearing AO's cache when the page cache is cleared is the safest moment to keep AO's cache under control for those who are not able to correctly configure AO ;-)

**Comment by willstocks-tech** [comment]
Thanks Frank - just added that to my `functions.php` and my AO cache still cleared when clearing W3TC's page cache 😞

Using this option if it makes a difference:
![image](https://user-images.githubusercontent.com/43744514/58103865-a488e500-7bdb-11e9-9b8a-eee085afe480.png)

Only reason I'd personally prefer this disabled is:
1) I notice some weird behaviour when I clear AO and my page cache at the same time. It might be because I'm using CCSS, but on initial page load, I see flashes of weird styling. Everything then gets into the correct order once AO's cache has been built and I clear the page cache at that point... might just be something weird going on though!
2) My AO cache doesn't infinitely grow... I have that thing on lockdown! 🤣

**Comment by futtta** [comment]
In that case I suspect W3TC cache is calling AO's clearall or simply
removing wp-content/cache from the filesystem.
