### ISSUE TITLE
autoptimize_filter_js_replacetag issue

### ISSUE THREAD

**Issue by bobhuf** [futtta/autoptimize#257]
Hi,

I'm trying to output minimised JS in the footer of my page but before external assets I'm including using templating inheritance.

My template:

```twig
<footer>...</footer>
{{ function('wp_footer') }}
{% block footer_after %}
{% endblock %}
```

I'm using to _autoptimize_filter_js_replacetag_ to add the JS directly after the closing footer tag with this:
```php
add_filter('autoptimize_filter_js_replacetag','my_ao_override_js_replacetag',10,1);
function my_ao_override_js_replacetag($replacetag) {
    return array("<footer>","after");
}
```

But this throws an error: "Autoptimize found a problem with the HTML in your Theme, tag `footer` missing". There is a footer present though, 100%. Am I using the correct value? I tried some variations (<footer /> e.g.) but none worked.

The only ao setting I have activated is "Aggregate JS-files".

Thanks.

**Comment by futtta** [comment]
Middag Bob; If `<footer>` is in your output HTML but AO doesn't see it, then you might have some output buffering breaking things?

(small remark; I'm not sure if you want to add after <footer> or after `</footer>`, your code says the former but your explanation says the latter)

**Comment by bobhuf** [comment]
Hoi Frank,

Thanks for replying so quickly.

That small remark made everything click. I assumed the array value worked more like a jQuery selector.  Changing the value to </footer> fixed everything.

Thanks again!

**Comment by futtta** [comment]
Graag gedaan! :)
