### ISSUE TITLE
Aggregate JS and CSS throwing CPU off the roof

### ISSUE THREAD

**Issue by joseairosa** [futtta/autoptimize#259]
Hello,

I've installed today the plugin on my online shop https://animegami.co.uk. Upon installation the whole website became unresponsive. Looking at the logs and usage graphs I can see that the bottleneck is with php-fpm (7.2).

<img width="975" alt="image" src="https://user-images.githubusercontent.com/288866/60219449-52864f80-986a-11e9-8c51-40f8ba9d5098.png">

The two spikes you see there were from when I enabled the plugin.

After a good amount of investigation, I was able to narrow it down to the Aggregate JS and CSS option. As soon as I turn this on, the servers just go bananas. Now, I'm fairly sure there's nothing directly wrong with the plugin but there's definitely something at play here.

Couple notes:
- eCommerce website, woocommerce
- Over 20 concurrent users continuously throughout the day (roughly 2500 unique users/day)
- I have criticalcss addon as well

Question?
1. Could this be related with purging?

Any help really appreciated.

**Comment by futtta** [comment]
Do you have "aggregate inline JS" and/ or "aggregate inline CSS" on José?

**Comment by joseairosa** [comment]
Hi @futtta, I have both on.

**Comment by futtta** [comment]
OK, what is probably happening is that due to "inline" being on, you have a
lot of "cache misses" (due to differences in inline code) which means the
CSS and/or JS has to be re-minified (which will make the cache grow quick,
which explains your question about purges). disable "also aggregate inline
JS" (and CSS) and see if that makes any difference?

**Comment by joseairosa** [comment]
That's a good point. I will try it out.

**Comment by joseairosa** [comment]
@futtta much less pronunced, but still incremental CPU usage to the point that it just uses all available php-fpm processes. I can see them timing out.

Any thoughts?

Just one other piece of information:
1. I just a scalable infrastructure with vairous instances behind a LB.
2. All instances share the same AWS EFS. There could be higher IO, but I've been using wp-rocket with no problem.

**Comment by futtta** [comment]
-> can you try with just CSS or just JS optimization to see if there are
significant differences?

-> were you also doing CSS/ JS aggregation & minification in WP Rocket?

-> do you have access to profiling tools or new relic or something like
that that could help pinpointing where things are slowing down?

**Comment by joseairosa** [comment]
`-> were you also doing CSS/ JS aggregation & minification in WP Rocket?`
Nope, nothing.

`-> can you try with just CSS or just JS optimization to see if there are significant differences?`
Will try it out. Need to wait when traffic is sllightly lower, otherwise it just completely breaks the website.

`-> do you have access to profiling tools or new relic or something like that that could help pinpointing where things are slowing down?`
I do, yes. The graph I shared above is from newrelic. I looked into the hooks and plugins and it's defintely related with js and css in the plugin.

**Comment by futtta** [comment]
OK, re. new relic; can you differentiate between autoptimizeStyles.php and autoptimizeScripts.php and/or between the CSS & JS minifier

**Comment by joseairosa** [comment]
After initial test looks like it's related with JS side. I've been running with just CSS for 24h and no issues at all. As soon as I turned on JS optimisation (only first option and aggregation, nothing else) CPU started to go up and up. I'm monitoring on new relic... will report back soon.

**Comment by joseairosa** [comment]
A couple notes:

Looks like initial huge load could be related with turning on CSS and JS at the same time, with no cache?
Still overall feel the website slower. Waiting for a bit more data from new relic

**Comment by futtta** [comment]
re. feels slower; compare rendering speed using a tool such as
webpagetest.org for example (choose a pop close to your audience and go for
4G or 3G+ bandwidth doing at least 5 (or more) tests so you can compare
median and average times)?

**Comment by futtta** [comment]
hey @joseairosa how are things running now?

**Comment by futtta** [comment]
closing due to lack of further info, feel free to reply if you have more info José.
