### ISSUE TITLE
CSS inlined in embed pages

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [futtta/autoptimize#260]
Wordpress has embed pages with their permalinks such as:

https://www.example.com/2019/07/02/hello-world/embed

This is an HTML page and has its own style, typically by Wordpress and not themes. 

https://github.com/WordPress/WordPress/blob/1d98a92fad2992200dad9352eee456eaddc454be/wp-includes/embed.php#L1021

But if a user chooses inline and defer optimisation in Autoptimize, the critical css is inlined in the embed page too, although it doesn't seem to affect the styles. 

But may be it's best to not add the critical css in embed pages?

**Comment by futtta** [comment]
Hmmm. ... wondering if that should be done at Autotimize level maybe? What
do you think?

**Comment by vijayaraghavanramanan** [comment]
I guess so, since it's a core Wordpress feature?

**Comment by futtta** [comment]
basic question is; do such embeds need to be autoptimized?

**Comment by vijayaraghavanramanan** [comment]
Oh, that way! Yes, maybe just do nothing/return if the url is an embed.

**Comment by futtta** [comment]
OK, I'll add it to my AO backlog :)

**Comment by futtta** [comment]
should be fixed in 2.6.0-beta-1 @vijayaraghavanramanan

**Comment by vijayaraghavanramanan** [comment]
Hi Frank,

Will test. Stuck without a computer for a few days :(

**Comment by vijayaraghavanramanan** [comment]
Very late reply! Tested. Works.

**Comment by futtta** [comment]
very late "close and comment" ;-)

thanks @vijayaraghavanramanan
