### ISSUE TITLE
Add support for jQuery Manager

### ISSUE THREAD

**Issue by Remzi1993** [futtta/autoptimize#261]
Hi @futtta 

I would like to work together with you guys, I maintain an open source project / plugin jQuery Manager and I would like to work together to provide default support with your optimize plugin.

By installing jQuery Manager and activate it, by default jQuery 3.x.x and jQuery Migrate 3.x.x is activated and this will be updated when users updates the plugin.

All jQuery and jQuery Migrate versions are located at the plugin assets directory:
WordPress installation -> wp-content/plugins/jquery-manager/assets/js

Is there a way to add support for excluding jQuery, by looking for my plugin and this specific directory? Because I’m planning to keep up with the jQuery releases and you guys have a popular plugin. I’m even inclined / offer to help as a junior PHP / WordPress Developer.

See project: https://wordpress.org/plugins/jquery-manager/ and https://github.com/Remzi1993/jquery-manager

Forum: https://wordpress.org/support/topic/add-support-for-jquery-manager/

Let me know if we could help each other.

Kind regards,
Remzi

**Comment by futtta** [comment]
Morgend Remzi;
You could use the `autoptimize_filter_js_exclude` or `autoptimize_filter_js_dontmove` filters to tell AO to exclude those? [more info in the code](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeScripts.php#L90-L116) :-)

Zonnige groeten uit Italië (laatste dagen vakantie),
frank

**Comment by Remzi1993** [comment]
Hoi Frank

Kan je mij helpen hoe ik de API moet gebruiken en kan checken of een gebruiker Autoptimize gebruikt?
Je zou een pull request kunnen doen :)

Een hele fijne vakantie gewenst!

Groet,
Remzi

**Comment by futtta** [comment]
Zo veel te doen zo weinig tijd Remzi. Maar hier een stukje voorbeelcode;

add_filter('autoptimize_filter_js_dontmove','remzi_noptimize');
function remzi_noptimize($dontmove_array) {
    $dontmove_array[]='/jquery-manager/assets/js';
    return $dontmoveIn;
}

Checken of AO actief is, is niet echt nodig; de filter doet dat voor jou,
want is zonder Autoptimize gewoon niet uitgevoerde code :)

Succes!
frank

**Comment by Remzi1993** [comment]
@futtta Bedankt.

**Comment by Remzi1993** [comment]
@futtta Kan ik ook een hele directory excluden?

**Comment by futtta** [comment]
graag gedaan, hou me gerust op de hoogte! :)

**Comment by futtta** [comment]
hele directory; de voorbeeldcode doet dat?

**Comment by Remzi1993** [comment]
@futtta Ik zal het nu testen.

**Comment by Remzi1993** [comment]
@futtta Je voorbeeldcode werkt niet :(

**Comment by futtta** [comment]
wel, wat werkt er niet? krijg je een foutmelding? of wordt de JS gewoon
niet uitgesloten? ...

**Comment by Remzi1993** [comment]
De js wordt niet uitgesloten en ik zou het ook willen excluden met minifien.

Dit is mijn code:

	class wp_jquery_manager_plugin {

	    public function __construct() {
                 add_filter('autoptimize_filter_js_dontmove','autoptimize_support');
	    }
        
            public function autoptimize_support($dontmove_array) {
                 $dontmove_array[]='/jquery-manager/assets/js';
                 return $dontmoveIn;
            }
         }

**Comment by Remzi1993** [comment]
@futtta 

Wat is het verschil met autoptimize_filter_js_dontmove en autoptimize_filter_js_exclude
Ik wil dat het niet geminified en verplaatst wordt en dan voor beide een hele directory: /jquery-manager/assets/js

**Comment by futtta** [comment]
als de files al minified zijn (i.e. eindigend op ".min.js" or "-min.js"
zullen ze sowieso niet geminified worden.

ivm je code; probeer mijn code eerst even standalone in bv. de code
snippets plugin, eenmaal het daar werkt kun je het in je OO-code proberen
integreren?

**Comment by Remzi1993** [comment]
@futtta Ik heb hiervoor jou code overgenomen en die schijnt ook niet te werken, zou je even op: https://github.com/Remzi1993/jquery-manager/tree/Autoptimize-support willen kijken? (Autoptimize-support branch)

Ik zou je push access kunnen geven?

**Comment by Remzi1993** [comment]
@futtta See: https://github.com/Remzi1993/jquery-manager/invitations

**Comment by futtta** [comment]
kom zelf amper toe aan coderen voor AO en mijn andere plugins, dus dat zal
niet lukken, maar ik probeer in de loop van volgende week de filter zelf
even uit en zal indien nodig een correcte versie posten :)

**Comment by Remzi1993** [comment]
@futtta Oké, bedankt voor je snelle reactie. Hopelijk heb je deze week tijd, in de tussentijd zal ik gebruikers op het forum helpen met excluden.
