### ISSUE TITLE
Deleted Autoptimize code keeps showing up

### ISSUE THREAD

**Issue by BoostIndigo** [futtta/autoptimize#262]
I installed autoptimize and was using it along with W3 total cache and was getting in the waterfall report on GTmetrix. I disabled the plugin. deleted cache and deleted the plugin. My site works fine for a while and then somehow the code shows back up with the same issues. When it does the site doesn't render properly. I cleared cache on WP fastest cache, but the code still shows in GTmetrix. I need to keep this code from returning, but can't figure out where it is being generated.

**Comment by futtta** [comment]
If you deleted the plugin, it is not generated anywhere, but must somehow
be served from a cache somewhere somehow, but can't tell you where as I
(obviously) don't know your setup.

**Comment by BoostIndigo** [comment]
I understand. What do you need to know? Url is https://indigoboost.com/  This is the code when the error shows in line 5 & 6:

rel=pingback href=https://indigoboost.com/xmlrpc.php> <script>var et_site_url='https://indigoboost.com';var et_post_id='45';function et_core_page_resource_fallback(a,b){"undefined"===typeof b&&(b=a.sheet.cssRules&&0===a.sheet.cssRules.length);b&&(a.onerror=null,a.onload=null,a.href?a.href=et_site_url+"/?et_core_page_resource="+a.id+et_post_id:a.src&&(a.src=et_site_url+"/?et_core_page_resource="+a.id+et_post_id))}</script><link
--
  | type=text/css media=all href=https://indigoboost.com/wp-content/cache/autoptimize/css/autoptimize_d76ab586031261596964b9fe9438951c.css rel=stylesheet><title>Digital Marketing Agency Pittsburgh PA \| Indigo Boost LLC</title><meta

With no error:

<meta http-equiv="X-UA-Compatible" content="IE=edge">
--
  | <link rel="pingback" href="https://indigoboost.com/xmlrpc.php" />

**Comment by futtta** [comment]
indeed see mention of AO when going to https://indigoboost.com/

but not when adding some random querystring, e.g.
https://indigoboost.com/?sqdfqs=qsd

which confirms there's some HTML caching going on. temporarily disable any
page cache you might have (you mentioned W3TC & WPFC) and if the problem
persists ask your hoster (I see nginx mentioned in the HTTP reponse
headers, maybe that is caching).

**Comment by BoostIndigo** [comment]
Thank you

 

Jim Norton

Digital Marketing Consultant

724.321.3900
