### ISSUE TITLE
Autoptimize itself is slow?

### ISSUE THREAD

**Issue by bstrokevin** [futtta/autoptimize#264]
Look at slow response time of the server. Reviewing new relic details...
Seems like it's adding 1 sec+ just processing the code
<img width="950" alt="Screen Shot 2019-07-24 at 11 40 46 AM" src="https://user-images.githubusercontent.com/13989077/61819685-62ad3280-ae08-11e9-8d0e-1977d2b7db6d.png">
<img width="933" alt="Screen Shot 2019-07-24 at 11 38 36 AM" src="https://user-images.githubusercontent.com/13989077/61819686-62ad3280-ae08-11e9-87b1-92dd0ceb8667.png">

**Comment by futtta** [comment]
all depends on (autoptimize) config, so what is yours? :-)

**Comment by bstrokevin** [comment]
No CDN. cos the server has global cdn. 

<img width="770" alt="Screen Shot 2019-07-24 at 11 55 20 AM" src="https://user-images.githubusercontent.com/13989077/61820492-f29fac00-ae09-11e9-8c68-7151d04bba79.png">
<img width="768" alt="Screen Shot 2019-07-24 at 11 55 10 AM" src="https://user-images.githubusercontent.com/13989077/61820493-f29fac00-ae09-11e9-9192-3c2d6527f090.png">

**Comment by bstrokevin** [comment]
also no image optimization and critical css is off for now

**Comment by futtta** [comment]
weird, given you don't have "aggregate inline JS/CSS" on that cannot be the
cause of longer TTFB (due to cache misses). can you disable just JS and
then just CSS opt. to see which one is causing this?

**Comment by futtta** [comment]
for completeness sake; AO will add some time to the TTFB (if no page cache
is present), but this _should_ be limited to 50ms or so (assuming no AO
cache misses).

**Comment by bstrokevin** [comment]
ok. I’ll run it on the test site and collect some data.

**Comment by futtta** [comment]
Just had a good look at the 1st image you uploaded; the fact that the `autoptimizeCache::check()` and `autoptimizeCache::retrieve()` functions are (incredibly) slow indicates I/O issues (read), as [those functions are very pretty straightforward wrappers around file_exists and file_get_contents](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeCache.php#L56-L81).

**Comment by futtta** [comment]
any news on this @bstrokevin ?

**Comment by bstrokevin** [comment]
Hi. 
I sent the info to hosting “Pantheon” and they are looking into it. It’s been a week but no update yet! :( 
Will keep you posted. Thanks.

**Comment by futtta** [comment]
any news @bstrokevin ? if no I propose to close this one and put it down to bad luck (or slow disk i/o) ;-)
