### ISSUE TITLE
plugin causing admin login issue

### ISSUE THREAD

**Issue by tddrake** [futtta/autoptimize#265]
Autoptimize plugin is causing problems with my Wordpress site on the WP admin login page.  Error: too many failed attempts to login - try again in 8 billion hours.  At least it feels like I have to wait this long.  The wait time is often 24 hours or more.  What is going on with this plugin causing the multiple failed attempts to login???

**Comment by futtta** [comment]
Why do you think it's due to Autoptimize tddrake? Because AO isn't active
on wp-admin/ or wp-login.php, so it is highly unlikely (never say never)
this has anything to do with AO.

**Comment by tddrake** [comment]
Good point.  However, there is definitely a conflicting issue with Autoptimize and WP or possibly another plugin because when I deactivate AO, the login page does not display the error message anymore.

 

Possibly AO and another plugin like Beaver Builder or Ninja Forms or some other plugin is conflicting?

 

Should I consider removing AO completely and downloading/reinstalling?

**Comment by futtta** [comment]
beaver builder & ninja forms should also not interfere with the login page
really .. you can always try to re-install, who knows what magic might
happen.

if not; create me a non-admin user with email address
futtta-at-gmail-dot-com and I'll have a look at what is (not) happening.

**Comment by tddrake** [comment]
Update:  After deactivating and reactivating the AO plugin, the failed login error message is no longer appearing.  Here’s hoping I don’t see this message anytime soon.

**Comment by futtta** [comment]
:+1:
