### ISSUE TITLE
[Question] HTML5 Picture element

### ISSUE THREAD

**Issue by willstocks-tech** [futtta/autoptimize#266]
Hey Frank!

A question for you... with the work you're doing on image optimization at the moment, I don't suppose you have any plans for including a function for swapping `<img>` tags out into properly structured `<picture>` elements with capability of declaring both the `.jpg` and `.webp` `<source>`'s?

**Comment by futtta** [comment]
not planned no:
* there's not tangible advantage (AO does webp differently)
* changing <img into <picture can sometimes break things (the "legacy"
shortpixel plugin does this)

**Comment by willstocks-tech** [comment]
Thanks Frank - I did assume as much!

I know there's the (always open) trac ticket to implement support for this element structure ([see](https://core.trac.wordpress.org/ticket/42920)) and I know there are a couple of plugins that cater for  this partially, although CDN support appears to be minimal for these implementations (such as using S3/Cloudfront) and my skillset is not advanced enough to self-implement 😞 

No worries though - thanks Frank! Looking forward to 2.6.0 and on 😁
