### ISSUE TITLE
Aggregate JS option stops Google Analytics from working 

### ISSUE THREAD

**Issue by edkeohane** [futtta/autoptimize#271]
When the Aggregate JS option is checked in the Wordpress settings then GA (via GTM) does not load.

The following file exclusions are saved in the settings.

wp-includes/js/dist/, wp-includes/js/tinymce/, js/jquery/jquery.js, analytics.min.js, js/ganalytics.js, googletagmanager, googleanalyticsobject, gtag.js

**Comment by futtta** [comment]
So do you get JS errors on the browser console @edkeohane ?

**Comment by edkeohane** [comment]
I don't see any errors in the console, but when you look in network when aggregate is checked, the GTM js is missing the id and the analytics.js is not listed. see below.

**Aggregate on**
8f254d98a2.js	200	script	(index)	(memory cache)	0 ms	
analytics.min.js?ver=1.21.9	200	script	(index)	(memory cache)	0 ms
autoptimize_98ec85253870d3a8c1f2c02384e22c1f.js	200	script	(index)	(memory cache)	0 ms	
lazysizes.min.js	200	script	(index)	(disk cache)	2 ms	
js?id=undefined	200	script	analytics.min.js?ver=1.21.9:2	(disk cache)	4 ms		

**Aggregate off**
autoptimize_single_26894ce388a25670f6002c165001f4bc.js?ver=1.21.9	200	script	(index)	(memory cache)	0 ms
8f254d98a2.js	200	script	(index)	(memory cache)	0 ms	
lazysizes.min.js	200	script	(index)	(memory cache)	0 ms
analytics.min.js?ver=1.21.9	200	script	(index)	(memory cache)	0 ms
lazyload.min.js	200	script	(index)	(memory cache)	0 ms
js?id=GTM-PL58H62	200	script analytics.min.js?ver=1.21.9:2	(memory cache)	0 ms	
analytics.js	200	script	js?id=GTM-PL58H62:132	(memory cache)	0 ms

**Comment by futtta** [comment]
do you have "aggregate inline JS" on and if so can you test with that option off?

**Comment by edkeohane** [comment]
aggregate inline JS is already off. and so 'minify excluded' is off in misc as well.

**Comment by futtta** [comment]
OK, afraid now is the time when I have to ask you for your site's URL :)

**Comment by edkeohane** [comment]
thanks. please can you email me and I'll reply back. thanks. ed@hooha.io

**Comment by futtta** [comment]
closing as fixed by excluding a specific theme JS file (which had the GTM-code in it) from optimization.
