### ISSUE TITLE
Conflicting settings for excluding files from minification

### ISSUE THREAD

**Issue by ChrisHardie** [futtta/autoptimize#272]
Hi! In #215 you had me use the `autoptimize_filter_js_minify_excluded` filter to make sure excluded files were not minified, but it looks like https://github.com/futtta/autoptimize/commit/89a848b24b7e8063b6e07f3344d54e63317de89e introduced an admin-facing checkbox and property `minify_excluded` that overrides that filter in https://github.com/futtta/autoptimize/blob/5a8817f9c07d523e7df08179597f9090af85a14e/classes/autoptimizeScripts.php#L184. I think it means the blog posts that were crashing browsers before my filter was added have been doing that again for the last 5 months - d'oh.

I personally prefer to let any theme/plugin-level filters take precedence over what's set by users in wp-admin, but I realize there are different use cases there. Regardless, I might suggest going with `false` if either of those values are false, instead of the current behavior.

**Comment by futtta** [comment]
You're right, filters should overrule settings, I'll correct for AO26.

**Comment by futtta** [comment]
see commit https://github.com/futtta/autoptimize/commit/0c18c85c43e0b3e7e42911cb743b0cea9116291f Chris, would be great if you could take the beta branch out for a spin (it's what will become 2.6 later this year).
