### ISSUE TITLE
Console errors in Jetpack block post

### ISSUE THREAD

**Issue by willstocks** [futtta/autoptimize#273]
Hey Frank,

So I happened to add a Jetpack block to one of my posts recently (https://willstocks.co.uk/review-obins-anne-pro-2/#obinslab-starter-appfirmware) and I have noticed that along with that block, there's a bunch of markup that is added to the bottom of my `<body>` that is failing with the following (red) console errors:

```
(index):773 Uncaught TypeError: Cannot read property 'setLocaleData' of undefined
    at (index):773
    at (index):774

(index):777 Uncaught ReferenceError: _ is not defined
    at (index):777

(index):783 Uncaught TypeError: Cannot read property 'setLocaleData' of undefined
    at (index):783
    at (index):784

autoptimize_e9bb067858300bec08c2eaed35cc16e8.js:28 Uncaught ReferenceError: lodash is not defined
    at Object.5 (autoptimize_e9bb067858300bec08c2eaed35cc16e8.js:28)
    at o (autoptimize_e9bb067858300bec08c2eaed35cc16e8.js:28)
    at Module.276 (autoptimize_e9bb067858300bec08c2eaed35cc16e8.js:28)
    at o (autoptimize_e9bb067858300bec08c2eaed35cc16e8.js:28)
    at Object.275 (autoptimize_e9bb067858300bec08c2eaed35cc16e8.js:28)
    at o (autoptimize_e9bb067858300bec08c2eaed35cc16e8.js:28)
    at 21 (autoptimize_e9bb067858300bec08c2eaed35cc16e8.js:28)
    at autoptimize_e9bb067858300bec08c2eaed35cc16e8.js:28
```

Now... I assume this is because I'm using the following AO config:
![image](https://user-images.githubusercontent.com/43744514/64951881-d0109900-d876-11e9-8ed8-5bd20e48e4df.png)

But I'm not "excluding" something specific... that being said, I'm not sure I want to exclude it and I'm not really sure what this is all for/what it's actually doing - because the block works fine!

I believe/am sure it's lodash - which I have not dequeued etc. 

The exact Jetpack block used is "Jetpack Slideshow"

**Comment by willstocks** [comment]
Fixed by adding `lodash` to AO excludes - is this the only way this can realistically be handled?

**Comment by willstocks** [comment]
So now I'm down to just the two errors, after excluding `lodash` from AO

```
(index):771 Uncaught TypeError: Cannot read property 'setLocaleData' of undefined
    at (index):771
    at (index):772
(index):782 Uncaught TypeError: Cannot read property 'setLocaleData' of undefined
    at (index):782
    at (index):783
```

Which appear to be block related... I just am not sure where from (it's inlined for some reason!)

**Comment by futtta** [comment]
WordPress (Gutenberg) Blocks on the frontend are a pain to optimize and have big impact on performance. Generally I advice to simply add `js/dist` to the JS opt. exclusion list. Or not use blocks on the frontend off course ;-)

**Comment by willstocks** [comment]
The annoyance of convenience, eh?

No worries - to be honest, I don't really know/understand what these blocks are adding/doing with this locale info. It looks like something to do with translations... but it's adding it twice!! I think I'll log this with the Jetpack team as a separate issue as they're chucking a load of stuff into the bottom of my `<body>` most of which is nasty to look at!

```html
<script type='text/javascript'>
( function( domain, translations ) {
	var localeData = translations.locale_data[ domain ] || translations.locale_data.messages;
	localeData[""].domain = domain;
	wp.i18n.setLocaleData( localeData, domain );
} )( "default", { "locale_data": { "messages": { "": {} } } } );
</script>

...

<script type='text/javascript'>
( function( domain, translations ) {
	var localeData = translations.locale_data[ domain ] || translations.locale_data.messages;
	localeData[""].domain = domain;
	wp.i18n.setLocaleData( localeData, domain );
} )( "default", { "locale_data": { "messages": { "": {} } } } );
</script>
```

**Comment by willstocks** [comment]
Thanks for your help btw @futtta! I have raised this with the Jetpack team (https://github.com/Automattic/jetpack/issues/13475) so hopefully they can provide some insight as to why the code is duped + if this is even necessary

**Comment by willstocks** [comment]
Yikes!!! That’s a huge amount! Javascript devs and their dependencies these
days 🤦🏻‍♂️ Always another framework

I will keep an eye on it for sure, thanks Frank ☺️
