### ISSUE TITLE
Remove data-src  attribute after lazyloaded

### ISSUE THREAD

**Issue by Ridder90** [futtta/autoptimize#277]
Hi there! 

I am using the lazy load feature. However it styles all images as `display: block` based on a css query that targets the images with a data-src attribute. 

```
img[data-src], img[data-srcset] {
    display: block;
    min-height: 1px;
}
```

Is it possible to remove the data-src/data-srcset attribute after lazyloading, so that the original intended styling can be used (eg `display: inline-block;`). 

Another option would be to adjust the above styleblock to:
```
img[data-src]:not(.lazyloaded), img[data-srcset]:not(.lazyloaded) {
    display: block;
    min-height: 1px;
}
```

Thanks in advance!

**Comment by futtta** [comment]
Morgend @Ridder90; I don't see those being added on my site and can't seem to find references in the code, can you provide some more info?

**Comment by Ridder90** [comment]
You are right! After some deeper research. It was originating from a js plugin i didn't use anymore but some of its style adjustments where still in my stylesheet. Sorry for wasting your time :(
