### ISSUE TITLE
Issue with Essential Addons

### ISSUE THREAD

**Issue by tobias992** [futtta/autoptimize#279]
Hello,
i have a issue with Elementor Extension, Essential Addons.
Essential Addons has its own Cache... they build at Pageload after flush.
The Problem is i have to visit all my Sites from Website (so that the files are generated)... and after that i have to flush the Cache from Autoptimize again. If i dont do that... i only get "view-errors".

Steps:
1. Flush Cache from Essential Addons and Autoptimize (e.g. after an Update)
2. Visit all Sites from Website (there are overall view-errors from Essential Addons elements)
3. After every Page was visited -> clear the Cache only from Autoptimize
4. Visit the Sites again and then its works without view-errors

I hope you understand my bad english, sorry for that.

**Comment by futtta** [comment]
pretty weird ... my gut tells me clearing AO helps because clearing AO also
triggers a page cache purge, so can you purge your page cache instead of AO
to confirm?

**Comment by tobias992** [comment]
I use Cache Enabler as Page Cache System. I also tested with deactivation... same Problem.
My Server uses nginx with Advanced Configuration (https://www.keycdn.com/support/wordpress-cache-enabler-plugin).

If you want i can setup a demo-instance on my Server...

**Comment by futtta** [comment]
OK, let's go for the demo-instance, because I have absolutely no idea what
is happening there.

**Comment by tobias992** [comment]
Okay no Problem. Please can you give me your email so i can send you the credentials?

**Comment by futtta** [comment]
futtta-at-gmail-dot-com :)

**Comment by tobias992** [comment]
Okay... you got an email :)

**Comment by futtta** [comment]
discussed in mail, conclusion:
* the essential addons CSS is exlcude from AO by default (as in wp-content/cache)
* the essential addons CSS file name does not change when changes are made
* but the essential addons CSS file came with a updated version querystring, which was removed as per Autoptimize Extra configuration

disabling that last option (removal of querystring) fixed the problem as that ensures the cache to be bypassed if the version has changed.

**Comment by tobias992** [comment]
Hello,
sorry but the issue is not solved (but we know its not a Problem with Autoptimize).
Its only a querystring for Plugin Version... thats does not really help. When i am edit a Page and Clear the Cache.... the Cache is changed but the name and querystring is the same.

But the Problem is deeper with Essential Addons... at the Moment they have big Problems. Every update make new Problems.

Thanks for helping :)
