### ISSUE TITLE
Undefined variable: inlined_ccss_block

### ISSUE THREAD

**Issue by gidomanders** [futtta/autoptimize#280]
https://github.com/futtta/autoptimize/blob/c92350652fcb3213c8b0a7b65434a1ac74ddbf54/classes/autoptimizeStyles.php#L885

My logs are full of this message. The variable is only defined if inline CSS is deferred:

https://github.com/futtta/autoptimize/blob/c92350652fcb3213c8b0a7b65434a1ac74ddbf54/classes/autoptimizeStyles.php#L858

The variable preloadCssBlock doesn't have a default value either.

**Comment by futtta** [comment]
OK, should be fixed on the beta branch, can you [download the beta-zip](https://github.com/futtta/autoptimize/archive/beta.zip) and test to confirm OK?

**Comment by gidomanders** [comment]
Sorry for the late reply, but I can confirm it works in beta. Thanks!

**Comment by futtta** [comment]
Thanks for the confirmation, AO26 is in feature freeze and going in it's final stretch of beta, expected release around Christmas-time :-)
