### ISSUE TITLE
Undefined variabele placeholder

### ISSUE THREAD

**Issue by Ridder90** [futtta/autoptimize#281]
I get these warnings in my error_log on version 2.5.1 on Wordpress 5.2.4 . 
```
PHP Notice: Undefined variable: placeholder in /var/www/html/wp-content/plugins/autoptimize/classes/autoptimizeImages.php on line 558
```
Is there anything I can do to prevent these warnings?

**Comment by futtta** [comment]
OK, I pushed a fix to what will become AO26 @Ridder90 , can you [download the beta](https://github.com/futtta/autoptimize/archive/beta.zip) and take that out for a spin?

**Comment by Ridder90** [comment]
So sorry for the late response. Problem is solved!
