### ISSUE TITLE
Enhancement request: Add Nginx Helper

### ISSUE THREAD

**Issue by Lofesa** [futtta/autoptimize#282]
Hi @futtta

Some people are using Nginx Helper as a interface with the fastcgi cache. This plugin make the admin work of selective delting cached files.

How can this be added to Autoptimize to delete the whole fastcgi cache when automimize cache is deleted?

I found this code in the file `/includes/class-nginx-helper.php`: 
		
```
// expose action to allow other plugins to purge the cache.
$this->loader->add_action( 'rt_nginx_helper_purge_all', $nginx_purger, 'purge_all' );
```
Thx in advance

**Comment by futtta** [comment]
so simply adding 

```php
if ( defined('NGINX_HELPER_BASENAME') ) {
    do_action( 'rt_nginx_helper_purge_all' );
}
```
right?

Give me a couple of minutes, I'll commit to the beta branch :-)

**Comment by futtta** [comment]
OK, [committed](https://github.com/futtta/autoptimize/commit/7a156e4aef320ea79edb521e75b1533617819191);
-> if you clear AO's cache it will call on that action to have nginx helper do the same
-> if you purge all in nginx helper AO should also clear it's cache

can you test the beta-branch ([download zip here](https://github.com/futtta/autoptimize/archive/beta.zip))?

**Comment by Lofesa** [comment]
Hi @futtta 
Tested, it works in the 2 ways
👍

**Comment by futtta** [comment]
thanks for the confirmation @Lofesa :+1:
