### ISSUE TITLE
CSS Aggregation spliting into multiple files

### ISSUE THREAD

**Issue by Shirkit** [futtta/autoptimize#284]
Hello,

So I've been using Autopmize for ahilw now, and now I've given up on trying to understand why it does not aggregate all my CSS files into a single one. It spits out multiple CSS files.

Also, my JS file, although is a single one, it's not 100% minified.

You can check the temporary URL here: https://bit.ly/385epTR

Any help is appreciated, I'm trying to save time on loading (I will still revise images, they are not final yet, nor are their sizes).

I'm running Wordpress 5.3 on Autopmize 2.5.1 under Nginx

Anyways, thanks for your awesome plugin, I will always use it, since it's the best.

**Comment by futtta** [comment]
AO CSS
1. honors media types
2. by default excludes CSS from wp-content/cache and wp-content/uploads (to
avoid cache issues)

AO JS (and CSS) rely on file-naming to determine if a JS or CSS file is
minified. a file ending in e.g.  -min.js or .min.css will not be re-minified

hope this clarifies,
frank

**Comment by Shirkit** [comment]
Huuuum, I'm sorry, you're right. I'll play with wp-content/uploads to see if it gives issues, and gonna inspect who is not minifying the files and calling them min.js

Thanks for this awesome plugin.

**Comment by futtta** [comment]
you're welcome, feel free to leave a review of the plugin and support here
<https://wordpress.org/support/plugin/autoptimize/reviews/#new-post>! :-)
