### ISSUE TITLE
Preload and amp pages

### ISSUE THREAD

**Issue by Lofesa** [futtta/autoptimize#285]
Hi
I have "enabled" the preload assets puting a url in it ( Preload specific requests ) then in the amp validate in the admin bar I get issues.

I have made this change and the issue is gone:
File: lasses/autoptimizeExtra.php
I have added new lines 390 - 392
```
if (function_exists( ‘is_amp_endpoint’ ) && is_amp_endpoint()) {
          return $in;
 }
```

**Comment by futtta** [comment]
That's weird, [as `filter_preload` hooks into `autoptimize_html_after_minify`](https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeExtra.php#L180) and [when is_amp_endpoint() the page isn't autoptimized to begin with](https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeMain.php#L383-L406)?

Can you give a step-by-step procedure of how to reproduce (including how to do "amp validate in the admin bar")?

**Comment by Lofesa** [comment]
Sorry, can´t reproduce this now, only get the toolbar.js warnig.
"amp validate in the admin bar":
When you have the AMP from Automattic enabled, in the admin bar there have an AMP menu with 2 options. 1)  validate the post 2) view the amp version.
If all works, when you validate, the sow a list of errors. You can get this list, when in admin append &amp&amp_validate to a post/page url, in the html code there is a comment.

![Captura](https://user-images.githubusercontent.com/22342793/70334520-e01c9100-1845-11ea-9566-657022cfe6b4.jpg)

**Comment by futtta** [comment]
OK, so;
* what is the AMP error listed exactly (guess that is shown when you hover over or click on that item)?
* when you have your AMP pages validated by an external service (instead of from the top menu bar), do you get errors then?

**Comment by Lofesa** [comment]
Hi

- what is the AMP error listed exactly (guess that is shown when you hover over or click on that item)?

Step to get the amp validation errors:

1. loged in as admin
2. edit any post/page (maybe custom post but I don´t have it)
3. Clic in view the post/page
4. In the admin bar, the AMP menu show 2 options:
       1. view the amp version
       2. validate
5. Clic the validate option
6. Get a screen with a list of validation errors. If you click in a triangle near the Type, you can view all the error info. What plugin/theme, what file, what line......


- when you have your AMP pages validated by an external service (instead of from the top menu bar), do you get errors then?

No. When you validate the url in a external service don´t get any error, cause the offending thing (html, js...) is removed by the amp plugin.

**Comment by futtta** [comment]
That's the opposite of what AO does (or should do) actually, as per the code (part of which was provided by the lead amp plugin developer) ensures that AO simply is not active on AMP pages at all ... 

To be sure, are you indeed using https://wordpress.org/plugins/amp/ ?

**Comment by Lofesa** [comment]
Sure, the AMP plugin from Automattic. Is not very important since is in the admin side, but is a strange thing.
I have "forced" include the jquery.js in the amp page...then I have issues in this validation, some from autoptimize and the jquery himself.

![Captura](https://user-images.githubusercontent.com/22342793/70360456-e2e7a800-187e-11ea-90df-a128d8f502e1.jpg)

When I "solve" the jquery issue, no errors in the list.

![Captura1](https://user-images.githubusercontent.com/22342793/70360473-f0049700-187e-11ea-9299-2cd23a9c78d0.JPG)

**Comment by futtta** [comment]
Wow, that's a freaky edge-case :-)

**Comment by futtta** [comment]
closing as freaky edge-case with no tangible impact ;-)
