### ISSUE TITLE
Pages displaying incorrectly after Autoptimize Version 2.6.0 update

### ISSUE THREAD

**Issue by mcneiljv** [futtta/autoptimize#290]
Hi futtta and contributors! Thanks for the lovely plugin and all your hard work. I have Autoptimize installed on several of my sites and I've been running into some strange issues after the 2.6.0 update. One of them is present on my blog website (running Baskerville child theme). The content tiles are running together, but if I deactivate Autoptimize or switch to version 2.5.1 everything displays correctly. Will there be a possible hotfix for this?

<img width="1680" alt="Screen Shot 2019-12-26 at 1 01 47 PM" src="https://user-images.githubusercontent.com/42184621/71485740-b3beb980-27e0-11ea-901c-48e3cd9499a9.png">

Thanks,
Jamie McNeil

**Comment by futtta** [comment]
hey Jamie, can you;
* try with [the beta.zip file here](https://github.com/futtta/autoptimize/archive/beta.zip) which already has some fixes?
* if not OK with that beta, try disabling lazyload or image opt. or CSS opt or JS opt or HTML opt to try to identify which is causing this so we can decide on next steps?

frank

**Comment by futtta** [comment]
Have you had a chance to test already @mcneiljv ?

**Comment by mcneiljv** [comment]
Thank you Frank! For some reason downgrading to version 2.5.1 then upgrading back to 2.6.0 worked to fix my issues. Weird bug.

**Comment by futtta** [comment]
might have been the 2.5.1 version of lazysizes.min.js in AO being served from browser cache instead of the 2.6 one (assuming you had lazy-load active).

anyway, happy it now works for you :)
