### ISSUE TITLE
Do not create EMPTY minified css/js files and remove the HTML links (Solved by #308)

### ISSUE THREAD

**Issue by sjoerdlinders** [futtta/autoptimize#293]
If the css/js files are empty after minifying the content, then these empty files should NOT be saved and the HTML links should be removed.

Solved by #308

**Comment by futtta** [comment]
Theoretically correct, but if that's the case the same applies to the original CSS/JS enqueued off course ;-)

That being said; feel free to do a PR, I'll be happy to review/ commit it!

**Comment by sjoerdlinders** [comment]
In this case I have a css file that has only comments in the original file and is therefore not empty (and it will be used in the future, so i do not want to remove it from the child theme core):

FILE: /wp-content/themes/total-child-theme/style.css 
/* WARNING: Put ONLY global child theme styling here! */

**Comment by futtta** [comment]
That would only show up as a separated empty file in edge-case scenario's (aggregate CSS off, file matches exclusion string(s) or it being the only file with that specific media-attribute value).

So here as well, not top priority but as I wrote; feel free to do a PR, I'll be happy to review/ commit it! :-)
