### ISSUE TITLE
Add .min to the autoptimized file name extension (Solved by #307)

### ISSUE THREAD

**Issue by sjoerdlinders** [futtta/autoptimize#294]
Solved by #307
 
Please add .min to the minimized file name, because for example PHPStorm create minified file versions for the already minified autoptimize css / js files!

Example:
autoptimize_single_1c4d8bedf537a3052de0f9f8a0b6ecf8.css (Created by Autoptimize)
autoptimize_single_1c4d8bedf537a3052de0f9f8a0b6ecf8.min.css  (Created by PHPStorm)

**Comment by futtta** [comment]
Not sure I understand; how does PHPStorm (an IDE, correct?) interact with the frontend of a WordPress site?

**Comment by sjoerdlinders** [comment]
When I download the autoptimized files to my project it will automaticly minimize these files in PHPstorm itself, but that is not really the issue. The real problem is should have mentioned here is that other minifying software will try to minify the already minifyed files.

**Comment by futtta** [comment]
> The real problem is should have mentioned here is that other minifying software will try to minify the already minifyed files.

Afraid combining minifiers is always a bad idea.

To be clear; I'm not against `.min.`, but I don't consider this top priority.
