### ISSUE TITLE
Add do_action() after minimized file is created (3rd party connection) (Solved by #306)

### ISSUE THREAD

**Issue by sjoerdlinders** [futtta/autoptimize#295]
Solved by #306

Enhancement:
As plugin developer I need a action hook (to connect to) when a minified file is actualy created, so I can use my own plugin to staticly write the minified file to my website (on a other domain).
 
I already changed added this in my own local autoptimize plugin:
/wp-content/plugins/autoptimize/classes/autoptimizeCache.php

    public function cache( $data, $mime )
    {
            ...

	    // Provide 3rd party action hook for every cache file that is created.
	    // This hook can for example be used to inject a copy of the created cache file to a other domain.
	    do_action( 'autoptimize_action_cache_file_created', $this->cachedir . $this->filename );
    }

(Would be nice if this action hook becomes available in the next version.)

**Comment by futtta** [comment]
Looks OK for inclusion, feel free to do a PR :)

**Comment by sjoerdlinders** [comment]
Hi Frank, I'm a long time developer but a newbie to get software actually approved and committed, so i don't really know how to do the PR thing? ... sorry (also don't really want this in the conversation .. so can you delete this comment for me please. My personal e-mail is: sjoerd.linders AT yahoo DOT com)
