### ISSUE TITLE
[Question] Control location of consolidated stylesheet

### ISSUE THREAD

**Issue by lonix1** [futtta/autoptimize#296]
I'm using the optimise/aggregate css options - so it detects all non-CDN stylesheets, minifies and concats them.

However it places that consolidated file (`<link media="all" href="http://foo.com/wp-content/cache/autoptimize/css/autoptimize_uid.css" rel="stylesheet">`) BEFORE other (CDN) css files, and thus leads to bugs.

How can I control its placement? I want it after other css files, not before. Can that be done?

**Comment by futtta** [comment]
you can use AO's API to change the injection-point, e.g.;
```php
add_filter('autoptimize_filter_css_replacetag','override_css_replacetag',10,1);
function override_css_replacetag($replacetag) {
	return array("</head>","before");
	}
```

**Comment by lonix1** [comment]
This works perfectly, thanks! And thanks for the great plugin!

Also, I see you are a fan of banner style formatting... respect.

**Comment by futtta** [comment]
You're welcome :-)

And re. code formatting; you have @zytzagoo to thank for that, he not only improved AO significantly but has tried teaching me some coding guidelines & other best practices as well!
