### ISSUE TITLE
lazysizes tries to load attachment pages as extra stylesheets

### ISSUE THREAD

**Issue by michalgor** [futtta/autoptimize#297]
I'm using 2.6.1 of Autoptimize.

Every img tag on my site has data-link attribute specified with url pointing to attachment page for that image, for example:

data-link="https://[...]/?attachment_id=25420"

Looks like that lazysizes provided with Auoptimize has this plugin enabled:
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/unveilhooks

which treats data-link attribute as url for extra stylesheet which is dynamically loaded.

This generates errors in browser console (because it expects css not html) also has negative impact on performance, because it creates unnecessary server requests.

**Comment by futtta** [comment]
that's an interesting one @michalgor .. do you use a plugin to add/ enable linking to the attachment page? how is that logic added?

**Comment by michalgor** [comment]
AFAIK - no. I'm not using any plugin related to images. This isn't added by base Wordpress? Maybe it's theme related?

I will try to investigate it some more.

**Comment by michalgor** [comment]
Looks like data-link is added in browser. Generated html from wordpress doesn't contain that attribute for img's.

**Comment by futtta** [comment]
that's bizarre (or at least unknown to me) ... does this happen in any
browser and for any user, anonymous or logged in?

**Comment by michalgor** [comment]
Any browser. Logged or anonymous. Doesn't matter.

Also, looks like it happens when image is added in post using Gallery block, not happens with Image block.

I've found occurences of "data-link" in this file in wp code:

https://github.com/WordPress/WordPress/blob/master/wp-includes/js/dist/block-library.js

Inside var named gallery_deprecated_deprecated

**Comment by michalgor** [comment]
Sorry, i was wrong. It isn't added in browser, it's already there when page is downloaded.

I will check out this next week on fresh wp install.

**Comment by futtta** [comment]
OK, keep me posted. If need be we can use the AO API to have unveilhooks
removed from the inlined lazysizes JS (it is in there to be able to
lazyload background images).

**Comment by michalgor** [comment]
**1.** I've installed latest Wordpress. Haven't configured anything, haven't installed any themes / plugins. Everything is default.

I've created page and uploaded image using gallery block. I can confirm that data-link attribute is being set for img.

Here's tag:
`<img src="http://test.wp/wp-content/uploads/2020/02/image.jpg" alt="" data-id="8" data-full-url="http://test.wp/wp-content/uploads/2020/02/image.jpg" data-link="http://test.wp/index.php/2020/02/17/hello-world/image/" class="wp-image-8" srcset="http://test.wp/wp-content/uploads/2020/02/image.jpg 1024w, http://test.wp/wp-content/uploads/2020/02/image-300x251.jpg 300w, http://test.wp/wp-content/uploads/2020/02/image-768x643.jpg 768w" sizes="(max-width: 1024px) 100vw, 1024px">`

Here's full html: [page.zip](https://github.com/futtta/autoptimize/files/4213007/page.zip)

**2.** I've installed Autoptimize 2.6.1. Enabled only image lazy loading.

Firefox network monitor shows image is lazy loaded, but also data-link url is being loaded as stylesheet:
![Screenshot from 2020-02-17 11-11-25](https://user-images.githubusercontent.com/312874/74644341-6f172500-5176-11ea-9b08-0726c143893d.png)

Firefox console:
![Screenshot from 2020-02-17 11-11-46](https://user-images.githubusercontent.com/312874/74644437-90781100-5176-11ea-8e6a-70633e31a154.png)

**Comment by futtta** [comment]
Created an issue at lazysizes for this, see https://github.com/aFarkas/lazysizes/issues/750.

**Comment by michalgor** [comment]
I guess you could provide your own version of unveilhooks with those 4 lines commented out: 

https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/unveilhooks/ls.unveilhooks.js#L101

**Comment by futtta** [comment]
I prefer to stay in perfect sync with origin :)

**Comment by michalgor** [comment]
But i doubt they can change it without breaking backwards compatibility for other (non wordpress) users. Only solution probably would be to add some option to lazySizesConfig disabling this functionality.

**Comment by futtta** [comment]
let's await feedback from upstream B-)

**Comment by futtta** [comment]
So no movement from upstream, workaround implemented in https://github.com/futtta/autoptimize/commit/1f3598fbe65e5192a4f7485fdaeaae8eb4c3e72e.

**Comment by Flaschenzug** [comment]
Are you going to implement the workaround in one of the next updates? Or do I have to change it manually ? Thanks :-)

**Comment by futtta** [comment]
it's in 2.7 beta, you can download it from
https://github.com/futtta/autoptimize/archive/beta.zip

**Comment by michalgor** [comment]
I think you didn't fixed it correctly.

Recently i've noticed huge load on my server. Today i realized this error returned. Noticed this in browser in network tab. Also lot of access to attachment_id on apache access.log

Probably after updating plugin my fix stopped working. 

This is how you fixed it? I've found  this on https://github.com/aFarkas/lazysizes/issues/750
`
    tmp = target.getAttribute('data-link');
    if(tmp && target.tagName.toLowerCase != 'img'){
        addStyleScript(tmp, true);
    }
`

You aren't calling function - there's no () after toLowerCase. You basically are comparing function (not result of function) with string. Which always will gives false.

**Comment by futtta** [comment]
nah; if you look at [the diff](https://github.com/futtta/autoptimize/commit/1f3598fbe65e5192a4f7485fdaeaae8eb4c3e72e) or [the file](https://github.com/futtta/autoptimize/blob/1f3598fbe65e5192a4f7485fdaeaae8eb4c3e72e/classes/external/js/lazysizes.min.js) you'll see `toLowerCase()` :-)

![image](https://user-images.githubusercontent.com/181297/101261727-a375c500-3739-11eb-96dc-1b8f23cb39c9.png)

**Comment by michalgor** [comment]
But current version is broken. Looks like this commit broken it:

https://github.com/futtta/autoptimize/commit/4938407e2064d066addf3fe05db3409aad00dddb

**Comment by futtta** [comment]
Hm, maybe something went wrong with minification, I'll have a look tomorrow. You're just in time for the 2.8 release by the way, if confirmed broken I'll ship the fix in there (after validating by you) ;-)

**Comment by futtta** [comment]
OK @michalgor, can you try (the lazysizes.min.js in) the beta branch, it should work now?
