### ISSUE TITLE
Prefetch CDN URL

### ISSUE THREAD

**Issue by BrookeDot** [futtta/autoptimize#298]
When a CDN is defined it would be great to add a prefetch header to the browser. This could either be an option, or perhaps preferred on by default. 

I'm thinking something like this just not sure the best place to add it:

```
if ( ! empty( $this->cdn_url ) ) {
	public function cdn_dns_prefetch( $hints, $relation_type ) {
		$maybe_prefetch = apply_filters( 'autoptimize_prefetch_cdnurl', true );
		if ( 'dns-prefetch' === $relation_type && (bool) $maybe_prefetch ) {
			$hints[] = $this->cdn_url;
		}
		return $hints;
	}
	add_filter( 'wp_resource_hints', array( $this, 'cdn_dns_prefetch' ), 10, 2 );
}
```

Thoughts?

**Comment by futtta** [comment]
Just add the CDN domain to Autoptimize -> Extra -> Preconnect (which
includes the DNS-lookup)? :)

**Comment by BrookeDot** [comment]
Today I learned that was an option. Closing.
