### ISSUE TITLE
Checkbox for "Inline and Defer CSS?" does not work

### ISSUE THREAD

**Issue by jasongong91** [futtta/autoptimize#299]
If you leave code within "Inline and Defer CSS?" even if the checkbox is unchecked I believe it still may be trying to render the page with above the fold css.
![image](https://user-images.githubusercontent.com/57649266/75379571-759a5080-588a-11ea-8f17-d1ef18eb47a6.png)

Had some flicker on our webpage which was resolved after removing the css from the unchecked above fold css textfield.

**Comment by futtta** [comment]
did a quick test and this is not the case Jason. [the code also says no](https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeStyles.php#L888), so this seems like coincidence really :)
