### ISSUE TITLE
jsmin-php is unmaintained

### ISSUE THREAD

**Issue by szepeviktor** [futtta/autoptimize#3]
You can read it here: https://github.com/rgrove/jsmin-php/

Consider https://github.com/tedious/JShrink instead.

**Comment by futtta** [comment]
as per the code jsmin-1.1.1.php is only used when "legacy minifiers" are enforced. as the goal of that flag (in wp-config.php) is to ensure autoptimize falls back on the old optimizers, it would make no sense to replace jsmin.php  with something else :-)
