### ISSUE TITLE
poll: does AO 2.0 work for you?

### ISSUE THREAD

**Issue by futtta** [futtta/autoptimize#30]
So does Autoptimize 2.0 Beta work (not talking about the current version, 1.9.4) for you?

Please chime in by replying with "OK" (aka `:+1:`) or "Not OK" (aka `:-1:`), in which case some extra info would be welcome!

**Comment by futtta** [comment]
:+1:

**Comment by grantdb** [comment]
Works great! :+1: 

Thanks!

**Comment by Naviprode** [comment]
marvelous - with help of autoptimize now a Pingdom tools speed score from 99!

**Comment by peterbowey** [comment]
Great code work @futtta !
Works well for me!  :+1:

**Comment by futtta** [comment]
so to be clear guys; your feedback is indeed specifically for the latest 2.0 beta-version? not interested in the "ancient" 1.9.4 here, just need confirmation if 2.0 works :-)

**Comment by Naviprode** [comment]
yes, latest download version, version 1.99 shown in wordpress

**Comment by futtta** [comment]
fyi: the beta on wordpress.org has just been sync'ed with the version here on GitHub. 

Changes:
1. fix for inline CSS not being aggregated when that option is active
2. fix for some background images with data-uri's sttill being sent through the cdn-ing routine
3. fix for language-files not being loaded
4. updated language files for multiple languages

**Comment by futtta** [comment]
updated the beta-version again:
* new FR translations
* [fixed a nasty bug](https://github.com/futtta/autoptimize/commit/ec09a2c1ac42530b1d3fe360212353bbcc563571) affecting e.g. jquery-validation.min.js getting broken

frank

**Comment by futtta** [comment]
updated beta, [fixing an cssmin-issue](https://github.com/futtta/autoptimize/commit/10d5ff82204c43cb4930cdd68dcfdef1928de47f) with 
`flex: 1 1 auto`
becoming
`flex: 1 1auto`

if all goes well, AO 2.0 could get released between Christmas & New Years ... :-)

**Comment by peterbowey** [comment]
@futtta
Well done, a great release on AO 2.0!

**Comment by dsalimian** [comment]
thumbs up, v2.0 works great :+1:

**Comment by futtta** [comment]
AO 2.0 will get released tomorrow, Saturday 26th. This date will allow a slow update pick-up rate (due to weekend between Christmas & New Years), limiting the damage in case a (major) bug would still be in there.

Thanks for all the testing guys!
frank

**Comment by peterbowey** [comment]
@futtta many thanks!
