### ISSUE TITLE
Preconnect option not working after recent update

### ISSUE THREAD

**Issue by mwpastore** [futtta/autoptimize#300]
At some point in the recent past, the "Preconnect to 3rd party domains (advanced users)" option seems to have stopped working. The domains listed in our settings are not being added to our WordPress pages. I've tried a few different domains and formats with no change.

**Comment by futtta** [comment]
Can you share the URL of the impacted site + what you have in the preconnect field Mike?

**Comment by mwpastore** [comment]
Pfft, naturally, I tried "one more time" after posting this and it's working now. So... sorry for the noise. Cheers!

**Comment by futtta** [comment]
no worries Mike, main thing is that now it does work :-
