### ISSUE TITLE
Lazy loading placeholder generator incompatible with HTML minifier

### ISSUE THREAD

**Issue by innocenat** [futtta/autoptimize#302]
So I was investigating why the lazy-loading was causing layout reflow, and I found 3 issues in the lazy loading PHP code.

1. The (built-in) HTML minifier remove quotation mark from `width` and `height` of `<img>`, so the regular expression `#height=("|'|)(.*)("|'|)#Usmi` in `get_size_from_tag` ([here](https://github.com/futtta/autoptimize/blob/7af99e7c2a1015b2ee5cc0aba71c80758b1b8d5d/classes/autoptimizeImages.php#L626)) was unable to detect the width and height of an image.
2. [Variable name misspell](https://github.com/futtta/autoptimize/blob/7af99e7c2a1015b2ee5cc0aba71c80758b1b8d5d/classes/autoptimizeImages.php#L742). [Here too](https://github.com/futtta/autoptimize/blob/7af99e7c2a1015b2ee5cc0aba71c80758b1b8d5d/classes/autoptimizeImages.php#L745).
3. [This condition](https://github.com/futtta/autoptimize/blob/7af99e7c2a1015b2ee5cc0aba71c80758b1b8d5d/classes/autoptimizeImages.php#L741,L744) can never be true because the `get_size_from_tag` return blank string  if it cannot find the image width/height.

**Comment by futtta** [comment]
for (2) & (3) feel free to clone, correct & issue a PR

for (1); only when using W3TC, which overrides AO's built-in HTML minifier and is _a lot_ more aggressive.

**Comment by innocenat** [comment]
While I do have W3TC running, if I disable AO's HTML optimization the problem goes away though. Does AO just trigger the W3TC minifier?

Would you mind if I also include the fix for (1)? (which is to change the regexp to `#height=("|'|)?([0-9%]+#smi`)

**Comment by futtta** [comment]
W3TC overrides AO's HTML minifier, so if you have AO HTML minfying active, you're actually seeing W3TC's in action. 

AO's HTML minifier does not remove quotes. Disable W3TC to confirm :-)

**Comment by innocenat** [comment]
I am going to take your word on that since I don't have any install that I could disable W3TC easily right now, just wondering since I didn't have W3TC minify enable.

Still, would you mind if I also include the regexp fix for this case too?

**Comment by futtta** [comment]
I'd prefer a fix for (2) and (3) to start with, we can look into (1) after
that :)

**Comment by futtta** [comment]
better yet might be 3 separate PR's each tackling 1 issue, if that's OK for you? :)

**Comment by futtta** [comment]
hey @innocenat ; any news on this? hoping on marking 2.7-beta-2 soon (within a couple of days), so would be great to include your PR's if ready :)

**Comment by innocenat** [comment]
Sorry for non-communication.

I still don't have PR ready, sorry. The reason I actually posted it as an issue and not PR in the first place is because I currently don't have time to properly tested all the situations yet (yeah, I just vim'd the source on the server for the site I was maintaining). I actually doesn't even have local wordpress installation right now. I don't mind if you just go ahead and fix it, even with the changes I detailed.

**Comment by futtta** [comment]
OK, will do :-)

**Comment by futtta** [comment]
2 & 3 should be fixed with https://github.com/futtta/autoptimize/commit/39f9398dca0b3ac48197a61c23a8574713e28073 @innocenat , thanks for the valuable input!

**Comment by futtta** [comment]
for (1) you could try this code snippet;
`
add_filter('autoptimize_filter_imgopt_fixquotes', '__return_true');`

which [triggers some quotes being re-added](https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeImages.php#L930-L937).

**Comment by innocenat** [comment]
No, it doesn't. It just triggers quote for class="..." only, not for width and height attribute.

**Comment by futtta** [comment]
Correct ... I _might_ add support for width & height there for 2.7.

**Comment by futtta** [comment]
ok, https://github.com/futtta/autoptimize/commit/889db907c04c40d2a8c0345ceccd5af779d5808f should also add quotes around height & width attribs @innocenat
