### ISSUE TITLE
problem with image and layzload

### ISSUE THREAD

**Issue by Flaschenzug** [futtta/autoptimize#303]
Hey there.

I have a problem with wordpress gallery images that are lazyloaded.

> Stylesheet https://www.slackliner-berlin.de/wp-content/uploads/2020/02/beach-slackline-auf-gestell-bei-firmenfeier.jpg wurde nicht geladen, weil sein MIME-Typ, "image/jpeg", nicht "text/css" ist.

Images are loaded propperly. But the console throws an error per image.

Open console, see the problem here: https://www.slackliner-berlin.de/events/

Any ideas what is going on here?
Thanks!

**Comment by futtta** [comment]
yes, issue with lazysizes (the lazyload JS library) acting on data-link attributes, see https://github.com/futtta/autoptimize/issues/297 for more info. will close this one as duplicate.

**Comment by Flaschenzug** [comment]
thanks
