### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by flaviomdutra** [futtta/autoptimize#309]
When I upload the plugin in the Wordpress panel, it shows the print below:

<img width="734" alt="Screen Shot 2020-03-29 at 09 53 01" src="https://user-images.githubusercontent.com/7936766/77849627-813ba880-71a3-11ea-80b7-36c20b7a1b7a.png">

And I can't seem to activate it.

**Comment by futtta** [comment]
that means your hoster isn't allowing you to activate/ use Autoptimize
Flavio, nothing I (or the plugin) can do to fix that I'm afraid.

**Comment by flaviomdutra** [comment]
Is there any server configuration that is necessary for the plugin to be activated?

**Comment by futtta** [comment]
no, nothing whatsoever
