### ISSUE TITLE
The "Add try-catch wrapping" setting does not work together with source maps

### ISSUE THREAD

**Issue by Tymvie** [futtta/autoptimize#311]
Steps to reproduce:

1. Install the https://wordpress.org/plugins/shortcodes-ultimate/ plugin and add the following shortcode: `[su_expand more_text="Show more" less_text="Show less" height="24" text_color="#333333" link_color="#0088FF" link_align="left"]test.[/su_expand]` in order to enqueue a script that contains a source map

2. Enable the "Add try-catch wrapping" setting.

The js file created by Autoptimize produces a js error because the catch statement does not exist

**Comment by futtta** [comment]
Try/catch wrapping is a last resort and should be off anyway as it slows
down JS execution speed considerably (see
https://blog.futtta.be/2014/08/18/when-should-you-trycatch-javascript/) :-)

That being said; if you have a fix for this I'll be happy to review a PR
and merge if OK.

**Comment by futtta** [comment]
Below code snippet can be used to remove the sourcemaps if you want.

```php
add_filter( 'autoptimize_js_after_minify', 'remove_sourcemaps', 10, 1 );
function remove_sourcemaps( $css_in ) {
	return preg_replace( '/(?:\/\/|\/\*)# sourceMappingURL\s?=.*\.map\s?(?: \*\/)?$/m', '', $css_in );
}
```
