### ISSUE TITLE
Crtitical CSS Tab (Edit or Remove)

### ISSUE THREAD

**Issue by CymruUSA** [futtta/autoptimize#313]
This is more an enhancement and not a bug but sometimes when you are trying to track some issue down you need to "pause" the the critical CSS. The two options are Edit or Remove and I don't want to do either. I just want to be able to test with CCSS removed until I can find a cause. Thanks.

**Comment by futtta** [comment]
just disable "inline & defer CSS" and things should be as if there was no critical CSS @CymruUSA  :-)
