### ISSUE TITLE
Not accessible source maps in Autoptimize CSS

### ISSUE THREAD

**Issue by KittMedia** [futtta/autoptimize#315]
Hi,

similar to #39, I’m running into the problem by having a source maps reference in my compiled Autoptimize CSS file.
The current version can be found here: https://kittmedia.com/wp-content/cache/autoptimize/6/css/autoptimize_bc53f29c698db4635560559886c39feb.css

There you can find the following line from my stylesheet CSS:
```
/*# sourceMappingURL=style.min.css.map */
```

Even if `$filecontent = preg_replace( '#^\s*\/\*[^!].*\*\/\s?#Um', '', $filecontent );` in `autoptimizeBase.php` matches. 🤔

The stylesheet CSS is enqueued with this URL: https://kittmedia.com/wp-content/themes/proteus/style.min.css

I’m running the latest version of Autoptimize, which is currently version 2.6.2.

I would be happy to get help in fixing this to avoid unnecessary 404 requests against a non-existing CSS source map.

After a little bit of testing, I can get rid of it by using the above regular expression in the filter `autoptimize_css_after_minify` to remove the source map:

```php
add_filter( 'autoptimize_css_after_minify', function( $css ) {
	return preg_replace( '#^\s*\/\*[^!].*\*\/\s?#Um', '', $css );
} );
```

However, I don’t think that this is intended.

**Comment by futtta** [comment]
don't worry; the unnecessary 404 is only done when you have the developer
console open, but is not there for your normal visitors.

**Comment by KittMedia** [comment]
Yes, I know that, but since I want to get rid of 404 errors on my website – careless where they come from – and since the plugin shouldn’t break something that has been working before (by using the source map from the regular enqueued CSS file), I think that should be fixed. 🙂

**Comment by futtta** [comment]
Well, I you can contribute the code to honor sourcemaps, I'll be happy to
review/ merge :-)

**Comment by futtta** [comment]
Better still; here's a code snippet for you to enjoy ;-)

```php
add_filter( 'autoptimize_css_after_minify', 'remove_sourcemaps', 10, 1 );
function remove_sourcemaps( $css_in ) {
	return preg_replace( '/(?:\/\/|\/\*)# sourceMappingURL\s?=.*\.map\s?(?: \*\/)?$/m', '', $css_in );
}
```

(the reason it was still in the optimized CSS is because the sourcemap was in a minified file (as per the filename), so AO won't re-minify the file so the comment is not removed).
