### ISSUE TITLE
Fix for proposed image height / width could lead to wrong owl carousel height

### ISSUE THREAD

**Issue by reneebeling** [futtta/autoptimize#317]
I'am using an owl-carousel slider on a blog and ran into some problems after updating from 2.6.2 to 2.7.0.
I've tried find the problem and found this change between the two versions in the ...\autoptimize\classes\autoptimizeImages.php:

![image](https://user-images.githubusercontent.com/64730014/80911859-75776f00-8d6b-11ea-8665-83e052b11f53.png)

If I am replacing the fixed code from 2.7.0 with the actual wrong code (e.g. misspelling heigth instead of height) of version 2.6.2, I will see everything as expected (see [reference page](https://www.lisannjenrich.com/)).
This is only a workaround for me but can you change this behaviour ("calculated" height) in a later version. 
Thanks a lot.

Rrené

See owl-carousel slider on frontpage with my workaround:
https://www.lisannjenrich.com/

**Comment by futtta** [comment]
Hmm, AO doesn't have anything to go on to correctly calculate the width and height and so it cannot but make some (stupid) assumptions, so guess you'll have to either:
* add the correct width & height parameter in the HTML source OR
* exclude those images from being lazyloaded OR
* use the `autoptimize_filter_imgopt_lazyload_placeholder` filter to change the width & height in there to your liking
