### ISSUE TITLE
Lint error: $this used in a static method

### ISSUE THREAD

**Issue by Fastigium** [futtta/autoptimize#318]
While scanning my plugins preparing for a PHP version upgrade, I got an error about this line:

https://github.com/futtta/autoptimize/blob/51c44faa80b75b78b0f56c3d3c2b2e9c62b2a76b/classes/autoptimizeCriticalCSSCron.php#L826

The exact error (a bit misleading, but I'm guessing it's triggered because the `ao_ccss_cleaning` method is static):

> 826 | ERROR   | "$this" can no longer be used in a plain function or method since PHP 7.1.

CriticalCSS is not enabled in autoptimize on my blog, so I'm guessing I can safely upgrade my PHP version, but I thought I'd report the error here so it may be addressed :slightly_smiling_face:. Thanks for providing us with this awesome plugin, much appreciated!

**Comment by futtta** [comment]
good catch, no idea why I made that static to begin with! :grin:

**Comment by futtta** [comment]
fixed in 2.7.1
