### ISSUE TITLE
Font CSS URL not being set to CDN

### ISSUE THREAD

**Issue by JeffPyeBrook** [futtta/autoptimize#32]
Noticed a couple of files not being redirected to come from CDN.  The specific case is the fontawsome.css

This is what is in the CSS.
```
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.3.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.3.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.3.0') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.3.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.3.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.3.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

Was also wondering if the **fixurls** function in the **autoptimizeStyles** class could use the cdn url when set instead of the site url?

**Comment by futtta** [comment]
cdn'ing the font is in the code, but is off by default (as fonts are subject to cross domain request policy and cdn's are considered another domain, which requires config on the cdn-site to work). if you pass "true" to the autoptimize_filter_css_fonts_cdn filter you should see the fonts cdn'ed.

frank

**Comment by futtta** [comment]
code snippet for that filter;

```php
add_filter('autoptimize_filter_css_fonts_cdn','cdn_fonts');
function cdn_fonts() { 
    return true; 
}
```

**Comment by futtta** [comment]
Were you able enable font CDN replacement with this method Jeff?

**Comment by JeffPyeBrook** [comment]
Thanks for checking in Frank. I haven't updated the site yet, just enjoying the post holiday rush quiet. :)

**Comment by futtta** [comment]
Do enjoy the end-of-year celebrations Jeff, all the best wishes! :-)

**Comment by denydias** [comment]
@futtta,

I have tested this. Indeed, CDN url font rewriting refuse to work regardless of `autoptimize_filter_css_fonts_cdn` set to `true`. The condition for entering the font URL rewriting code looks ok, which makes me think that this might be caused by the regex itself.

This used to work during our talk when developing #18. I had no time to investigate this further.

**Comment by denydias** [comment]
By the way, it used to work before 3718016.

**Comment by futtta** [comment]
this commit is the root cause; https://github.com/futtta/autoptimize/commit/0760b0ef15e57b19de7e4ffd1234582694da0059

now problem; got `unexpected T_SL` with `'LOD'` (albeit on older versions of PHP, but still) and get `preg_match_all(): Compilation failed: range out of order in character class at offset 68` with `LOD` ...

**Comment by futtta** [comment]
heredoc (`LOD`) vs nowdoc (`'LOD'`) issue, should clearly be nowdoc to avoid any parsing of the regex being parsed. problem (minor, given the passing of PHP<5.5) is that nowdoc "only" got introduced with PHP 5.3.

cfr. http://php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc

**Comment by Angristan** [comment]
Hello, where do we have to put this ?
```
add_filter('autoptimize_filter_css_fonts_cdn','cdn_fonts');
function cdn_fonts() { 
    return true; 
}
```

**Comment by futtta** [comment]
in your theme's functions.php (if you're not worried about it being overwritten). or you could use [the code snippets plugin](https://wordpress.org/plugins/code-snippets/)?

**Comment by Angristan** [comment]
I added it in my child theme's functions.php but it does not make anything :(

**Comment by JeffPyeBrook** [comment]
I like to drop a little php file into the mu-plugins directory for these kinds of setting. By doing this I preserve the code when I switch between themes.

This is what I have in my wp-content/mu-plugins/auto-opt.php file right now
```

/**
 * Do we want to minify?
 * If set to false autoptimize effectively only aggregates, but does not minify.
 *
 * @return: boolean true or false
 */

function my_ao_js_minify() {
	return true;
}

add_filter( 'autoptimize_js_do_minify', 'my_ao_js_minify', 10, 1 );


/**
 * Stop autoptimize from optimizing, e.g. based on URL as in example.
 *
 * @return: boolean, true or false
 */
function my_ao_noptimize() {
	$optimize_the_page = true;

	if ( is_admin() ) {
		return false;
	}

	if ( defined( 'DONOTCACHEPAGE' ) && DONOTCACHEPAGE ) {
		error_log( __FUNCTION__ . ' do not cache page, no auto optimize' );
		$optimize_the_page = false;
	}

	return ! $optimize_the_page;
}

add_filter( 'autoptimize_filter_noptimize', 'my_ao_noptimize', 10, 0 );


/**
 * apply url to cdn fonts
 */
function cdn_fonts() { 
    return true; 
}

add_filter('autoptimize_filter_css_fonts_cdn','cdn_fonts', 10, 0 );

```

**Comment by Angristan** [comment]
Exemple of what I am getting after ading the PHP code to functions.php : https://cdn.angristan.fr/wp-content/cache/autoptimize/css/autoptimize_46fe77cc7533973617044ceabbff9c01.css

**Comment by futtta** [comment]
hi angristan;
not sure what's going wrong, when [testing the regex used to extract font url's on regex101 this does work with -an excerpt of- your CSS](https://regex101.com/r/mA2mG0/3). If you want I can create a Gist with some debug-output in that function to better understand what is happening?

frank

**Comment by futtta** [comment]
angristan; do make sure you [apply this change](https://github.com/futtta/autoptimize/commit/d63cec2748eec01e586b42d597c25056f4eaa2e8) for font-CDN-replacement to work (small bug in 2.0)

**Comment by Angristan** [comment]
I don't understand what do you mean with you regex. I modified what you told me but no changes.
I am ok for the debug  :)

**Comment by futtta** [comment]
can you first and foremost have a peek in your php errorlog to see if anything bad by autoptimizeStyles is logged there?

**Comment by Angristan** [comment]
Nothing in the log

**Comment by Angristan** [comment]
Oh, in fact I have someting in my nginx log : http://hastebin.com/napojabiqo.log

**Comment by futtta** [comment]
well, then I guess you didn't to the change from https://github.com/futtta/autoptimize/commit/d63cec2748eec01e586b42d597c25056f4eaa2e8 after all?

`$fonturl_regex = <<<LOD`
on approx. line 400 in wp-content/plugins/autoptimize/classes/autoptimizeStyle.php should become
`$fonturl_regex = <<<'LOD'`

maybe double-check ;-)

If not; I just finished the version with debug-output (to wp-content/ao_log.txt);
```php
			// CDN the fonts!
			$this->ao_logger("before replace fonts",false);
			if ((!empty($this->cdn_url))&&apply_filters("autoptimize_filter_css_fonts_cdn",false)) {
				$this->ao_logger("ready to replace fonts",false);
				$fontreplace = array();
				$fonturl_regex = <<<'LOD'
~(?(DEFINE)(?<quoted_content>(["']) (?>[^"'\\]++ | \\{2} | \\. | (?!\g{-1})["'] )*+ \g{-1})(?<comment> /\* .*? \*/ ) (?<url_skip>(?: data: ) [^"'\s)}]*+ ) (?<other_content>(?> [^u}/"']++ | \g<quoted_content> | \g<comment> | \Bu | u(?!rl\s*+\() | /(?!\*) | \g<url_start> \g<url_skip> ["']?+ )++ ) (?<anchor> \G(?<!^) ["']?+ | @font-face \s*+ { ) (?<url_start> url\( \s*+ ["']?+ ) ) \g<comment> (*SKIP)(*FAIL) | \g<anchor> \g<other_content>?+ \g<url_start> \K ((?:(?:https?:)?(?://[[:alnum:]\-\.]+)(?::[0-9]+)?)?\/[^"'\s)}]*+) ~xs
LOD;

				preg_match_all($fonturl_regex,$code,$matches);
				if (is_array($matches)) {
					$this->ao_logger("found fonts, going through array",false);
					foreach($matches[8] as $count => $quotedurl) {
						$url = trim($quotedurl," \t\n\r\0\x0B\"'");
						$this->ao_logger("cdn-ing: ".$url,false);
						$cdn_url=$this->url_replace_cdn($url);
						$fontreplace[$matches[8][$count]] = str_replace($quotedurl,$cdn_url,$matches[8][$count]);
					}
					if(!empty($fontreplace)) {
						$this->ao_logger("str_replacing cdn'ed fonts",false);
						$code = str_replace(array_keys($fontreplace),array_values($fontreplace),$code);
					}
				} else {
					$this->ao_logger("no fonts found",false);
				}
			} else {
				$this->ao_logger("no cdn set or filter not true",false);
			}
```

This should replace the block without debug-output in wp-content/plugins/autoptimize/classes/autoptimizeStyle.php.

frank

**Comment by Angristan** [comment]
Of course I did ;) ![autoptimize](https://lut.im/xHwa03moGO/aUbaEPQ1KZlNds6U.PNG)

I also have to put this code in my functions.php ?

**Comment by futtta** [comment]
the debug code goes in wp-content/plugins/autoptimize/classes/autoptimizeStyle.php (replacing the existing block), 

but first of all; do you have any more errors in your nginx.log (in your screenshot the last visible one was yesterday at 17h48?

**Comment by Angristan** [comment]
No, the last entry is from 2016/01/07 17:48:29.

**Comment by futtta** [comment]
ok, that's when you implemented the newdoc-change, I guess?

next step; (assuming you have a CDN set in AO and you cleared caches to make sure this isn't a caching issue) edit wp-content/plugins/autoptimize/classes/autoptimizeStyle.php, and around line 394 replace the entire "cdn the fonts"-block with the code from https://github.com/futtta/autoptimize/issues/32#issuecomment-169987983

**Comment by Angristan** [comment]
your log looks like this 
```
root@lyra ~# cat /srv/wordpress/wp-content/ao_log.txt
before replace fonts
--
ready to replace fonts
--
found fonts, going through array
--
before replace fonts
--
ready to replace fonts
--
found fonts, going through array
--
before replace fonts
--
ready to replace fonts
--
found fonts, going through array
--
before replace fonts
--
ready to replace fonts
--
found fonts, going through array
--
before replace fonts
--
ready to replace fonts
--
found fonts, going through array
--
```

**Comment by Angristan** [comment]
I think I changed the line before, but this is possible. Iit's not a cache issue.

**Comment by futtta** [comment]
ok, can you try adding this:
`add_filter('autoptimize_filter_css_inject_min_late','__return_false');`

to your child theme's functions.php?

**Comment by Angristan** [comment]
I keep this ?
```
add_filter('autoptimize_filter_css_fonts_cdn','cdn_fonts');
function cdn_fonts() { 
    return true; 
}
```

**Comment by Angristan** [comment]
It works \o/

**Comment by Angristan** [comment]
Another bug : https://angristan.fr/wp-includes/js/wp-emoji-release.min.js is the last one that is not with the CDN URL. With isn't it with the big .js file ? http://tools.pingdom.com/fpt/#!/bc8GYT/https://angristan.fr

**Comment by futtta** [comment]
the wp-emoji-release.min.js file is injected by other JS and AO isn't supposed to change URL's inside JS, so I don't consider that a bug actually :-)

but do you need & want those pesky emoji's? else simply dequeue the hell out of them or install [the disable emoji's plugin](https://wordpress.org/plugins/disable-emojis/).

**Comment by Angristan** [comment]
I don't know why, but the bug is back today. :( 

Do you know any way to change the URL of wp-emoji-release.min.js btw ?

**Comment by futtta** [comment]
re. bug: you actually need the font-filter-thingie, it cannot work without that really :-)

re. emoji: a rewrite in your nginx config maybe?

**Comment by Angristan** [comment]
I deleted your modifications in autoptimizeStyle.php to disable log.

By I still have 
```
// Enable CDN for Autoptimize fonts
add_filter('autoptimize_filter_css_fonts_cdn','cdn_fonts');
function cdn_fonts() {
return true;
}
add_filter('autoptimize_filter_css_inject_min_late','__return_false');

```
in my functions.php.

Yep I think i'm gonna go for a rewrite but the utility of the CDN is decreased :/

**Comment by Angristan** [comment]
Edit : everything is ok, thanks for the support ;)

**Comment by futtta** [comment]
heureusement ;-)

bonne weekend!
frank

**Comment by Angristan** [comment]
À toi aussi :)

**Comment by themenow** [comment]
This doesn't work for me:

```
// Enable CDN for Autoptimize fonts
add_filter('autoptimize_filter_css_fonts_cdn','cdn_fonts');
function cdn_fonts() {
return true;
}
add_filter('autoptimize_filter_css_inject_min_late','__return_false');

```

Fonts url are unchanged, tried everything :(

**Comment by oinbar** [comment]
FYI this is not working on newest version. I tried setting $do_font_cdn in autoptimizeStyles.php and it just unpacked the entire JS/CSS compacted versions calling EVERYTHING through the CDN, not just fonts. Not sure if its the regex, or the filter logic, but either way this should probably be a setting in the UI.

Thanks.

**Comment by futtta** [comment]
have you tried below code snippet @oinbar (using [the code snippets plugins](https://wordpress.org/plugins/code-snippets/) or in your child theme's functions.php);
`
add_filter('autoptimize_filter_css_fonts_cdn','__return_true');`

**Comment by sainisagar310** [comment]
I have tried below code but still it isn't working for me.
`add_filter('autoptimize_filter_css_fonts_cdn','cdn_fonts');
function cdn_fonts() {
return true;
}
add_filter('autoptimize_filter_css_inject_min_late','__return_false');
`
