### ISSUE TITLE
Javascript error on Critical CSS tab

### ISSUE THREAD

**Issue by uprise10** [futtta/autoptimize#320]
Please see the screenshot below:

![critical-css-error](https://user-images.githubusercontent.com/1333461/81677047-dd574500-9450-11ea-86ff-4bce6c7bf8d6.png)

Due to (probably) a translation error, the Javascript on the Critical CSS tab is broken.

**Comment by futtta** [comment]
[Should be fixed in the current version of the beta](https://github.com/futtta/autoptimize/commit/ff09c8937f3a0b07bec58e9297f2e6b1d2eed5f2) Arjan, can you [download](https://github.com/futtta/autoptimize/archive/beta.zip) & test to confirm?

**Comment by uprise10** [comment]
It is. thanks!

**Comment by futtta** [comment]
OK, closing here, will release as 2.7.2 later this week.

Groeten uit België! :-)
