### ISSUE TITLE
CCCS Tab - Delete Rule not saving

### ISSUE THREAD

**Issue by CymruUSA** [futtta/autoptimize#321]
Using V2.7.2-beta-0

Current Behavior 
Scroll to a a path based rule and choose delete. AO responds with a dialog box "This Critical CSS rule will be deleted immediately and cannot be recovered. Are you sure?" Click Delete and AO scrolls to the top of the page and displays a discreet message "Rules or Queue changed! Don't forget to save your changes!"

This is not ideal since the message is calling for an additional action before the actual removal but has the appearance of a typical success message that is generally ignored. Move away from page and there is no additional warning. Rules are not removed.

Suggested
Would it not be better to have a checkbox next to the rules where you can choose one or many rules to remove and have a single button to delete rules and save in the same action? It would also make it easier when deleting multiple rules.

Thank you.

**Comment by futtta** [comment]
true, and that might (and should) change in the future. no eta though :-)

**Comment by futtta** [comment]
this was part of 2.9.1 @CymruUSA , so i can finally close this one :)
