### ISSUE TITLE
NGINX 502

### ISSUE THREAD

**Issue by tobias992** [futtta/autoptimize#322]
Hey,
with your new Update i have a very tricky problem with my websites and php7.4 with opcache:

After update i get an 502 error...

error.logs:
PHP-FPM:  child xxx exited on signal 11 (SIGSEGV)
NGINX:  recv() failed (104: Connection reset by peer)

WordPress Email:  /xxx/xxx/autoptimize/autoptimize.php Allowed memory size of xxx
I switched the php memory limit for testing to 1 GB - but same result.

After switch to php7.3 (opcache enabled) - the site is loading fine.

**Comment by futtta** [comment]
Don't really see [what change in the update](https://github.com/futtta/autoptimize/compare/2.7.1...2.7.2) could cause memory usage to grow Tobias .. :-/

**Comment by tobias992** [comment]
I switched all my Websites to PHP7.3 - now all is running fine.

Must be a Bug in PHP7.4.6. At the beginning from PHP7.4 i also had much problems with opcache. Looks like 7.4 is not really usable on stable environments at the Moment.
