### ISSUE TITLE
Getting inlined CSS when unchecked

### ISSUE THREAD

**Issue by CymruUSA** [futtta/autoptimize#323]
I have been flushing cache a lot recently since I am working on the site. 

What I've noticed is at times when I delete all cccs rules and jobs, save then return to plugin home page and save, then flush cache, the newly produced cache is inlining all css into the html even though that is not the chosen option. CCCS tab remains visible and rules are being created but I have no separate css file.

**Comment by futtta** [comment]
When "inline & defer CSS" and critical CSS are active and no matching rules are found, the plugin inlines all CSS as fallback-solution @CymruUSA so that is expected behavior. If you create a "default CCSS rule" this will not happen.

hope this clarifies,
frank
