### ISSUE TITLE
ignoring/exlcuding files from compression with inline "tag"

### ISSUE THREAD

**Issue by Flaschenzug** [futtta/autoptimize#324]
Is there a way to exclude scripts from compression with an inline tag?
e.g. <script src="SCRIPT.min.js" compression-ignore></script>

Would be an amazing thing if I don't have to add it to the "ignore" input field in the settings.
Thanks a lot

**Comment by futtta** [comment]
data-noptimize=1 should work (see what is added to the lazyload tag) :-)
