### ISSUE TITLE
lazyload not working with caching

### ISSUE THREAD

**Issue by Flaschenzug** [futtta/autoptimize#327]
i wrote a small caching plugin that fires after "autoptimize_html_after_minify":
`add_filter('autoptimize_html_after_minify', function ($content) {`

The caching itself is working (optimized code is used). But the lazyload functionality is not.
It's not written in the file.

Do you add the lazyload functions after autoptimize_html_after_minify ?
Or do you have any other ideas, why it is not included ?

Thanks :-)

**Comment by futtta** [comment]
indeed; cfr. https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeImages.php#L118-L123

add your own filter with priority 11 maybe?
