### ISSUE TITLE
Can't aggregate JS-files and show product images after newest update.

### ISSUE THREAD

**Issue by daandegroot123** [futtta/autoptimize#328]
Since the newest update of Autoptimize (2.7.3) my product images didn't appear anymore. They could still be found in the Chrome inspector at the same place, with working links to the images. However, the images themselves didn't show up. I found that disabling Autoptimize fixed the issue and afterwards found that the 'Aggregate JS-files' caused the problem. 

For now, I fixed the problem by just disabling the option. But, it would be nice if this could be fixed later on, for optimizing of course. Here is a list of my plugins on my website related to product images, page building or images in general:

- WooCommerce 4.2.0
- Elementor 2.9.12
- Elementor Pro 2.10.0
- JetWooBuilder 1.6.4
- WebP Express 0.17.3
- WP Fastest Cache 0.9.0.7
- reSmush.it Image Optimizer 0.3.7
- Autoptimize 2.7.3

**Comment by futtta** [comment]
my money is on the smush lazyload JS that might need to be excluding :)

**Comment by daandegroot123** [comment]
reSmush.it doesn't have lazy loading, I believe. I do use Autoptimize lazy loading, but turning that off didn't solve the issue.

**Comment by futtta** [comment]
so when JS aggregate is active and images don't load, what JS errors do you
see on the browser console?

**Comment by daandegroot123** [comment]
I see two errors in the console, one regarding Autoptimize and one regarding Jetpack, however, I don't use any of Jetpack's optimizing features.

![image](https://user-images.githubusercontent.com/41082044/84808240-b4eed780-b008-11ea-9e0f-0e579abf40f2.png)

**Comment by futtta** [comment]
looks related to facebook the fbq param/ object not being known at that point, probably due complianz. try disabling "also aggregate inline JS" or try adding `fbq` to the comma-separated JS optimization exclusion list?

**Comment by daandegroot123** [comment]
Neither adding `fpq` to the exclusion or disabling "also aggregate inline JS" or even doing both, solves the problem.

**Comment by futtta** [comment]
I'll need to see this happening, do you have a staging site where you can leave things broken?

**Comment by daandegroot123** [comment]
It isn't an easy site to migrate to staging. I tried [recreating ](http://www.rubenvanstiphout.nl/autoptimizeissue/product/test-product/)the problem here with the same plugins (the ones that I believe could cause the problem), theme, etc. 
But, the problem doesn't occur now. I do use Cloudflare on the website and not on the staging website, maybe that could cause problems?

**Comment by daandegroot123** [comment]
I see now that the staging site does give me the same error in the console, but the image is still visible so that makes this situation interesting.

**Comment by futtta** [comment]
Only error I see (in Chrome, no errors in FF) is a problem with the favicon? 

![image](https://user-images.githubusercontent.com/181297/84986467-e49ffb80-b13e-11ea-96dd-c0a926a012c0.png)

**Comment by daandegroot123** [comment]
Oh, huh. I saw it earlier, but now it's gone. I will just keep aggregating JS off to solve the problem.

**Comment by futtta** [comment]
could (have) be(en) cloudflare (rocket loader?) indeed, quite the mystery ;-)
