### ISSUE TITLE
Critical CSS conflicting with WP Rocket LazyLoad

### ISSUE THREAD

**Issue by webtrainingwheels** [futtta/autoptimize#329]
Hi Frank! 👋🏼

Our developer, Remy, found a little bug which is affecting our LazyLoad. 
Looks like it's related to your new code for Critical CSS which is wrapping our inline JS for lazyload with this, multiple times, and preventing our script for working correctly: https://github.com/futtta/autoptimize/blob/1edf162a95700a220ae643e56c83ffc0dd8a64a7/classes/autoptimizeCriticalCSSCore.php#L172

We saw [the post on your WP.org support forum from our mutual customer ](https://wordpress.org/support/topic/critical-css-breaks-lazy-loading-in-wp-rocket/)in which disabling the deferring of jquery was suggested as the solution.
Would it be possible to do an automatic exclusion in AO so that it will work seamlessly in the future?
Thanks!

**Comment by futtta** [comment]
yeah, it's a potentially "dangerous" option (a quick hack really) which by default is not checked for good reason. I might replace the code behind it at a later stage with something more robust ;-)

**Comment by futtta** [comment]
the clumsy "defer jQuery" logic [has been replaced with something more reliable](https://github.com/futtta/autoptimize/commit/cc7396fe8d3b51af2afba6e3ca1599316f8c7b0f) and a quick test with Rocket Lazyload does work now so closing Lucy :-)
