### ISSUE TITLE
Fatal error optimizing styles

### ISSUE THREAD

**Issue by JeffPyeBrook** [futtta/autoptimize#33]
Woke up this morning to a site that is down , and an error log that is full of these messages. 

[12-Jan-2016 06:26:22 America/New_York] PHP Warning:  preg_match_all(): Compilation failed: range out of order in character class at offset 68 in /wp-content/plugins/autoptimize/classes/autoptimizeStyles.php on line 401

**Comment by JeffPyeBrook** [comment]
Replaced WordPress repos plugin with GitHub master and a different error

[12-Jan-2016 07:36:32 America/New_York] PHP Warning:  preg_match(): Compilation failed: missing ) at offset 22 in wp-content/plugins/autoptimize/classes/autoptimizeStyles.php on line 650

**Comment by futtta** [comment]
There indeed was a bug in 2.0.0 for those that activated the font-cdn-filter [as reported by deny](https://github.com/futtta/autoptimize/issues/32#issuecomment-167602162). This has already been fixed here on Github and will be in AO 2.0.1.

**Comment by futtta** [comment]
ah, a missing ), let me quickly check that out..

**Comment by JeffPyeBrook** [comment]
Should "#(background[^;}]*url\(#Ui" become "#\(background[^;}]*url\(#Ui"?

If so, will the regex match if there is a space between the '(' and 'background"? Should it match?

**Comment by futtta** [comment]
Still looking, but I think I simply forgot to remove the opening ( in the regex;

```php
preg_match("#background[^;}]*url\(#Ui",$css)
```
can you try that?

frank

**Comment by JeffPyeBrook** [comment]
OK, the fix is live on this site if you want to look at the css

http://sparkle-gear.com/

Sorry my regex skills aren't that great, but it looks like the expression is trying to match a line that is a background declaration ending with a semicolon. Is it going to be a problem for CSS lines that do not end with the semicolon, as is sometimes the case with valid single attribute css statements like 
```
body {
    background-image: url("paper.gif")
}
```

**Comment by futtta** [comment]
no, as it also looks for `}`, which it finds (on the next line), cfr. https://regex101.com/r/kU1kA7/1

not a regex-specialist either, but regex101.com is a huge help :-)
