### ISSUE TITLE
Autoptimize and visual regression testing

### ISSUE THREAD

**Issue by megclaypool** [futtta/autoptimize#332]
Hey there,

This is more of a support request than a bug report:

I'm using Autoptimize to lazy load images on a site, but am running in to trouble with my visual regression testing -- when BackstopJS takes its screenshots, the lazy load images are in various stages of loading and so my tests are failing.

On some of our Drupal sites, we use bLazy, which has a javascript command that I can have Backstop enter in the browser dev console to force the immediate load of lazy load images. (`bLazy.load(document.querySelectorAll(".lazyload"), true);`) Do you know of a similar command I could use for Autoptimize, or another way to force the immediate loading of images for testing?

Thanks for your time and help; we use your plugin on most of our WordPress sites and appreciate your hard work 😀

**Comment by futtta** [comment]
Well, AO uses lazysizes, documentation of which can be found at
https://github.com/aFarkas/lazysizes, but apart from lazysizes.init()
(which fires automatically) I'm not sure if more can be done. You could
test with the ?ao_nolazy=1 parameter added to the URL to stop lazyload from
being active for those tests?

**Comment by megclaypool** [comment]
Cool!!!

I stumbled across mention of lazysizes in some of your old documentation, and their documentation explains that lazysizes has the command `lazySizes.loader.unveil(imageElement)`. So I worked out that I could add the following to my onReady script to get the images to load right away:

```
/*
  * Run a command in the puppeteer browser's terminal
  * (These specific commands are to force immediate loading of lazyload images that are screwing up my diffs!)
  */
await page.evaluate(() => {
  // Force immediate load of WP Autoptimize lazyload images
  if (typeof lazySizes !== "undefined" && typeof lazySizes.loader !== "undefined" && typeof lazySizes.loader.unveil !== undefined) {
    var imageArray = document.querySelectorAll(".lazyload");
    imageArray.forEach((image) => lazySizes.loader.unveil(image));
    setTimeout(function () {
      console.log("Giving lazyload images time to load...");
    }, 2000);
  }

  // Force immediate load of Drupal blazy lazyload images
  if (typeof Drupal !== "undefined" && typeof Drupal.blazy !== "undefined") {
    Drupal.blazy.init.load(document.getElementsByClassName("b-lazy", true));
    setTimeout(function () {
      console.log("Giving lazyload images time to load...");
    }, 2000);
  }
});
``` 

However, if I go to http://mysite.domain/?ao_nolazy=1 and run `typeof lazySizes`, I get "undefined" 🎉   So using your url trick is even better, because the lazyloading doesn't happen in the first place 😀  I'm going to go ahead and leave that code in my onReady script, as a kind of "belt *and* suspenders", since it won't fire unless I've forgotten to add `?ao_nolazy=1` to the end of my url. 

Thank you so much for the url tip -- it's exactly what I was hoping for and superior to the javascript solution I'd found 😀 😀 😀

**Comment by futtta** [comment]
happy it works Meg! :-)
