### ISSUE TITLE
Disabling the automatic queue

### ISSUE THREAD

**Issue by uprise10** [futtta/autoptimize#334]
Is it possible to disable the automatic queue for critical CSS generation and only rely on the manual given rules?

**Comment by futtta** [comment]
This might indeed be added later, but is not possible currently Arjan.

**Comment by uprise10** [comment]
Ok thanks.. I've solved it this way now:

```php
add_action( 'init', static function () {
	add_filter( 'cron_schedules', static function( $crons ) {
		if( isset( $crons['ao_ccss'] ) ) {
		    unset( $crons['ao_ccss'] );
		}
			
		return $crons;
	}, 99 );		
}, 99 );
```

When there is a beter option, I'd be happy toi be updated about it
