### ISSUE TITLE
ErrorException: Warning: strpos(): Empty needle when AUTOPTIMIZE_CACHEFILE_PREFIX is empty

### ISSUE THREAD

**Issue by tdtgit** [futtta/autoptimize#335]
Hi,

When I set `AUTOPTIMIZE_CACHEFILE_PREFIX` to an empty value, it's run fine without any issues and have a nice path (e.g `<link href="/wp-content/cache/css/bb23571f36922af6d16e2e6b2ed13ddf.css" rel="stylesheet">`) but the issue will come up when you logged in and AO count the valid files.

I think if `AUTOPTIMIZE_CACHEFILE_PREFIX` is empty, we can consider all files in `AUTOPTIMIZE_CACHE_CHILD_DIR` is of AO. What do you think? 😊

**wp-config.php**
```php
define('AUTOPTIMIZE_CACHE_CHILD_DIR', '/cache/');
define('AUTOPTIMIZE_CACHEFILE_PREFIX', '');
```

**Result:**
```
ErrorException /wp-content/plugins/autoptimize/classes/autoptimizeCache.php in autoptimizeCache::is_valid_cache_file
Warning: strpos(): Empty needle
```

**Expected result:**
No warning.

**Comment by futtta** [comment]
Nah, the code is based on the assumption there always is a prefix and I
don't intend to change that (it might break things elsewhere and don't want
to go down that rabbithole). Sorry!

**Comment by tdtgit** [comment]
Thanks for your quick response. So anyway I can suppress this warning without edit your code?

**Comment by futtta** [comment]
Afraid not; the strpos check uses the constant that holds the prefix, so
either the prefix is set (e.g. to "a") and it works or the prefix is not
set and you get that error.

**Comment by tdtgit** [comment]
Thanks! I will close this issue now. Stay safe.

**Comment by futtta** [comment]
You too Argus!
