### ISSUE TITLE
Granular Control! Removal of Inlined Critical CSS and Control of CSS Placement

### ISSUE THREAD

**Issue by AndresInSpace** [futtta/autoptimize#337]
Not really an issue, just showing how to for those that like messing with code.
If you have a more precise way this should be done @futtta, please let me know!
Well, the only issue I have really is that I would like to see a way to retreive the final url autoptimize generates for the aggregated css. eg wp-content/cache/autoptimize/css/autoptimize_fa48f0186c129d8965dc7cd3c78f7f1f.css
Ok onwards to the actual topic!
I needed some granular control over this plugin, basically:
1. On a specific condition, I do not want the site-wide custom CCSS (critical CSS) I added in autoptimize panel to be output on this specific page.
2. On same condition, defer the rest of the aggregated CSS (autoptimize_*.css) to the footer.
Hope this helps someone!

All added to (child) theme functions.php

The condition (true) replace with your own condition. It is using true here so it will work if you copy pasta it, but you would ideally do something like checking if a specific page/post template is in use.
If true wp_head calls function changeTheCSS

```
if(true){
    add_action('wp_head','changeTheCSS', 1);
}
```
ChangeTheCSS is doing two things:
1. We are basically resetting this filter which would usually call ao_ccss_frontend and inject critical css https://github.com/futtta/autoptimize/blob/4cda84c379503c8adc18331daca206c9c81dc7fd/classes/autoptimizeCriticalCSSCore.php#L34
https://github.com/futtta/autoptimize/blob/60fd08d4cc3b6abcf291733e846086b634625f21/classes/autoptimizeCriticalCSSCore.php#L68
2. Specify to autoptimize where to place the CSS block
```
function changeTheCSS() {
    add_filter('autoptimize_filter_css_defer_inline','removeInlineCSS',10,1);
    add_filter('autoptimize_filter_css_replacetag','moveCSSto',10,1);
}
```
Nothing fancy here, just return. You could probably do something fancy, but this serves our (my) needs.
```
function removeInlineCSS($s){
    return;
}
```
Function to return array parameters that autoptimize receives via autoptimize_filter_css_replacetag and uses as a reference of where to inject the CSS block in content.
We are telling it to inject before the closing body tag. 
```
function moveCSSto($replacetag) {
    return array("</body>","before");
}
```

Thanks for coming to my TED Talk.

**Comment by futtta** [comment]
thanks for sharing  @AndresInSpace :-)
