### ISSUE TITLE
CSS optimizer rewrite wrong url with WP_CONTENT_URL set

### ISSUE THREAD

**Issue by innocenat** [futtta/autoptimize#338]
Note: This is not a regression in recent version. It has been here for a while, but I just got around to try to identify the problem.

For example, if I have a wordpress at https://example.com and set WP_CONTENT_URL to https://example-static.com, then the CSS optimizer rewrite the relative URL in the css wrong.

For example, if I have a file at https://example.com/wp-content/themes/example/style.css that includes the line `url(fonts/woff2/example.woff2)`, the correct rewrite is `url(//example-static.com/themes/example/fonts/woff2/example.woff2)`, but currently it is `url(//example-static.com/wp-content/themes/example/fonts/woff2/example.woff2)` which is wrong.

My current workaround is to `ln -s $PWD wp-content` but it's really hacky and I want to remove it.

**Comment by futtta** [comment]
afraid such a setup is not supported by AO, although with some filter-magic you might get it working. or the soft-link off course ;-)

**Comment by innocenat** [comment]
So you are saying the core wordpress feature is not supported? Great!

**Comment by futtta** [comment]
I'm saying that if you tinker with WordPress core to have a different wp-content URL, you'll have to tinker with AO as well (via the API). If you ask nicely I'll even give you some pointers how to do so :stuck_out_tongue:

**Comment by innocenat** [comment]
Thinker with wordpress core? The WP_CONTENT_URL is a documented feature, and is in many set up guide as how to set up cookieless domain with wordpress.

I already read the code -- I see how I could do using filter, but that's not the point I am creating this issue. At least you should document that custom WP_CONTENT_URL is not supported.

**Comment by futtta** [comment]
My point is that changing WP_CONTENT_URL might be a documented feature, but is it not something extensively used; I think you're maybe the 3rd or 4th user asking about this. Taking into account AO is in use on approx. 1.5 million sites, this really is an edge-case :-)

But you're right I ought to document this, I will make sure to do so! 

Have a nice day :-)
