### ISSUE TITLE
AutoOptim plugin causing a blank white screen 

### ISSUE THREAD

**Issue by colbyschemm** [futtta/autoptimize#342]
I updated a Wordpress site to the latest version of AutoOptim today (2.7.8) and now several pages on our website are serving a blank white screen. 

Deactivating the plugin has temporarily resolved the issue, making it clear that it is causing the underlying issue on our site. However, I'm not sure the specific issue within the plugin that is causing this to happen.

**Comment by futtta** [comment]
OK, some things to do @colbyschemm;
* can you check the php errorlog for relevant entries ?
* can you try disabling CSS or JS or HTML or Image optimization to see which one might be causing this?
* can you try disalbing the "404 fallback" option to see if that makes a difference?

frank

**Comment by colbyschemm** [comment]
@futtta, thanks for helping! 

I activated CSS, JS, and HTML optimization and was able to isolate the issue. It seems like the white/blank screen is only happening when I have `Optimize JavaScript Code?` selected. The only sub-item we have selected in the JS optimization section is "Aggregate JS-files?". 

I did not check my PHP errorlog yet, and the "404 Fallback" was already toggled off. 

Do you have any suggestions of what could be going wrong with the JS?  I currently have the CSS and HTML optimization running without any problems so far.

**Comment by futtta** [comment]
OK, so what happens when you disable "aggregate JS-files", does that "fix" things?

**Comment by colbyschemm** [comment]
It's so strange, at first things were working on our site when I disable JS optimization. Now I have had to completely disable the plugin because both CSS and HTML were causing issues as well. 

Any other ideas?

**Comment by futtta** [comment]
Hmmm ... afraid "issues" is a tad too vague here @colbyschemm, can you be more specific?

-> if you have only HTML optimization active, what is broken?
-> if you have only JS optimization active, what is broken?
-> if you have only JS optimization AND JS aggregation active, what is broken?
-> what is in the PHP-errorlog?

And do you have a non-production site where you could leave things broken and if so can you share the URL?

**Comment by futtta** [comment]
hey @colbyschemm any progress? :-)

**Comment by colbyschemm** [comment]
Hey @futtta, thank you for helping out on this. Sorry for the slow responses. Unfortunately I didn't have time to resolve this and moved forward with another solution. Thanks again for your help.
