### ISSUE TITLE
Warning class 'Minify_CSS' not found

### ISSUE THREAD

**Issue by insad** [futtta/autoptimize#343]
Getting entries in www error log (php-fpm):

`call_user_func() expects parameter 1 to be a valid callback, class 'Minify_CSS' not found in /[hidden]/wp-content/plugins/autoptimize/classes/external/php/minify-html.php on line 228`

Plugin version 2.7.8
PHP version 7.4.7
Using php-fpm
WP version 5.5.1 (dutch)

**Comment by futtta** [comment]
No idea how that can happen I'm afraid;
-> CSS minify in minify-html.php is only executed if cssMinifier option is
set (see
https://github.com/futtta/autoptimize/blob/5429135ba1f1c507f49c873b42fc3c1c68c6d8f6/classes/external/php/minify-html.php#L78-L80
and
https://github.com/futtta/autoptimize/blob/5429135ba1f1c507f49c873b42fc3c1c68c6d8f6/classes/external/php/minify-html.php#L78-L80
-> but autoptimizeHtml.php does not set that option, only xhtml and
keepcomments (see
https://github.com/futtta/autoptimize/blob/5429135ba1f1c507f49c873b42fc3c1c68c6d8f6/classes/autoptimizeHTML.php#L79-L83
)

So I think something else (another plugin) is also calling the Minify_HTML
class which AO loads. Try disabling plugins one at a time to see what the
conflicting plugin is maybe?

**Comment by insad** [comment]
Yes indeed some conflict with another plugin that does minifying....
