### ISSUE TITLE
Produces error “Critical error on your website”.

### ISSUE THREAD

**Issue by ObscenityIB** [futtta/autoptimize#344]
Latest available plugin version on wordpress disables the website with a critical error message.

It's not very verbose, so I don't have any more details than this is the specific plugin doing it.

**Comment by futtta** [comment]
Normally a mail is sent to the site owner with more info, did you receive one? If not, can you check the PHP errorlog?

**Comment by ObscenityIB** [comment]
> 
> 
> Normally a mail is sent to the site owner with more info, did you receive one? If not, can you check the PHP errorlog?

No email. No errors in php log. No php errors in apache log

**Comment by futtta** [comment]
In that case try First and foremost try to identify what is breaking things
by just enabling CSS or JS or HTML or Image optimization (incl. lazyload),
maybe that allows us to narrow down somewhat (because to be clear for me
and most other users all works well)?

frank

**Comment by ObscenityIB** [comment]
> 
> In that case try First and foremost try to identify what is breaking things by just enabling CSS or JS or HTML or Image optimization (incl. lazyload)

cant change any options if the plugin wont load

**Comment by futtta** [comment]
ah, it's on the backend? even more bizarre, as AO does not optimize the
backend. guess that leaves us with the possibility of a plugin conflict of
some sort, which you could investigate by disabling all plugins and then
enabling AO and if that works (finger crossed) enable other plugins one at
a time to see if that triggers a WSOD?

**Comment by ObscenityIB** [comment]
Already used that method to confirm it was this specific plugin doing it.

**Comment by futtta** [comment]
So to be very precise; even with only AO active (no other plugins active at
all) you still get a WSOD?

**Comment by ObscenityIB** [comment]
Yes

```
[01-Nov-2020 13:15:17 UTC] PHP Warning:  require(/var/www/html/wp-content/plugins/autoptimize/classes/autoptimizeUtils.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/autoptimize/autoptimize.php on line 72
[01-Nov-2020 13:15:17 UTC] PHP Fatal error:  require(): Failed opening required '/var/www/html/wp-content/plugins/autoptimize/classes/autoptimizeUtils.php' (include_path='.:/usr/share/php') in /var/www/html/wp-content/plugins/autoptimize/autoptimize.php on line 72
```

**Comment by ObscenityIB** [comment]
looks like autoptimizeUtils.php is missing, but why

**Comment by ObscenityIB** [comment]
Ill back up the existing contents and drop in the current versions for now

Full tree for comparison

![image](https://user-images.githubusercontent.com/6983255/97804160-15be3a00-1ca2-11eb-9e4d-544b26f3c7c6.png)

**Comment by futtta** [comment]
well, it is on the wordpress.org svn (from which the zip-files are created automatically), see; https://plugins.trac.wordpress.org/browser/autoptimize/tags/2.7.8/classes

either there was some kind of issue when installing AO (in which case re-installing should help) or something (a security component?) removed autoptimizeUtils.php ?

**Comment by ObscenityIB** [comment]
As far as wordpress can see on the frontend, everything is up to date and installed correctly.

I compared the files it had to the files in the release
Everything marked as "Right only" is in the release, but not the update.

![image](https://user-images.githubusercontent.com/6983255/97804517-9d0cad00-1ca4-11eb-899b-52c7ca2f8238.png)

![image](https://user-images.githubusercontent.com/6983255/97804575-ea891a00-1ca4-11eb-942e-b9e012024b10.png)

**Comment by ObscenityIB** [comment]
On another note, its also one of the only two plugins that have autoupdate enabled.
Closing this now, since everything works.

**Comment by futtta** [comment]
seems like something went wrong during the auto-update (although AO was last updated on Oct. 9th, so not sure how this only updated recently?)
