### ISSUE TITLE
Minify script type application/ld+json

### ISSUE THREAD

**Issue by radex02** [futtta/autoptimize#345]
I use Rank Math for SEO and it adds an application/ld+json script for the SEO schema, but it is not minified by autoptimize. Also, it looks kinda odd when looking as the HTML as it is the only unminified part.

Please make it minify like any other JSON.

**Comment by futtta** [comment]
from a perfmonce point of view this is a micro (or nano) optimization
really so not likely to be implemented soon except if you're into coding
yourself and you want to contribute ;-)
