### ISSUE TITLE
Setting up non-standard wp_content locations.

### ISSUE THREAD

**Issue by joelschlotterer** [futtta/autoptimize#347]
We are using Sage 9 with bedrock which obfuscates the WP install, creating a non standard location for the wp-content folder. In the readme I see mention of an API and couple lines of code that can fix this. I can't seem to find any info about what those lines of code might be or even any documentation about the API. Is this something that's actually fixable or do I have to add this custom folder and chown it as part of our dev ops deployment process?

**Comment by futtta** [comment]
Is `wp-content` simply renamed while keeping the WordPress URL structure intact (so e.g. `https://domain.com/not_wpcontent/`) or is it somewhat more complicated?

**Comment by joelschlotterer** [comment]
Bedrock restructures the entire WordPress install the path would be https://domain.com/app/uploads/
https://roots.io/bedrock/

**Comment by futtta** [comment]
but that is /wp-content/uploads, right? so /wp-content/ == /app/?

let me put things differently; for each of the below what would the bedrock
path be?

* wp-content/cache/
* wp-content/uploads/
* wp-content/plugins/
* wp-content/themes/

frank

**Comment by joelschlotterer** [comment]
No, its like this:
app/uploads
app/themes
app/plugins

no wp-content folder - 
Bedrock does this for 2 main reasons, it allows for freely changing wordpress core versions up and down making rolling back updates easier, and secondly it provides some security by obscurity.

**Comment by futtta** [comment]
And -just for me to understand- how is AO broken in this case? Does it not optimize at all, or does it not optimize some JS/ CSS or does it store the cached optimized CSS/ JS in the wrong place?

**Comment by joelschlotterer** [comment]
Most of the time we see everything is fine:

Cache Info
Cache folder	/var/www/html/web/app/cache/autoptimize/
Can we write?	Yes

However, occasionally we have had the entire Autoptimize admin options disappear with only an admin notice on the plugins page that the cache directory wasn't writable:
Autoptimize cannot write to the cache directory (/var/www/html/web/app/cache/autoptimize/), please fix to enable CSS/ JS optimization!

I was assuming that the file wasn't writable because it wasn't in the uploads. I'm not sure that's actually the problem.

**Comment by futtta** [comment]
No, I don't think that is the problem indeed .. not sure what would be
though :-/ there's no restrictions on where files can be written in bedrock
or in your setup?

**Comment by joelschlotterer** [comment]
We wrote some custom chowning into our deploy process to ensure we have consistent write access where we need it for this. Thank you very much for your fast response.

**Comment by futtta** [comment]
Thank you Joel :)
