### ISSUE TITLE
Autoptimze mess up CSS and JS

### ISSUE THREAD

**Issue by Angristan** [futtta/autoptimize#35]
Hello,

I wiped my autoptimize cache today and my website is not displaying properly :

![screenshot_27-01-2016_jqohofmo](https://cloud.githubusercontent.com/assets/11699655/12622970/3d390302-c528-11e5-937a-0e2ebe6ca267.png)
instead of : 
![screenshot_27-01-2016_qh5vtggv](https://cloud.githubusercontent.com/assets/11699655/12622979/48107472-c528-11e5-8896-0a2b9288c170.png)

I do not have any HTTP erros like 404 so I don't understand. All my CSS and JS are in the 2 files as always.

**Comment by futtta** [comment]
would have to see it while not working angristan (on a dev-env?) or at least see a webpagetest.org test while AO is active and keeping AO's cache present so I can look at the source of the ao-files that would be in the webpagetest.org test report.

going to close here as not a code issue in AO itself, better to open a topic on https://wordpress.org/support/plugin/autoptimize to continue.

bien à toi,
frank

**Comment by Angristan** [comment]
You're right, I should have done that !

Here it is : https://wordpress.org/support/topic/autoptimize-breaks-css-and-js?replies=2#post-7947397
