### ISSUE TITLE
Autoptimize Incompatible with Product Filters for WooCommerce

### ISSUE THREAD

**Issue by joshjrom** [futtta/autoptimize#350]
I installed and activated Product Filters for WooCommerce (by WooCommerce) but noticed that all product filters weren't working. I deactivated all plugins and found that Autoptimize was the culprit. 

Here is a screenshot of Autoptimize deactivated - https://snipboard.io/O78LQ3.jpg

Here is a screenshot of Autotimize activated - https://snipboard.io/ygVLRM.jpg

From the screenshot which shows Autoptimize plugin deactivated, you'll notice that the Price Slider isn't showing up as is the case with other filters - nothing happens when clicked on. 

Can you assist in resolving this issue, please?

**Comment by futtta** [comment]
Given what Autoptimize does and how it works, there is no such thing as
guaranteed out-of-the-box compatibility with any plugin Josh. Conflicts
like these typically simply require some re-configuring of Autoptimize
(Settings -> Autoptimize). In this case you can disable JS optimization or
JS aggregation or you can try to exclude the product filter plugin from JS
optimization ). If you need more assistance, feel free to open a support
topic on the WordPress support forum for Autoptimize (
https://wordpress.org/support/plugin/autoptimize/).

frank

**Comment by joshjrom** [comment]
Thank you for getting back to me. 

I would prefer to exclude Product Filters for WooCommerce (by WooCommerce) from JS optimisation but I have no clue about how to achieve this. I have gone ahead to open a support topic on the WordPress support forum for Autoptimize as I feel I require more assistance.
