### ISSUE TITLE
Undefined index: autoptimize_imgopt_number_field_7 in /var/www/html/wp-content/plugins/autoptimize/classes/autoptimizeImages.php on line 773

### ISSUE THREAD

**Issue by markusreis** [futtta/autoptimize#351]
Hey!

I get the given following warning on all projects where I use autoptimize. You might want to add some safety-check there. Must've been introduced in some of the very previous updates: 

```Undefined index: autoptimize_imgopt_number_field_7 in /var/www/html/wp-content/plugins/autoptimize/classes/autoptimizeImages.php on line 773```

Autoptimize is on version 2.8.1

Cheers!

**Comment by futtta** [comment]
[fixed in the github version already](https://github.com/futtta/autoptimize/commit/bbab82f2dfe0dcd2863180a764aa38055780ec02), will be in the next update :)
