### ISSUE TITLE
Create pre-release or just tag beta?

### ISSUE THREAD

**Issue by techieshark** [futtta/autoptimize#352]
Hi,

Thanks for your work here. I've run into this little bug: https://wordpress.org/support/topic/undefined-index-after-update-2-8-1/#post-13798929

I'm using Composer to install the plugin, but I think that needs a git tag I can point it at. It's been mentioned that there's a beta zip, but I'm not sure how to target that in the composer.json. https://github.com/futtta/autoptimize/archive/beta.zip

---

Update: 

For now, I've added this to composer.json:

```
"scripts": {
  "post-install-cmd": "wp plugin install --activate https://github.com/futtta/autoptimize/archive/beta.zip",
}
```

**Comment by futtta** [comment]
Sorry for the (very) late reply @techieshark. Given you have a workaround I'm closing here, need to keep my process as simple as possible and pre-releases or tags are not that relevant (the updater works on values in the readme) ;-)
