### ISSUE TITLE
lazyload active but pageSpeed insights reports: Defer offscreen images

### ISSUE THREAD

**Issue by Flaschenzug** [futtta/autoptimize#353]
It looks like the defer offscreen images are not working properly on this page:
https://www.roundnet-deutschland.de/produkte/

In Firefox the images seem to be defered (network tool is loading the images on scroll).
But google sais NO. And in safari it looks like the images are loaded immediately.

Any ideas how / why this is happening?

Wordpress 5.7
Autoptimize 2.8.1

**Comment by futtta** [comment]
Based on the HTML source AO's lazyload is active (as `lazysizes.min.js` is loaded), but in the HTML none of the `<img` tags have the lazyload class added or the src changed to the placeholder, so something indeed is off. 

2 things to check:
* what are your image lazyload settings (exclusions/ lazyload from nth image)?
* can you check with other plugins disabled (and/ or briefly switching themes) as this might be a conflict?

**Comment by Flaschenzug** [comment]
Thanks for the quick reply.
- no exclusions (empty input)
- "0" for the nth image

> can you check with other plugins disabled (and/ or briefly switching themes) as this might be a conflict?
I will check that tonight and update my post here.

**Comment by Flaschenzug** [comment]
Could not find a solution and am a little lost.
If you have any idea how to solve the problem, I would be glad.

**Comment by futtta** [comment]
Well, does the problem still occur when all other plugins are off and you
use a different theme?

**Comment by Flaschenzug** [comment]
It looks like it is the caching plugin i am using/i wrote. But I have no clue why :-/.
When disabled, lazyload is working.

added classed to the images: "ls-is-cached lazyloaded"
What exactly is autoptimize doing with the images? adding class="lazyload" ?


Update: I use
add_filter('autoptimize_html_after_minify', function ($content) {`
to hook in and to cache the code. Is anything happening afterwards that I am missing out?

**Comment by futtta** [comment]
try adding a priority above 10 to your add_filter, that should work?

**Comment by Flaschenzug** [comment]
Wow, that works. Thanks futta.
I guess it is because of the lower priority, so that every other task is executed and than the caching is happening?

**Comment by futtta** [comment]
indeed, you are (were) caching the page before AO had the chance to to the
lazyload stuff :)
