### ISSUE TITLE
WP Rocket - Autoptimize is combining script that shouldn't be combined

### ISSUE THREAD

**Issue by sandyfigueroa** [futtta/autoptimize#354]
**Describe the bug**
WP Rocket has a feature called "Delay JavaScript execution", this function makes some changes to the <script> tag of those script that will be delayed to prevent them to be executed until the user interacts with the website.

For inline scripts, the script tag will be replaced by something like this:
`<script data-rocketlazyloadscript='data:text/javascript;base64,CgkJCDQoJLy......' ></script>`
For JavaScript files (src):
`<script data-rocketlazyloadscript='http://url/to/the/file.js' ></script>`

As you can see, the content, either an inline script or an external file, will be added to the attribute data-rocketlazyloadscript, so, when Autoptimize combines these script, because there is nothing inside the <script> tags, in the resulting combined file there won't be those scripts and the <scripts> tags are removed from the HTML, this prevents the scripts from being executed.

Also, WP Rocket adds a script that enables WPR to execute those delayed scripts when the user interacts with the website: https://snippi.com/s/4bmx88f

This code it is combined to the autoptimize combined file.

**To Reproduce**
1. Activate Delay JavaScript Execution on WP Rocket
2. Add a script to be delayed to the "Scripts to delay" box if needed (Example GA, GTM)
3. Activate JavaScript combination on Autoptimize (Aggregate JS-files option) and "Also aggregate inline JS" if needed.

**Expected behavior**
These scripts shouldn't be combined by Autoptimize.

**Screenshots**
![image](https://user-images.githubusercontent.com/13713107/112231953-b7b8d180-8c05-11eb-8657-8b1a4e06ece7.png)
![image](https://user-images.githubusercontent.com/13713107/112232034-e636ac80-8c05-11eb-95ac-39c5efc6f6c7.png)

**Additional context**
Take in account that not all the scripts in the site are delayed by this function, only those that the user adds to the "Scripts to delay" box on WP Rocket (There are some default tested script):
![image](https://user-images.githubusercontent.com/13713107/112231582-f7cb8480-8c04-11eb-89bf-c7951fe0d8bc.png)

You can see more information about this WP Rocket feature here: [Delay JavaScript Execution](https://docs.wp-rocket.me/article/1349-delay-javascript-execution)

Also, here you can see the same issue opened in the WP Rocket repository: https://github.com/wp-media/wp-rocket/issues/3707

**Comment by futtta** [comment]
OK, can you try adding  `data-rocketlazyloadscript` to the comma-separated list if Javascript Optimization exclusions @sandyfigueroa ?

**Comment by sandyfigueroa** [comment]
Hello @futtta Thank you for your answer. And I apologize for this missing information.

Indeed, excluding **_data-rocketlazyloadscript_** and **_rocket-browser-checker-js-after_** from Autoptimize solves the problem, but by the moment this should be done manually from Autoptimize UI
![image](https://user-images.githubusercontent.com/13713107/112327442-6e0ecc00-8c83-11eb-8263-799d95e252e7.png)

Since many users use Autoptimize alongside WP Rocket, it would be great if this exclusion came with Autoptimize by default.

**Comment by futtta** [comment]
Yes and no; AO does not have a lot of default exclusions except for some
WordPress core thingies (blocks & tinymce for example). Additionally mixing
JS optimization settings between WP Rocket & AO is somewhat ... risky
anyhow. But I do like WP Rocket (great product) so I'll have a think about
it ;-)

**Comment by futtta** [comment]
I'm no sure where `rocket-browser-checker-js-after` is from and why it would need to be excluded too @sandyfigueroa ?

**Comment by futtta** [comment]
found your test-site and saw where `rocket-browser-checker-js-after` came from @sandyfigueroa , added to the default (hard) exclusions, this will be in the next release (likely this weekend).
