### ISSUE TITLE
Stealing from iframe srcdoc

### ISSUE THREAD

**Issue by cass-e-design** [futtta/autoptimize#356]
Thank you for an awesome plugin! On top of the functionality, it's been educational on optimizing sites in general.
 
#### Describe the bug
When inline CSS aggregation and/or linked CSS aggregation are enabled, Autoptimize can steal linked CSS files out of the srcdoc attribute of iframes and aggregate them, applying the CSS to the whole outer page. I haven't tested this for JavaScript, but it may have a similar effect.
#### To Reproduce
Create a post containing an iframe, specifying the contents with the `srcdoc` attribute. Include a `<style>` tag/link a stylesheet. For example:
```html
<h3>demonstrate the effect on elements outside the iframe (This may not be immediately visible, depending on existing page CSS)</h3>
<iframe srcdoc="
  <head>
    <link rel=&quot;stylesheet&quot; href=&quot;STYLESHEET HERE&quot;>
    <style>
      h3 { color: blue; }
    </style>
  </head>
  <body>
    <h3>Content</h3>
  </body>
"></iframe>
```
Then review the page the iframe appears on with aggregation enabled.

*as an additional note, I had to fight WordPress texturizing my quotes inside the Custom HTML block and breaking the iframe. I haven't had to do that before, but beware?
#### Expected behavior
CSS / JavaScript ending up inside of an iframe would be either ignored, or aggregated according to the iframe's context. I'd be perfectly happy if they were ignored, since my usecase is primarily code examples.
#### Workarounds
* Disable inline CSS aggregation and/or linked CSS aggregation to taste (What I've done)
* Use style attribute on individual elements inside srcdoc to assign css
* If not using javascript aggregation, use javascript to embed style/links on page load

I wouldn't call this *urgent*, and I imagine it's relatively rare, but I thought it should be brought your attention once I noticed it. I hope this helps!

**Comment by futtta** [comment]
wow, didn't even know of `<iframe srcdoc` until a minute ago ... I'll have a look at what can be done :-)

**Comment by cass-e-design** [comment]
Neither did I until about two weeks ago lol. I wrote a whole plugin around sending p5.js scripts into iframes for isolation a while back (after doing at least *some* research on how to pre-specify iframe contents) then I started playing around with the inspection tool in the p5.js web editor and realized it had been around since [2012](https://caniuse.com/iframe-srcdoc). Felt very smart. Thank you!

**Comment by futtta** [comment]
ok, given the ... obscurity of iframe srcdoc's, I would propose to simply wrap everything in `<!--noptimize-->` instead as a workaround, as per below example, can you try that?
```html
<!--noptimize--><iframe srcdoc="
  <head>
    <link rel=&quot;stylesheet&quot; href=&quot;STYLESHEET HERE&quot;>
    <style>
      h3 { color: blue; }
    </style>
  </head>
  <body>
    <h3>Content</h3>
  </body>
"></iframe><!--/noptimize-->
```

**Comment by cass-e-design** [comment]
That works in my test case, yes!

**Comment by futtta** [comment]
Great. Given the fact the use of `<iframe srcdoc` is that uncommon and as we now have a confirmed workaround I'm not going to add logic to AO proper to tackle this (at least for now). Thanks for your input/ feedback and for teaching me something new :-)
