### ISSUE TITLE
Some Elementor CSS not combined

### ISSUE THREAD

**Issue by paulschreiber** [futtta/autoptimize#358]
#### Config
With WP 5.7, AO 2.8.3, Elementor 3.1.4.

#### CSS Settings
`Optimize CSS Code?`, `Aggregate CSS-files?` and `Also aggregate inline CSS?` are checked. Exclude is set to the default values.

#### Misc Setting
`Save aggregated script/css as static files?`, `Minify excluded CSS and JS files?`, `Enable 404 fallbacks?` and `Also optimize for logged in editors/ administrators?` are all checked:

I'm seeing three separate Elementor CSS links:
```
<link rel='stylesheet' id='elementor-post-7-css'  href='https://xxx.org/wp-content/cache/autoptimize/css/autoptimize_single_83eef2b47ceb88d1824f8296caa15ae7.css?ver=1617792926' type='text/css' media='all' />  
<link rel='stylesheet' id='elementor-global-css'  href='https://xxx.org/wp-content/cache/autoptimize/css/autoptimize_single_861b2a16d7271b1f48c9ca36bb288675.css?ver=1617792926' type='text/css' media='all' />
<link rel='stylesheet' id='elementor-post-53-css'  href='https://xxx.org/wp-content/cache/autoptimize/css/autoptimize_single_a92ba0ffb479e3df1ff04b481426dc5c.css?ver=1617822213' type='text/css' media='all' />
 ```

in addition to the expected link:
```
<link media="all" href="https://xxx.org/wp-content/cache/autoptimize/css/autoptimize_4e605fbd4fb5f022cad51c2d806144ec.css" rel="stylesheet" />
```

Note also the single quote vs double quote on the attributes, which is weird.

**Comment by futtta** [comment]
Ah, I seem to have missed this one, sorry @paulschreiber 

By default AO excludes CSS from `wp-content/uploads` from aggregation, as per post CSS can bloat the AO cache, removing that exclusion _should_ fix that for you (but do keep an eye on cache size).

**Comment by paulschreiber** [comment]
I don't think anything in my example uses the `uploads` folder.

**Comment by futtta** [comment]
If I'm not immensely mistaking, the elementor post CSS is stored there Paul.
