### ISSUE TITLE
Ajax edit action (500 error)

### ISSUE THREAD

**Issue by dmitrykovaltsov** [futtta/autoptimize#359]
Hi, thanks for developing a best plugin. I am facing the problem of editing the generated critical-css in the admin panel. When I click the [edit button](https://monosnap.com/file/vHH8bD0YflrHxFf6e7XuhNxU6CjxTt), I get a 500 error. 
`{"code":"500","string":"Error reading file ."}`

I found a place in the code. Could you please fix it?
https://github.com/futtta/autoptimize/blob/50f4917a6211675f38ecc7a3676a0d72bb8fbef1/classes/autoptimizeCriticalCSSSettingsAjax.php#L361 If you comment this condition, the edit button works, and the file is loaded into the textarea

Best regards!

**Comment by futtta** [comment]
that's strange ... can you error_log $filename to see why it does not pass the sanitation test?

**Comment by dmitrykovaltsov** [comment]
```php
var_dump( $filename );
string(41) "ccss_9fb21d3ddb6c4ee78e074eed9ee51cb8.css"
sanitize_file_name( $filename )
string(42) "_ccss_9fb21d3ddb6c4ee78e074eed9ee51cb8.css"
```
For some reason, a space appears in the file name, which is replaced by **_** using sanitize_file_name ()

**Comment by futtta** [comment]
Bizzare as that space does not appear in your first var_dump ... looks like you have something conflicting (another plugin?) there?

**Comment by dmitrykovaltsov** [comment]
@futtta Sorry, I found an issue in the theme, the line
`add_filter ('sanitize_file_name', 'make_filename_hash', 10);`
It breaks the `sanitize_file_name ($ filename)` function. Thank you for your feedback.

**Comment by futtta** [comment]
no worries @dmitrykovaltsov , glad to have been able to help :-)
