### ISSUE TITLE
Preloading of SVGs gives wrong "as=" attribute

### ISSUE THREAD

**Issue by pjrobertson** [futtta/autoptimize#360]
Steps to reproduce:

1. Add an SVG URL to the "Preload specific requests (advanced users)" option in Autoptimize > Extra
2. Reload front end web page
3. Note the inserted HTML: `<link rel="preload" href="my_svg.svg" as="other">`
4. Google Chrome gives a warning of "<link rel=preload> must have a valid 'as' value". Reading the specs, "other" is not a [valid option](https://w3c.github.io/preload/#as-attribute)

Expected outcome:

SVGs should be given the `as="image"` attribute, as specified in the W3C specs.

Thanks for this great plugin!

**Comment by futtta** [comment]
ah, I could have just pulled your PR, silly of me. anyway thanks Patrick! :-)

**Comment by pjrobertson** [comment]
No worries, I only figured after-the-fact it was such an easy fix. Appreciate the quick fix!
