### ISSUE TITLE
Feature suggestion - add media queries to image preloads

### ISSUE THREAD

**Issue by colmtroy** [futtta/autoptimize#362]
I've been using the autoptimize_filter_extra_tobepreloaded filter to help preload specific images, but it falls a little short when you bring srcset/responsive images into the equation.
e.g.
I use the following to preload the WooCommerce product featured image.
`add_filter( 'autoptimize_filter_extra_tobepreloaded', 'frontpage_specific_preload' );
function frontpage_specific_preload( $preload_array ) {
	global $product;
	if ( is_product() ) {
		$preload_array[] = wp_get_attachment_url( $product->get_image_id() );
	}
	return $preload_array;
}`

However, with srcset in the mix, there can be n number of options of this image for the browser to choose from when it comes to the actual thumbnail that gets rendered.

Given [preload supports](https://mdn.github.io/html-examples/link-rel-preload/media/) the media attribute it would be cool if there was some way to add a media query rule to the preload filter. I imagine this might be tricky to do given the various hoops you might need to jump through based on the various srcset/sizes attributes that might exist for any given image - but I think some sort of a solution would be ideal to make the best use of this filter.

**Comment by futtta** [comment]
Clearly an interesting idea although I don't know how I would implement that (yet). I'll keep this open, feel free to toss me ideas (or code of PR's ;-) ) my way, who knows what we can come up with ... :-)

**Comment by futtta** [comment]
this was added earlier this year, see https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeImages.php#L997-L1023 :-)
