### ISSUE TITLE
Lazysites fade effect style option (feature request)

### ISSUE THREAD

**Issue by erikyo** [futtta/autoptimize#363]
This is a feature request (and probably the least critical you have ever received), 
but i'd like to find an option that adds the css that makes the fade in effect for images as it's mentioned in the lazysites readme [here](https://github.com/aFarkas/lazysizes#css-api). 
I think it's also easy/transparent to implement... but on the ux/ui side it could be a very cool feature.

I discovered that by chance few days ago day, after a couple of days of testing the "effect" hasn't bored me yet, it's pretty cute, although it can be glitchy if the image already had a transition. It would have been better [animation](https://cssanimation.rocks/transition-vs-animation/), but  ¯\\_(ツ)_/¯... 

Another pretty cool thing: you could also put a [broken image](https://github.com/aFarkas/lazysizes#broken-image-symbol) icon in case it is needed.

**Comment by futtta** [comment]
Nice but indeed somewhat .. less critical so not likely to land in AO itself very soon. The good news though is that you can use the `autoptimize_filter_imgopt_lazyload_cssoutput` filter to add whatever CSS you like, so maybe give that a go? :-)

**Comment by erikyo** [comment]
thank you frank for your fast reponse, as your fast plugin too :) 

Actually I merged lazysites css directly to the site stylesheet, because I think I'll keep lazysites for a long time (even if you rightly abandon it in favor of loading="lazy") because for example even now [it's not compatible with safari mobile](https://caniuse.com/loading-lazy-attr). And if it's not there now, it won't be there for a long time, unfortunately....

Anyway thanks, I'll follow your advice because definitely better!

**Comment by futtta** [comment]
fyi; not planning on removing lazysizes from AO any time soon, in some cases (and apparently Safari mobile is one of those cases) it is the better choice :-)

**Comment by erikyo** [comment]
thank you, because usually customers have an iphone (...) and I wouldn't want to hear their complain 😅

for future users this is the code i use for lazy load with css animation, imho is better than the version with transition because **can** avoid css collisions with already animated images
```
add_filter( 'autoptimize_filter_imgopt_lazyload_cssoutput', 'my_lazyload_cssoutput' );
function my_lazyload_cssoutput() {
	return '<style>.lazyloaded{animation: lazyFadeIn linear .2s;} @keyframes lazyFadeIn { 0% {opacity:0;} 100% {opacity:1;} }</style>';
}
```
@futtta - maybe this filter is need to be placed above the fold because opacity: 0 (or display none) needs to be already in the CSSOM while loading the page (if loaded at the end of the page can cause flickering). I can show you the behaviour, Pm to me or find me on slack.

**Comment by futtta** [comment]
in that case it might be better to echo it as inline CSS using the 
wp_head action instead?

**Comment by erikyo** [comment]
yep! works flawlessly in this way!

```
add_action( 'wp_head', 'my_lazyload_cssoutput' );
function my_lazyload_cssoutput() {
	echo '<style>.lazyloaded{animation: lazyFadeIn linear .2s;} @keyframes lazyFadeIn { 0% {opacity:0;} 100% {opacity:1;} }</style>';
}
```

**Comment by erikyo** [comment]
I was not very happy with using opacity because images that already has this attribute flickered. I found a new way to avoid this  using the css attribute filter: opacity(n). So I want to share it :)

```
add_action( 'wp_head', function() {
  echo '<style>[data-src]{filter: opacity(0);}img.lazyloaded{animation: lazyFadeIn linear .2s;filter: opacity(1);}@keyframes lazyFadeIn{0%{filter: opacity(0);}100%{filter: opacity(1);}}</style>';
});
```

**Comment by futtta** [comment]
nice @erikyo :)
