### ISSUE TITLE
Add support for npm critical for critical CSS.

### ISSUE THREAD

**Issue by gregpriday** [futtta/autoptimize#364]
Would you be open to supporting [npm critical](https://www.npmjs.com/package/critical) as an alternative to [criticalcss.com](https://criticalcss.com)?

Criticalcss.com is great for WordPress sites on shared hosting environments, but if you have the server rights to install Puppeteer and Critical, then it's far more cost-effective to just use these packages. We'd probably just need an option to specify the critical executable path.

If you're open to adding this as a core feature, I'd be happy to try to implement it myself and submit a PR. Alternatively, I could try build it out as an addon plugin.

**Comment by gregpriday** [comment]
As a side note, this is the approach we took in our Laravel Page Cache package. It works well.

https://github.com/siteorigin/laravel-page-cache/blob/develop/src/Jobs/Optimizers/CriticalCss.php

**Comment by futtta** [comment]
Certainly interested Greg! Let's start as an addon plugin and see where that leads?

**Comment by futtta** [comment]
How are things going with this @gregpriday ? :)

**Comment by futtta** [comment]
Hey @gregpriday have you been able to make progress on this idea/ implementation? :)

**Comment by quebecblogue** [comment]
oh yes @gregpriday 

That would be awesome.
