### ISSUE TITLE
Inline JS defer should not create separate JS file

### ISSUE THREAD

**Issue by deep27ak** [futtta/autoptimize#365]
Hello there,

If we enable "Defer Inline JS" then it seems to bundle inline JS into a separate JS file and then execute it as defer. Ideally I would expect the inline scripts to stay inline and deferred.

The problem I see is when we inline certain JS then we have the ability to control the position of each inline JS in the header but when they are added as separate JS then we don't have that control any more so we need to add exclusion for these JS.

I recently tested FlyingPress which also provides similar feature and I observed they were able to defer inline scripts without creating separate files.

Some questions:
1. Does autoptimize segregate the inline JS i.e. all header JS into one file, all inline JS in the body into one and the other for footer?
2. Or do we have individual autoptimize_single_XXX.js file for each inline JS file?
3. Can you please consider to keep the respective JS inline but allowing defer in future releases?

Thanks
Deepak

**Comment by futtta** [comment]
Assuming "also aggregate inline JS" is off; Inline JS is kept at the same place in the HTML, but it is base64-encoded Deepak, it does not (or should not) create separate JS-files. If you can share a URL I'll be happy to have a look at what is happening.

**Comment by deep27ak** [comment]
Attached is the screenshot of my configuration
https://prnt.sc/1f3grqz

Here is a URL of one of the posts. For now I have added an exception for some of my inline JS but analytics script is also inline but I can't seem to find it in the page's source.
https://www.golinuxcloud.com/openssh-authentication-methods-sshd-config/

**Comment by futtta** [comment]
your analytics script is present (base64-encoded);
![image](https://user-images.githubusercontent.com/181297/126863594-524b9f46-dd51-4fd6-bee9-6cab1616400a.png)

**Comment by deep27ak** [comment]
Thanks for looking into this.

I am unable to locate any such string in page's source (attached screenshots), how do I get that detail?
https://prnt.sc/1f5su1m

Here is a screenshot from a different plugin for a similar solution:
https://prnt.sc/1f5v2tv

Although the other plugin has some more bugs so I wanted to stick to autoptimize.

Also in the screenshot which you have shared, the analytics is loaded by autoptimize_single_XXXX.js file so it is loaded as a different JS file instead of inline JS.

I am unable to locate "also aggregate inline JS" option, I can only see "Aggregrate JS Files" which by default turns OFF when selecting "Do not aggregate but defer?"

**Comment by futtta** [comment]
if you consider this original HTML:
![image](https://user-images.githubusercontent.com/181297/126866553-e42acc40-89c3-47e4-b8d9-6b170b8fd56b.png)

You'll see there is both inline JS and a linked JS-file for your analytics. The linked JS-file is not minified (based on the filename, which does not end in min.js) so AO minifies it and it becomes that autoptimize_single-<xyz>.js file. The inline JS (with `analytics` in it indeed) is base64-encoded and deferred, so you can't search for `analytics` as that is part of the base64-encoded string.

![image](https://user-images.githubusercontent.com/181297/126866716-6e98d31a-148d-4f97-96f8-9672331eb410.png)

**Comment by futtta** [comment]
I assume all is clear now @deep27ak, so I'll close, but feel free to follow up if any issue/ question!
