### ISSUE TITLE
Notice: is_page was called incorrectly. Notice: is_single was called incorrectly.

### ISSUE THREAD

**Issue by vestaxpdx** [futtta/autoptimize#367]
Hi

Plugin version: 2.9.1
WP Version: Version 5.8

Seems with the above versions I get.

```
Notice: is_page was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false
Notice: is_single was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false
```

If I disable autoptimize the warnings go. Very strange and only just started happening.

I have disabled every plugin except autoptimize and the warnings still appear. Any ideas?

**Comment by futtta** [comment]
fixed in the beta (the version here on github) with https://github.com/futtta/autoptimize/commit/27874774dcb776775872d1a2fa98d93fcc8859f6, 2.9.2 will be released later this week :)

**Comment by futtta** [comment]
ah, you can off course download & install https://github.com/futtta/autoptimize/archive/refs/heads/beta.zip to have the fix immediately ;-)

**Comment by vestaxpdx** [comment]
Awesome, thanks!
