### ISSUE TITLE
How about embedding small images in img's src?

### ISSUE THREAD

**Issue by igorgatis** [futtta/autoptimize#37]
My website has logos which are about ~2.5k each. They currently are fetched as any other regular image. Sounds like I could spare two calls to my servers in every single page by embedding these two images. Do you think Autopitmize can do that (like it does for CSS background images)?

**Comment by futtta** [comment]
Hmmm .... this is outside of AO's core functionality so unlikely to be added there, but maybe as a power-up (premium add-on) one day, who knows ... :-)
