### ISSUE TITLE
There is an undefined variable in php

### ISSUE THREAD

**Issue by unnamedfeeling** [futtta/autoptimize#372]
Hey
Great plugin!
In the latest https://wpackagist.org/ version (2.9.2) there is a bug in classes/autoptimizeUtils.php:478 - $w3tc_minify is undefined
The code block looks as follows:
```
} elseif ( defined( 'W3TC_VERSION' ) ) {
            $w3tcConfig     = file_get_contents( WP_CONTENT_DIR . '/w3tc-config/master.php' );
            $w3tc_minify_on = strpos( $w3tcConfig, '"minify.enabled": true' );
            if ( $w3tc_minify ) { // <-- there should be $w3tc_minify_on here
                return 'W3 Total Cache';
            }
```
Could you please consider fixing it?
Thanks

**Comment by futtta** [comment]
that's [fixed in the Github version already](https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeUtils.php#L479-L484), I'll release as 2.9.3 on wordpress.org (and I suppose packagist.org as well) later this month.

**Comment by unnamedfeeling** [comment]
Thanks!
