### ISSUE TITLE
Displaying error testing WordPress 5.9

### ISSUE THREAD

**Issue by fellyph** [futtta/autoptimize#374]
Hi autoptimze team, 

I have tested the plugin with the WordPress 5.9 Beta 3 and I got this warning message, after activate the plugin:

![Screen Shot 2021-12-15 at 12 12 49](https://user-images.githubusercontent.com/330792/146184903-233e79ec-6325-4542-bc3d-5c9525e2c102.png)

I'm using local flywheel with php 8.0

**Comment by futtta** [comment]
I *think* that is fixed in the beta with commit https://github.com/futtta/autoptimize/commit/d8566dd6a74c605fca83aa320f7cf35017d81d7e, can you test with [the beta zip-file](https://github.com/futtta/autoptimize/archive/refs/heads/beta.zip) @fellyph ?
