### ISSUE TITLE
Two issues with autoptimize 404 error handler and multisite setup...

### ISSUE THREAD

**Issue by quebecblogue** [futtta/autoptimize#376]
Hi,

I am testing the autoptimize 404 error handler right now and I have found two bug that makes the handler unusable in my case.

1) In autoptimize/config/autoptimize_404_handler.php

The regular expression assumes that a site id will never be more than 999.

> preg_match('#\/([0-9]{1,3})\/(?:js|css)\/[a-z0-9]*_fallback\.(?:js|css)$#', $fallback_target, $child_site_id);

I have some site id in the XXXXX range (my multisite is nearly 20 years old)

While I understand that I might be the only one who has this issue, I don't think you should be imposing that limit since Wordpress doesn't.

That regex fixes it.
> preg_match('#\/([0-9]\*)\/(?:js|css)\/[a-z0-9]*_fallback\.(?:js|css)$#', $fallback_target, $child_site_id);

2) Also, in autoptimize/config/autoptimize_404_handler.php on line 43.

This line doesn't take AUTOPTIMIZE_CACHEFILE_PREFIX into account and assumes an autoptimize_ prefix for the fallback file.
`$fallback_path = $ao_cache_dir . $js_or_css . '/autoptimize_fallback.' . $js_or_css;`

if you have set another prefix it will always return a 410 header.

It should be str_replace'd in check_fallback_php() 

Best regards,

**Comment by futtta** [comment]
agreed (although I would prefer to have a limit to id number, 5 instead of 3), can I convince you to do a PR or would you prefer I handle it? :-)

**Comment by quebecblogue** [comment]
Honestly Frank, I tried. Never used github as I have been all alone in my code all this time. I can't seem to be able to push anything to show up in my fork. I use Atom.

Along with the preg_match in the first post :

On line 649 of classes/autoptimizeCache.php

`$_fallback_php_contents = str_replace( 'autoptimize_fallback', AUTOPTIMIZE_CACHEFILE_PREFIX . "fallback", $_fallback_php_contents ); `

Sorry. I really tried to not be that guy.

Cheers.

**Comment by futtta** [comment]
No worries, I'll take care of it :)

**Comment by futtta** [comment]
Can you re-download the beta and test @quebecblogue ?

**Comment by quebecblogue** [comment]
Yes, I tested it and it seems to work.

Thanks Frank.

**Comment by futtta** [comment]
super, merci :-)
