### ISSUE TITLE
Keep the code base clean

### ISSUE THREAD

**Issue by szepeviktor** [futtta/autoptimize#388]
Hello! 👋🏻

Seen so much dangling spaces in #387 ...

You could Benefit from https://gitlab.com/greut/eclint or the old `eclint` npm package in Travis CI.

**Comment by szepeviktor** [comment]
😲 PHPCS shows ~700 problems.

**Comment by szepeviktor** [comment]
@futtta I leave it 100% up to you.

**Comment by futtta** [comment]
yeah, been some time since I checked phpcs' output, guess I'll need to do some janitorial work ;-)
