### ISSUE TITLE
remove source maps from comined CSS

### ISSUE THREAD

**Issue by webaware** [futtta/autoptimize#39]
When building CSS from something like SASS or LESS, or even combining multiple CSS files together with PostCSS, it's common to generate a [source map file](https://developer.chrome.com/devtools/docs/css-preprocessors). This allows browser debuggers to link back to the source file/line, e.g. when doing an Inspect Element. The source map is often (perhaps typically) linked from the generated CSS file inside a comment, like this:

`/*# sourceMappingURL=style.min.css.map */`

When Autoptimize combines CSS into one file in the Autoptimize cache folder, such relative references break. The browser still tries to load the file when the debugger is open, but it tries to find it within the Autoptimize folder:

`/wp-content/cache/autoptimize/nnn/css/style.min.css.map`

That translates into a WordPress page render (or cache load). It's unnecessary, because anyone wanting to debug their CSS will just turn Autoptimize off while they do that.

I reckon you could happily ditch any source map references in your combined CSS files, because they simply won't be of any use and can generate extra browser fetches when visitors have their debugger open. Removing these references will also squeeze a few more bytes from the combined CSS files :)

**Comment by futtta** [comment]
Sure, I'll look into that. Kind of surprised these aren't removed by the [CSS minimizer](https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/) already.

**Comment by webaware** [comment]
Aha. Right, it'll be because the source files are already minified (.min.css) so CSS minimizer isn't being called. Not sure whether you want to handle this one yourself, but it's probably a pretty simple regex (non-greedy match of `/*# sourceMappingURL ... */`)

**Comment by futtta** [comment]
Yeah, but ... already minified CSS/ JS is "injected late" with [the inject_minified function in autoptimizeBase.php](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeBase.php#L273-L316) and [one of the things done there is actually removing comments](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeBase.php#L291).

So I did a quick test, adding a sourcemappingurl to admin-bar.min.css and I can't reproduce the issue, so (at least in my case) the sourcemappingurl-comment is removed?

**Comment by webaware** [comment]
Interesting. Here's a live example of it *not* removing that.

* [Source](http://shop.webaware.com.au/wp-content/themes/webaware-shop/css/style.min.css)
* [Autoptimized](http://shop.webaware.com.au/wp-content/cache/autoptimize/8/css/autoptimize_8bbb4f35ad93b765f18497a23503a6cb.css)

I don't think I'm doing anything special, no filters or anything. Could it be a setting?

Isn't `inject_minified()` only removing comments for .js files though?

**Comment by webaware** [comment]
Ah, just noticed the second link is to a line that operates on any `/* ... */` comment. Still, not working...

**Comment by futtta** [comment]
indeed, (should) work(s) on comments in both CSS & JS-files. I'll do some more testing to see if I can reproduce.

**Comment by futtta** [comment]
reproduced and -hopefully- fixed, cfr. https://github.com/futtta/autoptimize/commit/8ae8d0aafc48bbd56af420a45fa2c5befe0682c9

so basically `Um` as regex modifier, instead of `Us`, can you test that @webaware ?

**Comment by webaware** [comment]
Nope, didn't change it for my files. I'll have a play with it sometime this week and submit a PR if I fix it. Thanks for looking into it.

**Comment by webaware** [comment]
I take that back, **yes, fixed**. Thanks!

I forgot to take aggressive caching into account and was looking at the cached version. All good with your patch. Cheers!

**Comment by futtta** [comment]
great! :)
