### ISSUE TITLE
Undefined offset autoptimizeStyles.php 

### ISSUE THREAD

**Issue by izulwahidin** [futtta/autoptimize#390]
PHP Notice:  Undefined offset: 1 in /var/www/wp-content/plugins/autoptimize/classes/autoptimizeStyles.php on line 334

**Comment by futtta** [comment]
based on a review of the code this *could* happen when "also aggregate inline CSS" is on but no inline CSS is found (which is ... unexpected), can you confirm that is what triggers the notice @izulwahidin ?

**Comment by futtta** [comment]
any news @izulwahidin ?

**Comment by izulwahidin** [comment]
Ups sorry.
when i open this issue, i tried to disable inline css. and no more error notice.

Thanks for the answer btw.
I'll close this issue
