### ISSUE TITLE
Minified JS broken with private class identifiers

### ISSUE THREAD

**Issue by PLUS-RobertEhrenleitner** [futtta/autoptimize#393]
When a class contains private attributes or methods, the necessary line break or semicolon is not inserted.
As a minimum non-working example, the following class in valid JavaScript syntax does not work:
````
class TestClass {
    #a = 3
    #b = 5
    #fnc1() {
        do_something()
    }
    #fnc(2) {
        do_anything()
    }
}
````
It is minified to:
````
class TestClass{#a=3#b=5#fnc1(){do_something()}#fnc(2){do_anything()}}
````
which contains several syntax errors: There should be line breaks or semicolons between all the attributes and methods.

**Comment by futtta** [comment]
Autoptimize uses [Mr Clay's JS minify](https://github.com/mrclay/jsmin-php/) for the minification @PLUS-RobertEhrenleitner, it might make more sense to report it there. When solved there I can make sure the upstream update is "inherited" by AO as well.

**Comment by PLUS-RobertEhrenleitner** [comment]
Thank you for this fast response, I reissued it [there](https://github.com/mrclay/jsmin-php/issues/15).

**Comment by PLUS-RobertEhrenleitner** [comment]
This issue is fixed by the [commit which updates JSMin including my fix](https://github.com/futtta/autoptimize/commit/cf9f31e9685c284f0ce17b17f2443a4fda2aad20).

**Comment by futtta** [comment]
Thanks for the fixes Robert!
