### ISSUE TITLE
Disable emoji dns-prefetch in ClassicPress

### ISSUE THREAD

**Issue by viktorix** [futtta/autoptimize#394]
We had a ClassicPress user report an issue with dns-prefetch not being disabled for emoji. It looks like the reason is ClassicPress uses a different URL for hosting emoji and your code specifically looks for WP's URL:
https://github.com/futtta/autoptimize/blob/b8916cbf3e1e048598e4b48c9fbfb70397a32744/classes/autoptimizeExtra.php#L210

ClassicPress Twimojie URL is ([source code](https://github.com/ClassicPress/ClassicPress/blob/ed526fcf0ebcaceb6d27f3eb9cc37ab427175afa/src/wp-includes/formatting.php#L5442)):
`https://twemoji.classicpress.net/12/svg/`

## There are two possible solutions:

1. Instead of checking for WP-specific URL, you can disable dns-prefetch with a filter: 
    - `add_filter( 'emoji_svg_url', '__return_false');`
2. You could check if ClassicPress exists and use the correct URL: 
    - `if ( function_exists( 'classicpress_version' ) ) { ... }`

I know there are a bunch of ClassicPress users using Autoptimize, so it would be nice to get this sorted for them if possible.

We'd be happy to submit a PR. Thanks for your time and consideration.

**Comment by futtta** [comment]
If `add_filter( 'emoji_svg_url', '__return_false');` indeed stops the prefetch from happening, then that looks like the easiest solution. 

a PR would be appreciated :)
