### ISSUE TITLE
Optimized JS and inline script order

### ISSUE THREAD

**Issue by Colir** [futtta/autoptimize#398]
Hello, 
I have a problem with the optimization of JS files.

I have inline JS that needs to run after changing the concatenated js by Autoptimize. I don't want Autoptimize to concatenate my inline JS.

But the js file optimized by Autoptimize is always loaded in the last position... I thought that this one was injected the hook "wp-footer" but not... (I can change the placement of wp-footer, it does not change the loading order in the DOM)

Thanks for your help.

**Comment by futtta** [comment]
As AO runs after all normal WordPress logic has been executed, it does not know about wp-footer or enqueueing or ... and simply injects right before `</body>`, but you can change the "injection point" for (CSS and) JS using the API.

An example which would AO replace a "fake" HTML-tag (`<injectjs />`, which you would have to add before your block of excluded inline JS) with the link to the Autoptimized JS;

```php
add_filter( 'autoptimize_filter_js_replacetag', 
    function ( $replacetag ) {
        return array( '<injectjs />', 'replace' );
    },
    10,
    1
);
```
Alternatively you can also pass an existing string (HTML tag) as first element in the array and make the 2nd argument either `before` or `after`.

**Comment by Colir** [comment]
Oh Yeah! clean explanation and working perfectly. Thank you

**Comment by futtta** [comment]
you're welcome :)
