### ISSUE TITLE
Problem with media="print"

### ISSUE THREAD

**Issue by harrinsonmb** [futtta/autoptimize#399]
Hi!

I have recently started using this plugin and I am having a problem with my configuration.

This is my config for CSS:
<img width="1062" alt="Captura de pantalla 2023-03-24 a las 20 25 54" src="https://user-images.githubusercontent.com/4362687/227623955-b49e851f-00bb-4e40-a858-576401a131d9.png">

With this config my application arrives to this point
https://github.com/futtta/autoptimize/blob/c2c37cf6629844ab612437d35801cadec90a355c/classes/autoptimizeStyles.php#L1069

But the result is not the expected, because in the final html output, the media attribute is equal to "print" but there's no onload attribute to change the media attribute to "all". Maybe this line also needs something like `onload="' . $preload_onload . '`, isn't it?

If I am right in what I've just said, It'll be also necessary to move the next line, two lines up. https://github.com/futtta/autoptimize/blob/c2c37cf6629844ab612437d35801cadec90a355c/classes/autoptimizeStyles.php#L1060

Thanks for your help!

**Comment by futtta** [comment]
so what happens if you add something like below as "above the fold CSS"?

```css
a{b:c;}
```

**Comment by harrinsonmb** [comment]
Do you mean, what happen if I fill the textarea for critical CSS?

I think that part works fine, the problem is the output for the `link` element

<img width="1087" alt="Captura de pantalla 2023-03-24 a las 21 29 41" src="https://user-images.githubusercontent.com/4362687/227632754-30b6739f-8bad-4eb6-b037-3b8e3a4f64ee.png">

As you can see the `media`attribute is "print", and there's is no `onload` attribute like there's in other cases.

**Comment by harrinsonmb** [comment]
Sorry, it's my bad I have just remembered that I force the media attribute to be "print" in one of my custom methods. So, everything it's working fine.

Regards!
