### ISSUE TITLE
Changing prefix and folder not working.

### ISSUE THREAD

**Issue by retober** [futtta/autoptimize#40]
If i try to change the served filenames as described in your FAQ with the following commands:
```
define('AUTOPTIMIZE_CACHE_CHILD_DIR','/resources/');
define('AUTOPTIMIZE_CACHEFILE_PREFIX','aggregated_');
```

The files still are named autoptimize_ ... further wordpress gives me the following errors:
```
Notice: Constant AUTOPTIMIZE_CACHE_CHILD_DIR already defined in /var/www/virtual/rcws/html/wordpress/wp-config.php on line 133

Notice: Constant AUTOPTIMIZE_CACHEFILE_PREFIX already defined in /var/www/virtual/rcws/html/wordpress/wp-config.php on line 134
```

**Comment by futtta** [comment]
guess you add them too late in wp-config.php, can you try moving them more to the top?

**Comment by retober** [comment]
I feel so stupid. I already tried it close to the top but now i moved it below the Salts and it is working.

**Comment by futtta** [comment]
great! :)
