### ISSUE TITLE
Optimised Google Fonts still blocking for 1.3s according to PageSpeed

### ISSUE THREAD

**Issue by adam-ah** [futtta/autoptimize#407]
# Setting enabled
`Combine and link deferred in head (fonts load late, but are not render-blocking), includes display:swap.`

# Snippet in HTML
```
<link rel="stylesheet" media="print" onload="this.onload=null;this.media='all';" id="ao_optimized_gfonts" href="https://fonts.googleapis.com/css?family=Google+Sans+Text:400,500%7CGoogle+Sans+Display:400,500,700%7CInter:regular,700,600%7CLora:600,regular&amp;display=swap">
```

# PageSpeed.web.dev results
From https://pagespeed.web.dev/
<img width="731" alt="image" src="https://github.com/futtta/autoptimize/assets/3745745/ec86c9b6-a608-4086-af22-0971b8bcf793">

Is this a new problem with PageSpeed? The setting and the generated code seems to be correct

**Comment by futtta** [comment]
I have seen this happening before but I have no explanation for it I'm afraid.

I would "remove google fonts" instead ;-)

**Comment by adam-ah** [comment]
I ended up moving it locally (with the OMGF plugin but I guess they all do the same).
I also tried not to use Google Fonts, but the site looks so bare with the default fonts...
Google Fonts seems to be a joke: sluggish hosting for tiny data
