### ISSUE TITLE
Add: option to enable WebP as default output format

### ISSUE THREAD

**Issue by adamsilverstein** [futtta/autoptimize#408]
## Description
When users upload images to WordPress (or run image regeneration), WordPress outputs numerous sub-sized images to serve on the front end.  The `image_editor_output_format` filter (added in vs. 5.8) enables direct control of the output mime type based on the input type. I would propose an option that would output WebP files for any JPEGs that are uploaded. Since WebP is widely supported on both the server and in browsers, this is a safe change for nearly everyone (and note that if the server doesn't support WebP, WordPress will fall back to the original mime type - JPEG). WebPs are ~28% smaller on average than the JPEGs WordPress servers generate.

## Discussion
I realize Autoptimize __already__ connects users to an image CDN/image compression service which frankly is a better option than generating WebPs on the server; however I assume there is a cost to using those services, so some users might appreciate a WebP option. I do consider them somewhat mutually exclusive though, so maybe the WebP option should only be available when you don't have the CDN option enabled.

I created a start on a [pull request](https://github.com/futtta/autoptimize/pull/405) to add this feature, do you think this is something you would want to add? If so, I can work on this more with your feedback, if not no worries - I'm not attached to this suggestion!

**Comment by futtta** [comment]
Hi Adam; given (a) the fact generating webp could increase server load on low-powered shared hosting and (b) AO indeed integrates a CDN-based solution and (c) offering both webp & the CDN-based approach is likely to be confusing UI-wise, I don't think I want to move forwards with this. Thanks for the suggestion though, much appreciated!
