### ISSUE TITLE
PHP Warning in cronjob: Trying to access array offset on value of type int in autoptimizeCacheChecker.php

### ISSUE THREAD

**Issue by mcguffin** [futtta/autoptimize#409]
Hi,
When running a cronjob in wp-cli I get the following Error message:
```
PHP Warning:  Trying to access array offset on value of type int in [REDACTED]/wp-content/plugins/autoptimize/classes/autoptimizeCacheChecker.php on line 59
```
In our setup the cron is running under a system user account with no write access to `wp-content/cache`. 

https://github.com/futtta/autoptimize/blob/a548aab20f739d9a96b7c91cb4468d13fe477c65/classes/autoptimizeCacheChecker.php#L58-L59

I found out `autoptimizeCache::stats()` returns `0` if the cache dir is not writable. IMHO `autoptimizeCache::stats()` would just need to check if `is_dir( AUTOPTIMIZE_CACHE_DIR )` and return a neutral value (like `[ 0, 0, time() ]` ) if not:

https://github.com/futtta/autoptimize/blob/a548aab20f739d9a96b7c91cb4468d13fe477c65/classes/autoptimizeCache.php#L473-L495

Would you care for a PR for these two lines?

**Comment by futtta** [comment]
Hey @mcguffin ; the cacheavail() function checks for the constant AUTOPTIMIZE_CACHE_READONLY and if that is present returns true. 

https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeCache.php#L550-L552

Would setting that constant be an option for you?

**Comment by mcguffin** [comment]
Yes, the error is gone with the following code:
```php
add_action( 'autoptimize_setup_done', function() {
	if ( is_dir( AUTOPTIMIZE_CACHE_DIR ) && ! is_writable( AUTOPTIMIZE_CACHE_DIR ) ) {
		define( 'AUTOPTIMIZE_CACHE_READONLY', 1 );
	}
});
```

I personally would prefer `autoptimizeCache::stats()` to return `[ 0, 0, time() ]` in line 480, like the function doc says...

**Comment by futtta** [comment]
I'm not dead set against making changes to AO proper, but given this is an edge case and given there is a workaround, this is pretty low on the priority-list :-)

Re. the code, you can probably simplify it to;

```php
add_action( 'plugins_loaded', function() {
  if ( defined( 'DOING_CRON' ) ) { 
    define( 'AUTOPTIMIZE_CACHE_READONLY', 1 );
  }
});
```
