### ISSUE TITLE
Creation of dynamic property in autoptimizeProTab.php

### ISSUE THREAD

**Issue by headwalluk** [futtta/autoptimize#410]
The $this->rnd_title is not declared in autoptimizeProTab.php, which causes a warning in PHP8.2. It needs to be declared at class-level.

**Comment by futtta** [comment]
would be great if you could do a test of the version here on github to confirm all is OK now @headwalluk :-)

**Comment by headwalluk** [comment]
I've pulled the new version just now. I see the addition of $rnd_title in "autoptimizeProTab.php" and I can confirm there are zero warnings or errors when running on PHP 8.2.11 (FPM) 👍

**Comment by futtta** [comment]
thanks for the confirmation @headwalluk , this will be in the next AO update (no eta yet though).

**Comment by wkhayrattee** [comment]
I confirmed this all good as well from my end.
Had this issue while upgrading onto PHP 8.2 and WP 6.4.1, was about to create a PR when I saw this has been addressed already here. cheers
