### ISSUE TITLE
Proposal: add Plugin Check workflow

### ISSUE THREAD

**Issue by adamsilverstein** [futtta/autoptimize#412]
## Description 
Plugin Check is a [plugin checking tool](https://github.com/WordPress/plugin-check) developed by the WordPress core team (see [original proposal](https://make.wordpress.org/plugins/2022/07/05/proposal-for-a-wordpress-plugin-checker/)). This tool is used as part of the plugin review process and will help ensure a plugin’s codebase remains up-to-date with the base required standards from the Plugin Review team. The tool includes both static and runtime checks and an ever-growing list of checks for various plugin development requirements and best practices.

## Details
The plugin check can be run automatically using a GitHub [action](https://github.com/swissspidy/wp-plugin-check-action) and the  results of the Plugin Check analysis will be added in the form of annotations on new pull requests.
Specific groups of checks can be enabled or disabled using the `checks` attribute (or folders can be excluded, etc). For an initial implementation, I suggest enabling all checks, then disabling whatever you know you want to ignore. As the Plugin Check grows to include more tests, the list run in the automated action can be trimmed to whatever you prefer.

## Pull request
I have prepped a PR for your review: https://github.com/futtta/autoptimize/pull/411 - I see the workflow hasn't run, maybe they aren't enabled on the repo?

**Comment by futtta** [comment]
> I see the workflow hasn't run, maybe they aren't enabled on the repo?

what isn't enabled on the repo exactly @adamsilverstein ?

**Comment by adamsilverstein** [comment]
> what isn't enabled on the repo exactly @adamsilverstein ?

Maybe running actions or workflows for the repository? 

I was expecting the action I added in the PR to have run, even though it isn't merged yet. Maybe I have something wrong in the workflow file, I will try merging it to my fork to see what happens.

You can see a similar PR I opened in Yoast - https://github.com/Yoast/wordpress-seo/pull/20808/ and the resulting plugin checker run - https://github.com/Yoast/wordpress-seo/pull/20808/checks

**Comment by adamsilverstein** [comment]
The action does seem to run when I opened the PR against my fork, so it is either account or repo related: https://github.com/adamsilverstein/autoptimize/actions/runs/6897518991/job/18765843941?pr=2

**Comment by futtta** [comment]
No idea why it doesn't seem to work on my end (not into github that way), but wow that's a lot of errors/ warnings ... 

Most are due to AO being kind of ancient and thus not using all the newer wordpress-specific alternative functions (e.g. WP_Filesystem functions or `wp_json_encode` or `wp_parse_url`), but most of those I'm not eager to change in the context of "don't fix what is not broken" ;-)

Will have to change a lot of `_e` to `_esc_html_e` though (and similar) ... ;-)

re. the output; it's very verbose, but it is missing what seems to be essential; the file and line number for which the warning/ error was thrown?

**Comment by futtta** [comment]
well, simply merging seems to have triggerer the plugin check :)

thanks for the suggestion, best wishes for 2024 @adamsilverstein !

**Comment by swissspidy** [comment]
> re. the output; it's very verbose, but it is missing what seems to be essential; the file and line number for which the warning/ error was thrown?

@futtta That's just the raw console log output. Every warning/error is filed as an annotation directly in-line within each file. Very useful for PRs. See https://github.com/futtta/autoptimize/actions/runs/7432069708 for a list of files and each warning.

By the way some of the checks (e.g. the database query ones) are likely not accurate for your own project, especially when already using PHPCS anyway, so running the same checks twice would be redundant. You could exclude them from running if desired.
