### ISSUE TITLE
Autoptimize deletes all subfolders in /cache/

### ISSUE THREAD

**Issue by HDDen** [futtta/autoptimize#413]
For example, I'm using "Kama Thumbnail" ( https://wordpress.org/plugins/kama-thumbnail/ ). It creates cropped/scaled copies of images, and puts results to /cache/thumb . When I'm clicking toolbar button "Autoptimize - Clear CSS/JS cache", this folder completely removes from server.

**Comment by futtta** [comment]
No but yes but no; when clearing the AO cache [it stays within it's own folder (by default wp-content/cache/autoptimize)](https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeCache.php#L191) but it will inform (some) page caching plugins of that fact so they should clear their cache (to avoid breaking the site; If the page page cache would not be cleared, it would have references to AO files that are not there any more). Additionally some page caching solutions "listen" for AO's cache being cleared and will clear their own cache (for the exact same reason).

So what likely happening is although you're clicking on "clear CSS/ JS cache" the page cache is cleared as a result and is the page cache in question (I think WP Super Cache for example) will in that case remove everything in the cache folder. So  and although AO does not clear anything outside of it's own directory, a page

hope this clarifies,
frank

**Comment by HDDen** [comment]
Yep, seems to be true, after disabling WP Super Cache problem is gone. Thanks!

**Comment by futtta** [comment]
always happy to help :)
