### ISSUE TITLE
AO installed and now my site is dead meat

### ISSUE THREAD

**Issue by DerPivit** [futtta/autoptimize#418]
What the title says. And I am not able to fix it, even by disabling the plugin, clearing all caches and restoring a DB-Backup from *before* installing this plugin. 

The issue persists and I have no clue why. 

But I do know that I am not the only one with this problem. I should have read the frustrated comments on the plugin-site beforehand. 

In every post containing an image there shows up another image before the content. And I have no clue where the fuck it comes from. There is no reference at all in the source code of the given post.

So could please someone tell me how I repair my website? > https://kiebitz.mchlksr.de/

I attach a scrot of one of the posts in question.

![scrot-2024-07-25_12-58](https://github.com/user-attachments/assets/608d6915-96c1-46d9-9454-3f6503d3d2df)

**Comment by futtta** [comment]
HI; I had a look but I'm afraid this is not related to Autoptimize @DerPivit. I can confirm (a) that Autoptimize is not active on your site and (b) that AO does not make any irreversible changes, so when you disable it (and clear all cache) all is well. 

It looks like the first version of the image is the "featured image" and the 2nd one is the image added in the actual post. You can probably use the page builder (or theme) options not to show the featured image, or you could use CSS to hide it;
`
img.wp-post-image{display:none;}`

hope this helps,
frank

**Comment by DerPivit** [comment]
Thanks a lot, Frank.

You were right. In fact it was an issue with a child-theme. I deleted it and made it new. That was it. :)

**Comment by futtta** [comment]
happy to read you've managed to fix the problem @DerPivit :)

if this was the only issue you encountered when using AO, it might be an idea to give it another go? I'll be here if you need support! :)
