### ISSUE TITLE
Background image data:... URI replacement mistakenly replaces some rulesets and breaks CSS

### ISSUE THREAD

**Issue by synthetiv** [futtta/autoptimize#42]
Hi there,

First off, thank you for the amazing plugin – it's worked flawlessly for me until just recently! :)

On one of my sites, I use the class `.has-background` for certain elements, and I discovered yesterday that if I turned on the "Generate data: URIs for images" setting in Autoptimize, parts of my CSS would get mangled.

I finally tracked this behavior down to the regex on line 299 of classes/autoptimizeStyles.php: it will actually try to replace certain _selectors_ that include the word "background," as long as they're followed somewhere by `url(...)`.

For example, given this CSS:
```css
.has-background { background: url(images/bg.png); }
```
Autoptimize will attempt to replace `background { background: url(images/bg.png)` instead of just `background: url(images.bg.png)`. Thus the replacement adds multiple unmatched `{`s, breaking all CSS rules further down in the file.

I've found a really simple fix that addresses my particular use case, and I'm about to submit a pull request, but I'd appreciate any feedback – maybe there's a good reason for the original regex _not_ to skip over matches containing a `{`.

**Comment by futtta** [comment]
thanks Kenji!

**Comment by synthetiv** [comment]
No problem, thank you!
