### ISSUE TITLE
toolbar; division by zero on line 56

### ISSUE THREAD

**Issue by futtta** [futtta/autoptimize#46]
While testing I all of a sudden got this @pablocusto;

> Warning: Division by zero in /var/www/futtta.be/wordpress/wp-content/plugins/autoptimize/classes/autoptimizeToolbar.php on line 56
> Notice: Undefined offset: -2147483648 in /var/www/futtta.be/wordpress/wp-content/plugins/autoptimize/classes/autoptimizeToolbar.php on line 56

Not sure I understand what's happening, but I'm sure you do? :-)

**Comment by futtta** [comment]
should be fixed with commit https://github.com/futtta/autoptimize/commit/258bf0016c2350d4ae07f24cf5030b769865c593

**Comment by zytzagoo** [comment]
This is weird, I don't have this commit applied and when dumping data just to test quickly by editing autoptimizeToolbar.php after L60:

```php
var_dump($stats, $bytes, $class, $size, $percentage); exit;
```
which results in this output:
```
array (size=3)
  0 => int 0
  1 => int 0
  2 => int 1464706737
int 0
int 0
string '0.00 B' (length=6)
float 0
```

And I get no such warning anywhere... The warning means the divisor is 0, not the dividend? Or?
(which would mean `$class` ended up being `0`?)

Or I might be reading things wrong after a full days work...

**Comment by zytzagoo** [comment]
Fun times: https://3v4l.org/i82FN

**Comment by futtta** [comment]
problem is that the divider is based on $class, which is based on log( $bytes , 1024 ). so if $bytes is 0, things indeed might not always go down well :)

**Comment by zytzagoo** [comment]
It's platform dependant, core issue is in use of `log()`, see: https://3v4l.org/P38Sj

**Comment by pablocusto** [comment]
Oops! Thanks you @zytzagoo 

another way to fix that, maybe could be:
`
$bytes = $stats[1]|1;
`

https://3v4l.org/9eguA

**Comment by futtta** [comment]
I'll let you guys agree on the best approach, you're a lot more knowledgeable :-)

**Comment by pablocusto** [comment]
Don't believe it, maybe all depends on the coffee cups number ;-)

sorry, is better add the condition in this line _(for $bytes does not remain with 1)_:
`$class = min( (int) log( $bytes|1 , 1024 ), count( $si_prefix ) - 1 );`

BTW: We would also have to change the `ceil` by `floor`
`$percentage = floor( $bytes / $max_size * 100 );`

https://3v4l.org/gRSc3

What do you think?

**Comment by futtta** [comment]
so @zytzagoo, @pablocusto, what is your preferred solution? :-)

**Comment by zytzagoo** [comment]
My fork is using what I've committed above until you guys settle on whatever :)
(at which point I'll change my fork to match upstream if needed [so that I can keep up with future updates more easily])

**Comment by pablocusto** [comment]
did the tests and @zytzagoo method has better performance.

this is the test: https://3v4l.org/ZJ0ss

but I think we should change the `ceil `by `floor` to round the percentage value.

**Comment by futtta** [comment]
Great, @zytzagoo could you issue a PR with just this specific fix?

**Comment by zytzagoo** [comment]
Didn't touch `ceil` since it's an unrelated change really (should be a separate commit/pr/issue basically).

Not really sure which is better -- my gut says to stay with ceil since it "errors up" and this is about percentages shown to the users (meaning if they're close to full cache, it's better to be notified "sooner" rather than "later" -- but it's nitpicking, I mean, we're talking 1% up/down difference in the worst case, no?)

Plus, `ceil` doesn't require any further code changes and I'm lazy like that :)

**Comment by futtta** [comment]
thanks for the PR, merged! :)

I prefer to stick with `ceil`, as it's weird to have 0% when you have e.g. 10 files 312KB.

**Comment by pablocusto** [comment]
You're right, I had not thought that. 
That just to 5 Mb are 1%.
