### ISSUE TITLE
Load external dependencies before the optimized script

### ISSUE THREAD

**Issue by wvega** [futtta/autoptimize#48]
Hi,

I have a WordPress plugin that includes JavaScript code that depends on external libraries loaded from a CDN:

* Both the plugin's code and the external library are registered with `wp_register_script`.
* The external library is listed as a dependency of the plugin's code.
* Both scripts are configured to be printed in the footer.

Without Autoptimize, WordPress prints the the `<script>` tags in the necessary order: the external library appears first, then the plugin's code.

With Autoptimize, the optimized script that includes the plugin's code is printed in the page's `<head>` (because the **Force JavaScript in &lt;head&gt;?** setting is enabled), but the external library is still printed before the `</body>`. As you may expect, this causes the the plugin's code to start throwing errors because the external library is not defined.

I noticed that disabling **Force JavaScript in &lt;head&gt;?** fixes the problem, and that maybe the solution for my user's problem. However, I still have a question:

Is it possible to have Autoptimize move the external library to the `<head>` as well, whenever the **Force JavaScript in &lt;head&gt;?** setting is enabled AND one of the optimized scripts has a dependency on that library?

**Comment by futtta** [comment]
AO (currently/ historically) does not take dependencies into account and I doubt it will in the near future. So the best solution would indeed be not to force JS in head.

But you can have AO move external dependencies as well by setting the `autoptimize_filter_js_unmovable` filter to false and making sure inline JS is aggregated as well. If that is the case, AO will move all JS either before (default) or after (based on the `domovelast` array which you can alter with the `autoptimize_filter_js_movelast` filter) the optimized JS.

hope this helps :)
frank

**Comment by wvega** [comment]
Thanks @futtta, it helps!

I'll checks those filters and try to come up with a solution to use when disabling the option to force javascript in the head is not possible.
