### ISSUE TITLE
toolbar; honour admin css styles (colors)

### ISSUE THREAD

**Issue by futtta** [futtta/autoptimize#55]
got this remark from a tester;

> The Red icon does not show on the Sunrise admin color scheme.  In general, the color of the icon should be aware of the admin color scheme so it can contrast.

if you have any idea how to do that @pablocusto , "go"! ;-)

But I consider this minor, really (the timeout is way more important).

**Comment by pablocusto** [comment]
Oops! LOL.. added to next fix.

in a couple of hours I make a new pull request with the fix of the timeout
issue  with your suggestion of the modal popup

**Comment by futtta** [comment]
> with your suggestion of the modal popup

great, but I meant a wordpress notice, in the page underneath the h1 :-)
