### ISSUE TITLE
JavaScript default improvements. 

### ISSUE THREAD

**Issue by Volnus** [futtta/autoptimize#58]
Oops published too early. 

Basically, I propose that jquery.js is added to the default ignore list since minifying and moving it to the footer will break most sites, and it ships optimized from core already. You will get more performance moving the rest of the scripts to the footer while ignoring Jquery then you would from moving them all to the header. 

Therefore, I propose the default options in JS are moved to ignoring jquery.js and to uncheck the force JS in head. 

Most sites won't have any problems with this configuration and people will get a larger performance boost this way.

**Comment by futtta** [comment]
you do have somewhat of a point here, but;
* I don't like changing those defaults, this will break some sites that work OK now
* always excluding jquery.js goes against my beliefs ;-)

**Comment by futtta** [comment]
thought about this while mowing my lawn, not sure I should dismiss this. reconsidering ...

**Comment by futtta** [comment]
reconsidered & implemented, cfr. https://github.com/futtta/autoptimize/commit/50b0f8caf96be37e492f531f2d57bdab2a2770f5
