### ISSUE TITLE
Why .gzip?

### ISSUE THREAD

**Issue by X-NicON** [futtta/autoptimize#59]
Nice commit https://github.com/futtta/autoptimize/commit/81e9e8d90243c1a81af0a31ef7e63d877a17ebec
BUT

Why .gzip file extension? rather than the typical .gz?

http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html
.gz

Many apache configuration examples where indicated .gz

**Comment by futtta** [comment]
@Draikin might know :-)

But I guess changing example config to use .gzip instead of .gz would be trivial, no? Else you could change the extension in autoptimizeCache.php. I might add a filter to switch suffix in a later version (although is seems a little ... hardcore ;-) )

frank

**Comment by Draikin** [comment]
You're absolutely right, it should be .gz. I didn't consider that when I added the code. I thought it was still serving the .gzip file directly when I last checked, but the documentation indeed suggests that it check .gz only, so it would be best to change the extension in autoptimizeCache.php accordingly. So a filter is probably unnecessary. Can you commit that change, @X-NicON?

**Comment by X-NicON** [comment]
Thank you so quickly answered.

@Draikin I think a filter is needed, since all these modules are optional, and if it is not enabled, then compressed files will just take up space. Or are you talking about the filter proposed by @futtta (I'm a little confused).

@futtta , as far as I know, the module specified does not support anything except .gz. at your request, I have made a pull request, please check.

**Comment by futtta** [comment]
merged, closing.

thanks again @X-NicON & @Draikin :-)

**Comment by Draikin** [comment]
@X-NicON Sorry for the confusion, I was indeed talking about the filter to change the extension, not the one that's already there. So it's all good!
