### ISSUE TITLE
Autoptimize incompatible with diverting CDN paths

### ISSUE THREAD

**Issue by PatTheMav** [futtta/autoptimize#61]
Not necessarily a bug, more a peculiarity I've found when I configured my WP install to use a CDN url for all external assets:
- Both Autoptimize as well as my CDN plugin were configured to use the same URL/host (`cdn.mydomain.com`)
- The wp-content and wp-include folders were mirrored at a subdirectory of that host (`https://cdn.mydomain.com/blog/...`)
- The CDN plugin took a full path so that config worked out of the box
- Autoptimize only takes a hostname

This leads to the situation where the scripts/stylesheets hosted on the CDN are recognised by the plugin out of the box (due to the CDN host being configured), but as they are on a different path, it can't open them locally.

Example:
- CDN path: `http://cdn.mydomain.com/blog/wp-content/theme/styles.css`
- Real path: `http://www.mydomain.com/wp-content/theme/styles.css`

The plugin fails to concat all the files (even though it tries to) and thus empty stylesheets/scripts are generated.

The following snippet in my functions.php fixed the issue, but would be great if the CDN path could be recognised by the "domain" setting:

```
function ao_fix_uri($uri) {
    return str_replace("/blog/wp-", "/wp-", $uri);
}

add_filter('autoptimize_filter_cssjs_alter_url', 'ao_fix_uri');
```

**Comment by futtta** [comment]
Sorry for not replying earlier @PatTheMav ... AO indeed assumes the CDN url to be a mirror of your origin server. I might look into this at a later stage, but given this is an edge case (most people indeed have CDN-urls that mirror the ones on the origin server exactly) and as you have a workaround, I'm considering this of a lower priority for now.

frank
