### ISSUE TITLE
multiple userSettings values => multiple autoptimize files

### ISSUE THREAD

**Issue by drzraf** [futtta/autoptimize#62]
Hi, I've a lot of "autoptimize_*.js" files created
Here is a diff between the two last:
```
< var userSettings={"url":"\/","uid":"11","time":"1475152253","secure":"1"}
---
> var userSettings={"url":"\/","uid":"58","time":"1475152415","secure":"1"}
33952c33952
<  https://xxx/wp-content/plugins/wp-columna/style.css?bogus=1475152253"
---
>  https://xxx/wp-content/plugins/wp-columna/style.css?bogus=1475152415"
```

Aside from the plugin (which, I guess should be fixed to avoid aggregation), the userSettings comes from core.
I'd not expect it from being aggregated and thus multiply the number of files created by autoptimize.

**Comment by futtta** [comment]
hmmm .... some thoughts;
* userSettings is (at least in my case) not available on the frontend (even when logged in), only in wp-admin. so not sure when core injects userSettings in frontend, but that does not seem default behavior?
* by default AO comes with "aggregate inline JS" disabled, in which case the problem you describe does not exist either (maybe for bbpress or buddypress it does, but that's not core anymore?)
* you can simply add `userSettings` to the comma-separated JS optimization exclusion-list.

so I would consider this not a bug :-)

**Comment by drzraf** [comment]
> * userSettings is (at least in my case) not available on the frontend (even when logged in), only in wp-admin. so not sure when core injects userSettings in frontend, but that does not seem default behavior?

WP 4.6.1 :
wp-includes/script-loader.php

> function wp_default_scripts( &$scripts ) {
[...]
> $scripts->add( 'utils', "/wp-includes/js/utils$suffix.js" );
> did_action( 'init' ) && $scripts->localize( 'utils', 'userSettings', array(
>         'url' => (string) SITECOOKIEPATH,
>         'uid' => (string) get_current_user_id(),
>         'time' => (string) time(),
>         'secure' => (string) ( 'https' === parse_url( site_url(), PHP_URL_SCHEME ) ),
> ) );
[...]

Does not seem related to wp-admin.


> * you can simply add `userSettings` to the comma-separated JS optimization exclusion-list.

Then that's the option I'll consider (as a workaround ;))

**Comment by futtta** [comment]
and wp_default_scripts() is called from ... [wp-admin/load-scripts.php](https://github.com/WordPress/WordPress/blob/a3ffebce3036c69f38e9fd2a798a9e0c13084ea6/wp-admin/load-scripts.php#L37) :-)

so not part of core frontend :-)

so you're on bbpress or buddypress, are you? :-p

**Comment by drzraf** [comment]
> and wp_default_scripts() is called from ... [wp-admin/load-scripts.php](https://github.com/WordPress/WordPress/blob/a3ffebce3036c69f38e9fd2a798a9e0c13084ea6/wp-admin/load-scripts.php#L37) :-)
> 
> so not part of core frontend :-)


but also when new WP_Scripts()
(via init() and do_action_ref_array('wp_default_scripts'))

what happens in :
./wp-includes/functions.wp-scripts.php
./wp-admin/customize.php
./wp-admin/load-scripts.php

## and the inside the following plugins:
./wp-content/plugins/wp-pagenavi/scb/Util.php
./wp-content/plugins/admin-menu-editor/includes/menu-editor-core.php
./wp-content/plugins/wp-maintenance-mode/includes/functions/helpers.php


> so you're on bbpress or buddypress, are you? :-p

no, I'm not.

**Comment by futtta** [comment]
> but also when new WP_Scripts()

Tested again on a virgin WP install; no userSettings to be seen on frontend, so whatever happens in 

> and the inside the following plugins:

well, sure, but that's not core anymore, is it? :-p

conclusion; not core, not a bug, simply add userSettings to your JS exclusion strings and all will be fine :-)

have a nice evening!
frank
