### ISSUE TITLE
Is it possible to only concatenate files?

### ISSUE THREAD

**Issue by XhmikosR** [futtta/autoptimize#63]
Hello.

I was wondering, is there any way to only concatenate CSS/JS files? If not, would you consider adding an option for that?

Thanks!

**Comment by futtta** [comment]
no options (too much of those already), but filters; pass `false` to `autoptimize_js_do_minify` and/ or `autoptimize_css_do_minify` and you'll have un-minified autoptimized files.

have a nice sunday!
frank

**Comment by XhmikosR** [comment]
You mean like this?

```php
add_filter('autoptimize_css_do_minify', __return_false);
add_filter('autoptimize_js_do_minify', __return_false);
```

Thanks!

**Comment by futtta** [comment]
indeed, that should work :-)
