### ISSUE TITLE
`register_uninstall_hook()` called on every page load results into multiple unnecessary database queries

### ISSUE THREAD

**Issue by bjork** [futtta/autoptimize#73]
In the end of the main plugin file, `autoptimize.php`, `register_uninstall_hook()` is called every time the plugin loads. This results into two `SELECT`s and one `UPDATE` on every page load.

While the queries are not very expensive they are unnecessary. Eliminating the queries halves the database query time on my blog from 40 milliseconds to 20 ms.

The easiest way to fix this would be to wrap the call to `register_uninstall_hook()` like this:

```
function autoptimize_activate(){
    register_uninstall_hook( __FILE__, 'autoptimize_uninstall' );
}
register_activation_hook( __FILE__, 'autoptimize_activate' );
```
This way the uninstall hook would only be registered once, not on every page load.

**Comment by futtta** [comment]
good catch, can you issue a pull request? :-)
