### ISSUE TITLE
use of standards WP hooks rather than output buffering

### ISSUE THREAD

**Issue by drzraf** [futtta/autoptimize#77]
I looked at the code and found that most of it is executed inside an output buffering handler.

I would like to know:
- why was it done like this?
- don't recent WP version help streamlining the process?
- why not simply use WP hooks in order to fetch every queued js/css rather than regexp over the final HTML?
- do you know of similar caching plugins hooks standard hooks to achieve the same result? What are their drawback w.r.t to this?

**Comment by futtta** [comment]
for the simple reason that using the OB every little bit if JS/ CSS will be captured, extracted and optimized, even if it was not enqueued properly (which happens all too often) :-)

**Comment by drzraf** [comment]
Thank you for making the initial assumption clear (modules/themes authors do not write good code).
Don't you think that the far cleaner WP-integration of autoptimize in case of processing **only** properly declared assets would be worth the change?
Do you know of any module similar to autoptimze (in quality) that applies in a less intrusive way (more WP-compliant)?

Personally, I think that there should be no intent in processing assets of "bad" module/themes that would rather need fixing, but that's just my opinion.

**Comment by futtta** [comment]
> Do you know of any module similar to autoptimze (in quality) that applies in a less intrusive way (more WP-compliant)?

[bwp-minify](https://wordpress.org/plugins/bwp-minify/) maybe?

**Comment by zytzagoo** [comment]
For properly enqueued assets minification, you should consider https://github.com/kasparsd/minit + various https://github.com/kasparsd/minit/wiki/Minit-Extensions

**Comment by futtta** [comment]
closing time ;-)
