### ISSUE TITLE
Autoptimize not minifying/compressing js/css with no errors

### ISSUE THREAD

**Issue by jageshmk** [futtta/autoptimize#79]
Hi,

Autoptimize not minifying/compressing js/CSS with no errors in Siteground Hosting.
Stage URL is https://staging1.eboardsolutions.com
How to find the reasons in the server?

Thank you!

**Comment by futtta** [comment]
github is not for normal plugin support @jageshmk, can you [open a topic on the wordpress support forum](https://wordpress.org/support/plugin/autoptimize#new-topic-0) instead (and be more precise as to what the problem is)?
