### ISSUE TITLE
CSS Optimization Breaks CSS calc

### ISSUE THREAD

**Issue by Volnus** [futtta/autoptimize#86]
If you are using "calc" autoptimize will make code that looks like this
calc(-50vw + 50%)
into this
calc(-50vw+50%)

The problem being spacing in calc matters as the first rule is valid but the second one isn't. (I just noticed this on a client site I was working on).

**Comment by futtta** [comment]
cfr. https://github.com/futtta/autoptimize/commit/685d76b44043c6ec8aee4414a433673a29bc3c56 this should be OK on the GitHub version (which one day will be AO 2.2 or 2.1.1), can you try that @Volnus ?

**Comment by Volnus** [comment]
Works closing the issue ^^

**Comment by mkmyuu** [comment]
I would like to re-open this issue... CSS calc is still broken under certain circumstances. I am using the following formula:
`width: calc(100% / 3 - (3 - 1) * 1em / 3);`
which autoptimize translates to
`width: calc(100% / 3 -(3 - 1) * 1em / 3);`
Note the minus before the opening parenthese losing its space. Firefox would still display the width correctly, but Chrome does not.

**Comment by futtta** [comment]
Better open an issue at the upstream [YUI CSS compressor PHP port project](https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port) @mkmyuu , if they fix it, it'll trickle down to AO :-)

**Comment by mkmyuu** [comment]
Thank you @futtta ! If anyone else needs this, it is now opened here: https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/issues/61

**Comment by despecial** [comment]
Unfortunately, this still happens. Issue should be re-opened imho.

This is my current workaround. Could be modified with regex and put into the core
```
function fix_css($css) {
	return str_replace( 'min-width:calc(1280px+16vw)','min-width: calc( 1280px + 16vw )', $css );
}
add_filter( 'autoptimize_css_after_minify', 'fix_css', 10, 1 );
```

**Comment by futtta** [comment]
If anyone is up for a regex, I'm taking! ;-)

**Comment by despecial** [comment]
Sure (:

Pattern to match all calc occurences
`/calc(\((?>[^()]+|(?1))*\))/g`

Then we need to add space for all the available operators (+ - * /)

Pattern: `/([\*,\+,\-,\/])/` 
Replace: `" $1 "`

e.g. `preg_replace('/([\*,\+,\-,\/])/',' $1 ',$match);`

Hope this helps!

**Comment by futtta** [comment]
OK, so I just added logic to hide the calc formula from minification.

This logic is off by default though,  but you can enable it with this code snippet;

```php
add_filter( 'autoptimize_filter_css_hide_calc', '__return_true' ):
```

Make sure to clear the AO cache before testing too ;-)

looking forward to your feedback!

**Comment by despecial** [comment]
Hej @futtta 
Thanks for implementing this feature. Here is my feedback from testing it

A) works
- when the calc definition is simple and does not include multiple brackets within the outer brackets

B) does not work
- e.g. `calc( (1280px) + (16vw) ) )` becomes `calc((1280px)+(16vw))` which is problematic (for Firefox)
- another example: `calc( (120px * 5) / 2 )` becomes `calc((120px * 5)/` which is totally messed up

**Comment by futtta** [comment]
weird, so you have the filter active and purged all caches (both AO's and page caches), but calc is still minified??

**Comment by despecial** [comment]
So, nothing changed after adding `add_filter( 'autoptimize_filter_css_hide_calc', '__return_true' );`

Same result for the testing.

**Comment by futtta** [comment]
And you cleared all caches (autoptimize + any page cache you or your host might have)?

**Comment by despecial** [comment]
Re-Downloaded the beta version 3.1.4-beta-1 and it works as intended.
Thanks for fixing this issue!
