### ISSUE TITLE
autoptimize scripts is throwing an error minifying js

### ISSUE THREAD

**Issue by JeffPyeBrook** [futtta/autoptimize#9]
autoptimize scripts is throwing an error 

error type: [8] Undefined variable: input file: ...\wp-content\plugins\autoptimize\classes\external\php\minify-2.1.7-jsmin.php line: 92

Seems to be because the constructor for the JSMin class requires a parameter and none is provided.  We probably don't need to create an object of the class since the method is called staticly

Maybe the line
```
if (@is_callable(array(new JSMin,"minify"))) {
```

should be rewritten to
```
if (@is_callable(array( 'JSMin' , 'minify' ) ) ) {
```

**Comment by futtta** [comment]
confirmed, applied the fix proposed, thanks Jeff!
