### ISSUE TITLE
Yoast seo json-ld not optimized

### ISSUE THREAD

**Issue by grantdb** [futtta/autoptimize#91]
Not sure if this is the place to post this but using the latest Autoptimize 2.1.99 the scripts that Yoast injects into the header for schema in the blog front page are not concatenated when the combine inline js option is selected. I have tried using the init early option. This was the same result in earlier versions of your fine plug as well. Thoughts?

**Comment by futtta** [comment]
thanks for the feedback & testing AO 2.2-.01 @grantdb :)

but AO only optimizes script type=javascript, json-ld is left untouched, this is also the case for AO2.1, so not a regression or bug really.

**Comment by grantdb** [comment]
Yep that's what I figured, thanks!
