### ISSUE TITLE
Not compatible with CAPTCHA by BestWebSoft

### ISSUE THREAD

**Issue by Monter** [futtta/autoptimize#95]
As in the topic - the CAPTCHA by BestWebSoft plugin adds a JavaScript function called bb2_addLoadEvent containing the timestamp that is refreshed every time a page is refreshed in the page header. Enabling minify HTML and JS for the page containing this plug-in creates thousands of JS files in the plugin cache.

Temporary solution: Add "bb2_addLoadEvent" to exceptions in JavaScript optimization settings. Could this be solved by some exception in the plug-in code?

**Comment by futtta** [comment]
your temp solution is the solugion @Monter , I don't (simply can't) add exceptions for all plugins out there :-)

**Comment by Monter** [comment]
O.K., maybe some information about this case in Readme? ;o)

**Comment by futtta** [comment]
there's info on the FAQ on fast increasing cache size already, applies here as well :-)
