### ISSUE TITLE
Google Fonts no longer working

### ISSUE THREAD

**Issue by Kurisutian** [futtta/autoptimize#96]
I tested version 2.2 on my website and found out that despite the settings I made, all Google Fonts are no longer used. With v2.1 which I downgraded to afterwards, all fonts are working again. 
I created my theme with templatetoaster if this information is of any use. Also I'm running the latest WP version 4.7.5.
If you need more information, let me know what I should provide and I will do my best to do so!

**Comment by futtta** [comment]
OK, some questions:
* how are google fonts included? the JS or CSS-link or CSS-import manner?
* are the google fonts being loaded but not applied? or not being loaded (look at your browser's dev tools -> network for that)?
* any (JS-)errors on the browser's console?

**Comment by futtta** [comment]
@Kurisutian can you provide more info?

**Comment by Kurisutian** [comment]
@futtta sorry, for the late reply, I was on vacation for a couple of days. I will provide the information as soon as possible and get back to you! Thanks for your patience. ;)

**Comment by Kurisutian** [comment]
OK, I re-installed the current git version. And funny enough I managed to get both issues, the google font one and the one mentioned in the wordpress forum working. So the newest version I just installed did fix both for me! :)

**Comment by futtta** [comment]
great news, thanks for confirming @Kurisutian ! :-)
