### ISSUE TITLE
WOFF / TFF files on CDN

### ISSUE THREAD

**Issue by jsiegmund** [futtta/autoptimize#97]
I installed Autoptimize on my WP install where I also have WP Super Cache active. I've set up Azure to host a CDN but the cheaper version unfortunately does not come with custom domain names, so I have a CORS issue there. I fixed some of the issues by using the latest version from this repo, but for some reason it's still  trying to load two of the files from the CDN and I suspect that Autoptimize is the cause of this. 

In general I'd love some guidance on how to combine the two. Both WP Super Cache and Autoptimize have CDN settings which I now both have enabled. Should I use only one of two? Also I like the option for WP Super Cache where you can configure extensions the plugin should ignore for CDN so that they're always loaded from the host itself. I've set that to exclude TTF and WOFF, but since those are still being loaded I suspect Autoptimize is putting them somewhere earlier in the pipeline.

Any info would be appreciated :)

**Comment by futtta** [comment]
fonts _should_ be excluded from CDN by default, so this is probably a regression, I'll check.

**Comment by jsiegmund** [comment]
I can confirm turning off the CDN option has fixed the issue, so there definitely seems to be something wrong there.

**Comment by futtta** [comment]
can only reproduce for "dirty" font-url's, e.g. `font.woff?something` or `font.ttf#iefix`. is that the case for you?

**Comment by futtta** [comment]
got a fix for that (those "dirty" font-URL's), will commit in a sec.

**Comment by futtta** [comment]
can you test that @jsiegmund ?

**Comment by jsiegmund** [comment]
Will test it, when I've got the time, I'll get back to you.

**Comment by futtta** [comment]
looking forward to that :)

in the mean time; can you confirm those woff/ ttf files had querystring and/ or anchor appended to the URL @jsiegmund ?

**Comment by jsiegmund** [comment]
Yeah that's confirmed, querystring.

**Comment by jsiegmund** [comment]
Confirmed, working like a charm!

**Comment by futtta** [comment]
thanks for confirming @jsiegmund !
