### ISSUE TITLE
Autoptimize breaks WP navbar when used with Page Builder Sandwich

### ISSUE THREAD

**Issue by bergjs** [futtta/autoptimize#98]
When using Page Builder Sandwich together with Autoptimize the default navbar of WordPress is not visible anymore: https://cl.ly/43002W2t0f1l

I disabled the Autoptimize plugin and it's visible again: https://cl.ly/2A1G3N0s3J2I

**Comment by futtta** [comment]
please open a support topic on [the wordpress support forum for autoptimize](https://wordpress.org/support/plugin/autoptimize#new-post) @bergjs
